// GENERATED by scripts/build-penpot-fn.ts - do not edit by hand.

// services/penpot/vercel-entry.ts
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
var ALLOWLIST = [
  "get-all-projects",
  "import-binfile"
];
var ALLOWED = new Set(ALLOWLIST);
var UPSTREAM_BASE = "https://design.penpot.app/api/rpc/command/";
var CORS = {
  "access-control-allow-origin": "*",
  "access-control-allow-headers": "authorization, content-type",
  "access-control-allow-methods": "POST, OPTIONS"
};
var UPSTREAM_TIMEOUT_MS = 25e3;
var MAX_BODY = 32 * 1024 * 1024;
var config = { api: { bodyParser: false } };
function readRawBody(req) {
  const pre = req.body;
  if (pre !== void 0 && pre !== null && typeof req.on !== "function") {
    if (typeof pre === "string") return Promise.resolve(Buffer.from(pre));
    if (Buffer.isBuffer(pre)) return Promise.resolve(pre);
    return Promise.reject(new Error("Pre-parsed request body cannot be forwarded byte-exact"));
  }
  return new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    req.on("data", (c) => {
      size += c.length;
      if (size > MAX_BODY) {
        reject(new Error("Request body too large"));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}
function sendJson(res, status, body) {
  res.writeHead(status, { ...CORS, "content-type": "application/json; charset=utf-8" });
  res.end(JSON.stringify(body));
}
function createPenpotProxy(fetchImpl = fetch) {
  return async (req, res) => {
    if (req.method === "OPTIONS") {
      res.writeHead(204, CORS);
      res.end();
      return;
    }
    if (req.method !== "POST") {
      sendJson(res, 405, { error: "method-not-allowed", hint: "POST /api/penpot/rpc/<command>" });
      return;
    }
    const pathname = new URL(req.url ?? "/", "http://internal").pathname;
    const m = pathname.match(/\/rpc\/([^/]+)\/?$/);
    const command = m?.[1] ?? "";
    if (!ALLOWED.has(command)) {
      sendJson(res, 403, {
        error: "command-not-allowed",
        hint: `Only these Penpot RPC commands are proxied: ${ALLOWLIST.join(", ")}`
      });
      return;
    }
    let body;
    try {
      body = await readRawBody(req);
    } catch (err) {
      sendJson(res, 400, { error: "bad-request", hint: String(err?.message ?? err) });
      return;
    }
    const headers = {};
    if (typeof req.headers.authorization === "string") headers.authorization = req.headers.authorization;
    if (typeof req.headers["content-type"] === "string") headers["content-type"] = req.headers["content-type"];
    if (typeof req.headers.accept === "string") headers.accept = req.headers.accept;
    const ac = new AbortController();
    let timerFired = false;
    const timer = setTimeout(() => {
      timerFired = true;
      ac.abort();
    }, UPSTREAM_TIMEOUT_MS);
    let upstream;
    try {
      upstream = await fetchImpl(UPSTREAM_BASE + command, {
        method: "POST",
        headers,
        body: body.length > 0 ? new Uint8Array(body) : void 0,
        signal: ac.signal
      });
    } catch (err) {
      clearTimeout(timer);
      const timedOut = timerFired || err?.name === "TimeoutError";
      sendJson(res, 502, {
        error: "penpot-unreachable",
        hint: timedOut ? `design.penpot.app did not answer within ${UPSTREAM_TIMEOUT_MS / 1e3}s` : "could not reach design.penpot.app - check your connection and Penpot status"
      });
      return;
    }
    clearTimeout(timer);
    console.log(`[penpot] ${command} -> ${upstream.status}`);
    res.writeHead(upstream.status, {
      ...CORS,
      "content-type": upstream.headers.get("content-type") ?? "application/json"
    });
    if (upstream.body) {
      try {
        await pipeline(Readable.fromWeb(upstream.body), res);
      } catch {
        if (!res.writableEnded) res.end();
      }
    } else {
      res.end(Buffer.from(await upstream.arrayBuffer()));
    }
  };
}
var vercel_entry_default = createPenpotProxy();
export {
  ALLOWLIST,
  config,
  createPenpotProxy,
  vercel_entry_default as default
};
