// SPDX-License-Identifier: MPL-2.0
/**
 * The context every profile feature module receives as its first argument: the
 * state mountProfile() used to keep as closure variables, plus one namespace of bound
 * operations per module. Generated by scripts/split-closure.ts; edit by hand from here on.
 *
 * The profile (settings) view: your details, the preference cards, storage and the offline manager.
 */
import type { Profile } from '@lolly-tools/core/host-v1';
import type { A11yPrefs } from '../../lib/a11y-prefs.ts';
import type { FeatureFlag } from '../../feature-flags.ts';
import type { UserFontsHost } from '../../user-fonts.ts';
import type { SessionRowContext } from '../profile-storage-model.ts';
import type { CaHealth, IdentityStatus, ProfileHost } from './shared.ts';
import type { ShellUpdater } from '../profile-updates.ts';
import type { MetricsSnapshot } from '../../metrics.ts';
import type { rowsOps } from './rows.ts';
import type { prefsOps } from './prefs.ts';
import type { summariesOps } from './summaries.ts';
import type { shellOps } from './shell.ts';
import type { chromeOps } from './chrome.ts';
import type { headshotOps } from './headshot.ts';
import type { storageOps } from './storage.ts';
import type { offlineOps } from './offline.ts';
import type { connectionsOps } from './connections.ts';
import type { identityOps } from './identity.ts';
import type { mountProfile } from '../profile.ts';

export interface ProfileViewCtx {
  // ---- state (was: closure variables of mountProfile) ----
  viewEl: HTMLElement;
  host: ProfileHost;
  params: string;
  profile: Profile;
  jellyOn: boolean;
  liveProfile: Profile;
  fields: string[];
  activeTheme: string;
  instanceBase: string;
  activeDesignSystemLabel: string;
  adminHref: string | null;
  canChangeInstance: boolean;
  shellUpdater: ShellUpdater | null;
  hasShellUpdater: boolean;
  headshotUrl: string;
  focusParam: string | null;
  focusFlags: boolean;
  focusUseDetails: boolean;
  focusSectionId: string | null;
  OPEN_KEY: "lolly-profile-open";
  openState: Record<string, boolean>;
  jellyHidden: boolean;
  LISTED_FLAGS: FeatureFlag[];
  a11yState: A11yPrefs;
  A11Y_ROWS: Array<{ key: keyof A11yPrefs; label: string; info: string }>;
  followDsState: boolean;
  renderSaveState: boolean;
  displayName: string;
  metrics: MetricsSnapshot;
  headshotFileInput: HTMLInputElement | null;
  refreshStorageMeter: (() => Promise<void>) | null;
  fontsHost: UserFontsHost;
  storageDetails: HTMLDetailsElement | null;
  storageLoaded: boolean;
  toolNameById: Map<string, string>;
  sessRowCtx: SessionRowContext;
  offlineDetails: HTMLDetailsElement | null;
  offlineLoaded: boolean;
  offlineRunUnsub: (() => void) | null;
  aiPolicyUnsub: (() => void) | null;
  connectionsDetails: HTMLDetailsElement | null;
  connectionsLoaded: boolean;
  syncLoaded: boolean;
  identityDetails: HTMLDetailsElement | null;
  PROVIDER_LABELS: Record<string, string>;
  identityStatus: IdentityStatus | null;
  caHealthP: Promise<CaHealth | null> | null;
  identityLoadP: Promise<void> | null;
  // ---- operations, one namespace per module ----
  rows: ReturnType<typeof rowsOps>;
  prefs: ReturnType<typeof prefsOps>;
  summaries: ReturnType<typeof summariesOps>;
  shell: ReturnType<typeof shellOps>;
  chrome: ReturnType<typeof chromeOps>;
  headshot: ReturnType<typeof headshotOps>;
  storage: ReturnType<typeof storageOps>;
  offline: ReturnType<typeof offlineOps>;
  connections: ReturnType<typeof connectionsOps>;
  identity: ReturnType<typeof identityOps>;
  /** The closure itself, for the moved code that re-enters it. */
  mountProfile: typeof mountProfile;
}

/** A module function minus its leading context parameter. */
export type Op<F> = F extends (pv: ProfileViewCtx, ...a: infer A) => infer R ? (...a: A) => R : never;

/** Bind a module function to one context so it can be passed around as a value. */
export function bindOp<F extends (pv: ProfileViewCtx, ...a: never[]) => unknown>(pv: ProfileViewCtx, f: F): Op<F> {
  return ((...a: never[]) => f(pv, ...a)) as Op<F>;
}
