// SPDX-License-Identifier: MPL-2.0
import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import type { TextDocumentV1 } from '@lolly-tools/core';
import type { Page } from 'playwright-core';
import type { CanvasCommitEl } from '../shells/web/src/lib/canvas-commit.ts';
import { getBrowser,closeBrowser } from '../packages/node-shell/src/browsers.ts';
import { createTextStory } from '../engine/src/text-story-document.ts';
import { textSemanticSource } from '../engine/src/text-semantic.ts';
import { journeyDiagnostics } from './helpers/journey-diagnostics.ts';
const origin=process.env.LOLLY_EXPORT_TEST_URL;
async function state(page:Page):Promise<{document:TextDocumentV1;boxes:Array<Record<string,unknown>>}>{return page.evaluate(()=>{const model=(document.getElementById('tool-canvas') as CanvasCommitEl).__lollyModel!();return {document:JSON.parse(model.find(input=>input.id==='textDocument')!.value as string),boxes:model.find(input=>input.id==='boxes')!.value as Array<Record<string,unknown>>};});}
test('Design converts mixed text, edits an ungrouped emoji path, keeps source and reopens', {skip:origin?false:'set LOLLY_EXPORT_TEST_URL',timeout:150000},async()=>{
  const story=createTextStory('story','Office 😀 blue',i=>`p${i}`);story.frameIds=['text'];story.defaultStyle='body';story.spans=[{start:0,end:6,character:{underline:true,color:'#aa2266'}}];
  const doc:TextDocumentV1={version:1,stories:[story],styles:[{id:'body',kind:'paragraph',name:'Body',paragraph:{character:{font:'font',size:50}}}],fonts:[{id:'font',family:'SUSE',sha256:createHash('sha256').update(readFileSync('shells/web/public/fonts/SUSE[wght].ttf')).digest('hex'),faceIndex:0,source:{kind:'bundled',path:'/fonts/SUSE[wght].ttf'}}]};
  const box={id:'text',kind:'text',text:'',textStory:'story',textFrame:JSON.stringify({mode:'fixed',inset:{top:0,right:0,bottom:0,left:0},columns:{count:1,gutter:0,balance:false},verticalAlign:'top'}),x:150,y:140,w:600,h:220,rot:12};
  const browser=await getBrowser(),context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),diagnose=journeyDiagnostics(context,'design-text-vector');page.setDefaultTimeout(20000);
  try{
    await page.goto(`${origin}/design?${new URLSearchParams({boxes:JSON.stringify([box]),textDocument:JSON.stringify(doc),c2pa:'0',imprint:'0'})}`);await page.locator('svg[data-text-frame="text"]').waitFor();
    for(const id of ['navigator','inspector']){const toggle=page.locator(`[data-topbar="${id}"]`);if(await toggle.getAttribute('aria-pressed')==='true')await toggle.click();}
    await page.locator('#tool-canvas [data-box-id="text"]').click();await page.locator('[data-cx="text-convert"]').click();
    const panel=page.getByRole('dialog',{name:'Convert to paths',exact:true});await panel.getByRole('button',{name:'Apply',exact:true}).click();await panel.waitFor({state:'detached'});
    const converted=await state(page),vector=converted.boxes.find(box=>box.kind==='path')!;assert.ok(vector.pathPaint);assert.equal(converted.boxes.length,2);assert.equal(converted.boxes.find(box=>box.id==='text')!.hidden,true);assert.equal(converted.document.stories[0]!.source,story.source);assert.equal(vector.rot,12);
    const id=String(vector.id),geometry=String(vector.path);await page.locator(`[data-box-id="${id}"] svg`).waitFor();await page.locator('[data-cx="nodes"]').click();await page.keyboard.press('ControlOrMeta+a');await page.keyboard.press('ArrowRight');await page.locator('[data-pen="done"]').click();
    assert.notEqual(String((await state(page)).boxes.find(box=>box.id===id)!.path),geometry,'painted geometry is editable');
    await page.locator('#tool-canvas').focus();await page.keyboard.press('ControlOrMeta+z');await page.waitForFunction(({id,geometry})=>((document.getElementById('tool-canvas') as CanvasCommitEl).__lollyModel!().find(input=>input.id==='boxes')!.value as Array<Record<string,unknown>>).find(box=>box.id===id)?.path===geometry,{id,geometry});
    await page.keyboard.press('ControlOrMeta+Shift+g');await page.waitForFunction(()=>((document.getElementById('tool-canvas') as CanvasCommitEl).__lollyModel!().find(input=>input.id==='boxes')!.value as Array<Record<string,unknown>>).filter(box=>box.kind==='path').length>1);
    const parts=(await state(page)).boxes.filter(box=>box.kind==='path');assert.ok(parts.every(box=>box.path),'ungrouped parts keep editable geometry');assert.ok(parts.every(box=>!box.group),'Ungroup exposes individually selectable parts');
    const ordinary=parts.filter(box=>!box.pathPaint);assert.ok(ordinary.length>5,'solid letters and emoji use ordinary path paint');assert.ok(ordinary.every(part=>Number(part.w)<Number(vector.w)&&Number(part.h)<Number(vector.h)),'solid parts have individual selection bounds');
    await page.keyboard.press('ControlOrMeta+g');await page.waitForFunction(()=>((document.getElementById('tool-canvas') as CanvasCommitEl).__lollyModel!().find(input=>input.id==='boxes')!.value as Array<Record<string,unknown>>).filter(box=>box.kind==='path').every(box=>box.group));
    const regrouped=(await state(page)).boxes.filter(box=>box.kind==='path');assert.equal(new Set(regrouped.map(box=>box.group)).size,1);
    await page.keyboard.press('ControlOrMeta+Shift+g');await page.waitForFunction(()=>((document.getElementById('tool-canvas') as CanvasCommitEl).__lollyModel!().find(input=>input.id==='boxes')!.value as Array<Record<string,unknown>>).filter(box=>box.kind==='path').every(box=>!box.group));
    const piece=parts.find(part=>part.pathPaint)!;assert.ok(piece,"the gradient emoji yields a separately editable part");await page.keyboard.press('Escape');const pieceEl=page.locator(`#tool-canvas [data-box-id="${piece.id}"]`);await pieceEl.click();assert.equal(await pieceEl.getAttribute('aria-pressed'),'true','the intended piece is selected');await page.locator('[data-cx="nodes"]').click();const node=await page.locator('.fc-pen-node').first().boundingBox();assert.ok(node);await page.mouse.move(node.x+node.width/2,node.y+node.height/2);await page.mouse.down();await page.mouse.move(node.x+node.width/2+18,node.y+node.height/2+12,{steps:6});await page.mouse.up();await page.waitForFunction(({id,path})=>((document.getElementById('tool-canvas') as CanvasCommitEl).__lollyModel!().find(input=>input.id==='boxes')!.value as Array<Record<string,unknown>>).find(box=>box.id===id)?.path!==path,{id:piece.id,path:piece.path});await page.locator('[data-pen="done"]').click();
    const edited=(await state(page)).boxes.filter(box=>box.kind==='path');assert.notEqual(String(edited.find(box=>box.id===piece.id)!.path),String(piece.path),'one separated path edits independently');for(const other of parts.filter(box=>box.id!==piece.id))assert.equal(edited.find(box=>box.id===other.id)!.path,other.path,'other parts stay intact');
    await page.locator('#tool-canvas').focus();
    for(const condition of ['piece','grouped','separate','original']){await page.keyboard.press('ControlOrMeta+z');await page.waitForFunction(({condition,id,piece})=>{const boxes=(document.getElementById('tool-canvas') as CanvasCommitEl).__lollyModel!().find(input=>input.id==='boxes')!.value as Array<Record<string,unknown>>;const paths=boxes.filter(box=>box.kind==='path');return condition==='piece'?boxes.find(box=>box.id===piece.id)?.path===piece.path:condition==='grouped'?paths.every(box=>box.group):condition==='separate'?paths.length>1&&paths.every(box=>!box.group):paths.length===1&&paths[0]?.id===id;},{condition,id,piece});}await page.locator(`[data-box-id="${id}"] svg`).waitFor();
    await page.keyboard.press('ControlOrMeta+z');await page.locator('svg[data-text-frame="text"]').waitFor();assert.equal((await state(page)).boxes.length,1);
    await page.locator('#tool-canvas [data-box-id="text"]').click();await page.locator('[data-cx="text-convert"]').click();await panel.getByLabel('Convert',{exact:true}).selectOption('emoji');await panel.getByRole('button',{name:'Apply',exact:true}).click();await panel.waitFor({state:'detached'});
    const inline=await state(page),active=inline.document.stories.find(story=>story.frameIds.includes('text'))!;assert.ok(active.source.includes('\ufffc'));assert.equal(textSemanticSource(active).source,story.source);assert.equal(active.inlines.length,1);assert.ok(active.inlines[0]!.svg.includes('<path'));assert.ok(active.inlines[0]!.emojiSources?.length,'converted emoji retains portable source credits');
    await page.keyboard.press('ControlOrMeta+s');await page.locator('.dtb-save-status[data-dirty="false"]').waitFor();const saved=await state(page),savedSvg=await page.locator('svg[data-text-frame="text"]').evaluate(element=>element.outerHTML);await page.reload();await page.locator('svg[data-text-frame="text"]').waitFor();const reopened=await state(page);assert.deepEqual(reopened.document,saved.document);for(const box of saved.boxes){const actual=reopened.boxes.find(item=>item.id===box.id)!;for(const [key,value] of Object.entries(box))assert.equal(String(actual[key]),String(value),`persisted ${box.id}.${key}`);}assert.equal(await page.locator('svg[data-text-frame="text"]').evaluate(element=>element.outerHTML),savedSvg);
    await page.screenshot({path:'/tmp/lolly-271-vector-ui.png'});
  }catch(error){await diagnose(error);throw error;}finally{await context.close();await closeBrowser();}
});

test('linked frame detach freezes its visible geometry and conserves the remaining source', {skip:origin?false:'set LOLLY_EXPORT_TEST_URL',timeout:90000},async()=>{
  const story=createTextStory('linked','A continuous article flows across linked frames without losing any source. '.repeat(5),i=>`p${i}`);story.frameIds=['first','last'];story.defaultStyle='body';
  const doc:TextDocumentV1={version:1,stories:[story],styles:[{id:'body',kind:'paragraph',name:'Body',paragraph:{character:{font:'font',size:24}}}],fonts:[{id:'font',family:'SUSE',sha256:createHash('sha256').update(readFileSync('shells/web/public/fonts/SUSE[wght].ttf')).digest('hex'),faceIndex:0,source:{kind:'bundled',path:'/fonts/SUSE[wght].ttf'}}]};
  const settings=JSON.stringify({mode:'fixed',inset:{top:0,right:0,bottom:0,left:0},columns:{count:1,gutter:0,balance:false},verticalAlign:'top'});
  const boxes=[{id:'first',kind:'text',text:'',textStory:'linked',textFrame:settings,x:60,y:80,w:220,h:100},{id:'last',kind:'text',text:'',textStory:'linked',textFrame:settings,x:350,y:80,w:550,h:450}];
  const browser=await getBrowser(),context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),diagnose=journeyDiagnostics(context,'design-text-linked-vector');page.setDefaultTimeout(20000);
  try{
    await page.goto(`${origin}/design?${new URLSearchParams({boxes:JSON.stringify(boxes),textDocument:JSON.stringify(doc),c2pa:'0',imprint:'0'})}`);await page.locator('#tool-canvas svg[data-text-frame="last"]').waitFor();
    for(const id of ['navigator','inspector']){const toggle=page.locator(`[data-topbar="${id}"]`);if(await toggle.getAttribute('aria-pressed')==='true')await toggle.click();}
    const visible=await page.locator('#tool-canvas svg[data-text-frame="last"] > title').textContent();assert.ok(visible&&visible.length<story.source.length);assert.ok(story.source.endsWith(visible));
    await page.locator('#tool-canvas [data-box-id="last"]').click();await page.locator('[data-cx="text-convert"]').click();
    const panel=page.getByRole('dialog',{name:'Convert to paths',exact:true});await panel.getByLabel('Linked frame conversion',{exact:true}).selectOption('detach');await panel.getByLabel('Keep editable copy',{exact:true}).uncheck();await panel.getByRole('button',{name:'Apply',exact:true}).click();await panel.waitFor({state:'detached'});
    const converted=await state(page);assert.equal(converted.document.stories.length,1);assert.deepEqual(converted.document.stories[0]!.frameIds,['first']);assert.equal(converted.document.stories[0]!.source,story.source.slice(0,-visible.length));
    const vector=converted.boxes.find(box=>box.kind==='path')!;assert.ok(vector.pathPaint&&vector.path);assert.equal(JSON.parse(String(vector.vectorSource)).text,visible);assert.ok(!converted.boxes.some(box=>box.id==='last'));
    await page.locator('#tool-canvas').focus();await page.keyboard.press('ControlOrMeta+z');await page.locator('#tool-canvas svg[data-text-frame="last"]').waitFor();const restored=await state(page);assert.equal(restored.document.stories[0]!.source,story.source);assert.deepEqual(restored.document.stories[0]!.frameIds,story.frameIds);assert.equal(restored.boxes.length,2);
  }catch(error){await diagnose(error);throw error;}finally{await context.close();await closeBrowser();}
});
