// SPDX-License-Identifier: MPL-2.0
/**
 * The runtime-context manifest (/info/docs-render-manifest.json): the facts the in-app
 * docs view (and the interactive figures) implement DocsRenderContext over, instead of the
 * filesystem the static build reads. Precomputed by docs/build.ts's writeDocsManifest().
 *
 * Skips when /info is not built (same contract as docs-meta-descriptions): the file is a
 * build output, gitignored, regenerated by build:info. Run after a build.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const MANIFEST = join(ROOT, 'shells/web/public/info/docs-render-manifest.json');
const SHOTS_DIR = join(ROOT, 'docs/shots');

// Always present (null-or-value). `ai` is OMITTED - it is 'generated'|'composite'|undefined,
// and JSON.stringify drops an undefined field; that is harmless (facts.ai absent ≡ undefined
// to the renderer), and an AI shot serialises its `ai` fine (asserted separately below).
const CREDENTIAL_FIELDS = [
  'signer', 'generator', 'when', 'dimensions', 'model', 'oversight', 'anat', 'recipe', 'src', 'canCopySource',
] as const;

test('the render manifest covers every shot with a size and credential facts', {
  skip: existsSync(MANIFEST) ? false : 'no built /info on disk - run `npm run build:info`',
}, () => {
  const m = JSON.parse(readFileSync(MANIFEST, 'utf8'));
  assert.ok(Array.isArray(m.shots) && m.shots.length > 100, `the shot list is missing or short (${m.shots?.length})`);
  // The manifest shot list is exactly what is committed - a runtime localizedShot()/darkShot()
  // resolves from it, so a drift means the in-app view can't find a shot the static site ships.
  const onDisk = readdirSync(SHOTS_DIR).filter((f) => /\.(svg|png|jpe?g)$/.test(f));
  assert.deepEqual([...m.shots].sort(), onDisk.sort(), 'the manifest shot list drifted from docs/shots');
  for (const file of m.shots) {
    const src = `/info/shots/${file}`;
    // The fit-content 0x0 deadlock guard needs a measured size for every shot.
    assert.ok(m.sizes[src]?.w > 0 && m.sizes[src]?.h > 0, `no measured size for ${file}`);
    // Every committed shot is signed (docs-shot-credentials guards that), so it must carry facts,
    // and those facts must point at the file they describe (the same-file rule).
    assert.equal(m.credentials[src]?.src, src, `credential facts for ${file} missing or misattributed`);
  }
});

test('the manifest credential facts carry the full DocsRenderContext shape', {
  skip: existsSync(MANIFEST) ? false : 'no built /info on disk - run `npm run build:info`',
}, () => {
  const m = JSON.parse(readFileSync(MANIFEST, 'utf8'));
  const sample = Object.values(m.credentials)[0] as Record<string, unknown>;
  assert.ok(sample, 'no credential facts in the manifest');
  for (const k of CREDENTIAL_FIELDS) assert.ok(k in sample, `CredentialFacts missing "${k}"`);
  // A vector shot's anatomy is fully populated (a runtime credential line reads these counts).
  const vec = Object.values(m.credentials).find((c: any) => c?.anat?.kind === 'vector') as any;
  assert.ok(vec, 'expected at least one vector shot with anatomy');
  for (const k of ['paths', 'nodes', 'groups', 'images', 'elements', 'bytes']) {
    assert.equal(typeof vec.anat[k], 'number', `anat.${k} is not a number`);
  }
  // Where an AI declaration exists it survives serialisation (undefined-drop only hides absence).
  const ai = Object.values(m.credentials).find((c: any) => c?.ai) as any;
  if (ai) assert.ok(ai.ai === 'generated' || ai.ai === 'composite', `unexpected ai value ${ai.ai}`);
});
