// SPDX-License-Identifier: MPL-2.0
/**
 * The drift guard between engine/src/grade.ts and community/darkroom/hooks.js.
 *
 * The darkroom tool cannot import the engine - that rule is what lets one tool
 * definition run unchanged in a browser, in Tauri and in the CLI - so when the
 * LUT readers, the tetrahedral sampler and the frame apply were promoted into
 * `engine/src/grade.ts` for the video grade (plans/130), the tool kept its own
 * copy. Two copies of the same maths drift silently, and the failure is not a
 * crash: a graded clip would quietly stop matching the still the user picked
 * the look from.
 *
 * So this file lifts darkroom's own functions out of `hooks.js` the same way
 * the engine runtime compiles a hook (`new Function('host', src + …)`, the
 * pattern tests/fuzz/targets.ts used for these very parsers before they moved)
 * and asserts the two implementations agree:
 *
 *   (a) the parsers, over a corpus of good and malformed text - same record, or
 *       both throw;
 *   (b) the sampler, to 1e-6 over a random 5³ lattice and 50 random triples;
 *   (c) the frame apply at full intensity, byte-for-byte on a random 16×16 RGBA
 *       frame;
 *   (d) the grain + vignette pass, byte-for-byte on random frames.
 *
 * (d) is the one that most needed pinning and the last to arrive. It is the only
 * ported function the engine deliberately CHANGED (a per-frame seed and an
 * optional reference resolution), it is the one whose divergence shows up as a
 * different-looking clip rather than a crash, and until darkroom's copy was
 * lifted into a named `grainVignettePass` there was nothing here to lift - the
 * maths was an inline block, so it had been transcribed by hand into
 * tests/grade.test.ts instead, which pinned the engine to a copy of itself. Both
 * of the engine's extra arguments are left at their defaults below, which is
 * exactly the case that must still reduce to darkroom's own.
 *
 * A failure here means one copy moved. Fix whichever one is wrong; do not
 * relax the comparison.
 *
 * Run with: node --test tests/grade-drift.test.ts
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  type GradeLut,
  type GrainVignetteParams,
  applyGrainVignette,
  applyLutFrame,
  parse3dlLut,
  parseCubeLut,
  sampleLut,
} from '../engine/src/grade.ts';

// ── lifting the tool's copy ──────────────────────────────────────────────────

type ParseFn = (text: string) => GradeLut;
type SampleFn = (lut: GradeLut, r: number, g: number, b: number) => [number, number, number];
type ApplyFn = (imageData: { data: Uint8ClampedArray }, lut: GradeLut) => void;
type GrainFn = (data: Uint8ClampedArray, w: number, h: number, p: GrainVignetteParams) => void;

/** Darkroom's functions, compiled the way the runtime compiles a hook. The
 *  hooks are a plain script, not a module, so a `return` of the names under
 *  test is appended and the whole thing is called with a stub host. */
const darkroom = (() => {
  const src = readFileSync(
    join(dirname(fileURLToPath(import.meta.url)), '..', 'community', 'darkroom', 'hooks.js'),
    'utf8',
  );
  return new Function(
    'host',
    `${src}\nreturn { parseCube, parse3dl, sampleLut, applyPipelineLut, grainVignettePass };`,
  )({}) as {
    parseCube: ParseFn;
    parse3dl: ParseFn;
    sampleLut: SampleFn;
    applyPipelineLut: ApplyFn;
    grainVignettePass: GrainFn;
  };
})();

// ── comparison helpers ───────────────────────────────────────────────────────

/** A tiny xorshift32, independent of both implementations' PRNGs, so the test
 *  corpus cannot accidentally be generated by the code it is checking. */
function seededRandom(seed: number): () => number {
  let s = seed | 0 || 1;
  return () => {
    s ^= s << 13;
    s ^= s >>> 17;
    s ^= s << 5;
    return ((s >>> 0) % 1000000) / 1000000;
  };
}

/**
 * Darkroom leaves DOMAIN_MIN/MAX as whatever `.slice(1, 4).map(Number)`
 * produced, so a short declaration yields a 1- or 2-long array; the engine
 * types the field as a 3-tuple and fills the missing slots with NaN. The two
 * behave identically downstream (an undefined and a NaN both make the
 * normalisation NaN), so the comparison reads both as three numbers.
 */
function domain3(v: unknown): number[] {
  const a = v as number[];
  return [Number(a?.[0]), Number(a?.[1]), Number(a?.[2])];
}

function assertSameLut(mine: GradeLut, theirs: GradeLut, what: string): void {
  assert.equal(mine.kind, theirs.kind, `${what}: kind`);
  assert.equal(mine.size, theirs.size, `${what}: size`);
  assert.equal(mine.title, theirs.title, `${what}: title`);
  assert.deepEqual(domain3(mine.domainMin), domain3(theirs.domainMin), `${what}: domainMin`);
  assert.deepEqual(domain3(mine.domainMax), domain3(theirs.domainMax), `${what}: domainMax`);
  assert.equal(mine.data.length, theirs.data.length, `${what}: data length`);
  for (let i = 0; i < mine.data.length; i++) {
    if (mine.data[i] !== theirs.data[i]) {
      assert.fail(`${what}: data[${i}] ${mine.data[i]} vs ${theirs.data[i]}`);
    }
  }
}

/** Runs both parsers on the same text and asserts they agree - same record, or
 *  both throw. The messages are compared too where both threw, because the
 *  tool surfaces them verbatim in its error banner. */
function assertParsersAgree(mineFn: ParseFn, theirsFn: ParseFn, text: string, what: string): void {
  let mine: GradeLut | null = null;
  let mineErr: Error | null = null;
  let theirs: GradeLut | null = null;
  let theirsErr: Error | null = null;
  try { mine = mineFn(text); } catch (e) { mineErr = e as Error; }
  try { theirs = theirsFn(text); } catch (e) { theirsErr = e as Error; }
  if (theirsErr) {
    assert.ok(mineErr, `${what}: darkroom threw "${theirsErr.message}", the engine did not`);
    assert.equal(mineErr.message, theirsErr.message, `${what}: error message`);
    return;
  }
  assert.ok(!mineErr, `${what}: the engine threw "${mineErr?.message}", darkroom did not`);
  assertSameLut(mine as GradeLut, theirs as GradeLut, what);
}

// ── (a) the parsers, over a corpus ───────────────────────────────────────────

/** A .cube of N³ rows carrying a non-identity ramp, red-fastest. */
function cubeText(N: number, title: string): string {
  const rows: string[] = [`TITLE "${title}"`, `LUT_3D_SIZE ${N}`];
  for (let bI = 0; bI < N; bI++) {
    for (let gI = 0; gI < N; gI++) {
      for (let rI = 0; rI < N; rI++) {
        const r = (rI / (N - 1)) ** 1.4;
        const g = 1 - (1 - gI / (N - 1)) ** 1.2;
        const b = bI / (N - 1) * 0.9 + 0.05;
        rows.push(`${r.toFixed(6)} ${g.toFixed(6)} ${b.toFixed(6)}`);
      }
    }
  }
  return rows.join('\n');
}

/** A .3dl of N³ BLUE-fastest integer rows behind an N-wide mesh line. */
function tdlText(N: number, scale: number): string {
  const rows: string[] = [Array.from({ length: N }, (_, i) => Math.round(i / (N - 1) * 1023)).join(' ')];
  for (let rI = 0; rI < N; rI++) {
    for (let gI = 0; gI < N; gI++) {
      for (let bI = 0; bI < N; bI++) {
        rows.push(`${Math.round(rI / (N - 1) * scale)} ${Math.round(gI / (N - 1) * scale)} ${Math.round(bI / (N - 1) * scale)}`);
      }
    }
  }
  return rows.join('\n');
}

/** The corpus: well-formed text of both formats, then everything the parsers
 *  are meant to reject or shrug off. */
const CORPUS: Array<[string, string]> = [
  ['3d cube', cubeText(4, 'Ramp')],
  ['1d cube', 'LUT_1D_SIZE 5\n0 0 0\n0.1 0.2 0.3\n0.5 0.5 0.5\n0.8 0.7 0.6\n1 1 1\n'],
  ['cube with a declared domain', `LUT_3D_SIZE 2\nDOMAIN_MIN -0.1 -0.2 -0.3\nDOMAIN_MAX 1.1 1.2 1.3\n${cubeText(2, 'x').split('\n').slice(2).join('\n')}`],
  ['cube with comments, CRLF and an unknown keyword', `# hi\r\nLUT_3D_SIZE 2\r\nLUT_IN_VIDEO_RANGE\r\n${cubeText(2, 'y').split('\n').slice(2).join('\r\n')}`],
  ['cube with an unquoted title', `TITLE My Look\n${cubeText(2, 'z').split('\n').slice(1).join('\n')}`],
  ['4-wide .3dl on the 1023 scale', tdlText(4, 1023)],
  ['4-wide .3dl on the 255 scale', tdlText(4, 255)],
  ['5-wide .3dl on the 65535 scale', tdlText(5, 65535)],
  ['truncated cube', ['LUT_3D_SIZE 3', '0 0 0', '1 0 0', '0 1 0'].join('\n')],
  ['cube declaring an over-cap grid', 'LUT_3D_SIZE 500\n0 0 0\n1 1 1\n'],
  ['cube declaring size 1', 'LUT_3D_SIZE 1\n0 0 0\n'],
  ['cube with a non-numeric size', 'LUT_3D_SIZE banana\n0 0 0\n'],
  ['a short DOMAIN_MIN declaration', `LUT_3D_SIZE 2\nDOMAIN_MIN 0.0\n${cubeText(2, 'w').split('\n').slice(2).join('\n')}`],
  ['rows carrying NaN and Infinity', `LUT_3D_SIZE 2\nNaN NaN NaN\nInfinity 0 0\n${cubeText(2, 'v').split('\n').slice(2).join('\n')}`],
  ['plain prose', 'this is not a LUT at all, it is a sentence'],
  ['empty text', ''],
  ['whitespace only', '   \n\t\n  \r\n'],
  ['.3dl with an absurd mesh width', `${Array.from({ length: 200 }, (_, i) => i).join(' ')}\n0 0 0\n1 1 1\n`],
  ['.3dl with no mesh and a non-cube row count', Array.from({ length: 7 }, () => '0 0 0').join('\n')],
  ['a .3dl body with cube keywords glued on', `LUT_3D_SIZE 4\n${tdlText(4, 1023)}`],
];

test('parseCubeLut agrees with darkroom parseCube over the corpus', () => {
  for (const [what, text] of CORPUS) {
    assertParsersAgree(parseCubeLut, darkroom.parseCube, text, `parseCube / ${what}`);
  }
});

test('parse3dlLut agrees with darkroom parse3dl over the corpus', () => {
  for (const [what, text] of CORPUS) {
    assertParsersAgree(parse3dlLut, darkroom.parse3dl, text, `parse3dl / ${what}`);
  }
});

// ── (b) the sampler ──────────────────────────────────────────────────────────

test('sampleLut agrees with darkroom sampleLut to 1e-6 on a random lattice', () => {
  const rnd = seededRandom(0x5eed);
  const N = 5;
  const data = new Float32Array(N * N * N * 3);
  for (let i = 0; i < data.length; i++) data[i] = rnd();
  const lut: GradeLut = {
    kind: '3d', size: N, data, domainMin: [0, 0, 0], domainMax: [1, 1, 1], title: '',
  };
  for (let i = 0; i < 50; i++) {
    const r = rnd();
    const g = rnd();
    const b = rnd();
    const mine = sampleLut(lut, r, g, b);
    const theirs = darkroom.sampleLut(lut, r, g, b);
    for (let c = 0; c < 3; c++) {
      assert.ok(
        Math.abs(mine[c]! - theirs[c]!) <= 1e-6,
        `at ${r},${g},${b} channel ${c}: ${mine[c]} vs ${theirs[c]}`,
      );
    }
  }
});

test('sampleLut agrees on the grid corners, the N === 2 case and a declared domain', () => {
  const rnd = seededRandom(0x1234);
  for (const N of [2, 3, 8]) {
    const data = new Float32Array(N * N * N * 3);
    for (let i = 0; i < data.length; i++) data[i] = rnd();
    const lut: GradeLut = {
      kind: '3d', size: N, data, domainMin: [-0.25, 0, 0.1], domainMax: [1.25, 1, 0.9], title: '',
    };
    for (const v of [0, 0.5, 1, -1, 2]) {
      const mine = sampleLut(lut, v, v, v);
      const theirs = darkroom.sampleLut(lut, v, v, v);
      for (let c = 0; c < 3; c++) {
        assert.ok(Math.abs(mine[c]! - theirs[c]!) <= 1e-6, `N=${N} v=${v} c=${c}: ${mine[c]} vs ${theirs[c]}`);
      }
    }
  }
});

test('sampleLut agrees on a 1D table', () => {
  const rnd = seededRandom(0xabcd);
  const N = 6;
  const data = new Float32Array(N * 3);
  for (let i = 0; i < data.length; i++) data[i] = rnd();
  const lut: GradeLut = {
    kind: '1d', size: N, data, domainMin: [0, 0, 0], domainMax: [1, 1, 1], title: '',
  };
  for (let i = 0; i < 20; i++) {
    const r = rnd();
    const g = rnd();
    const b = rnd();
    const mine = sampleLut(lut, r, g, b);
    const theirs = darkroom.sampleLut(lut, r, g, b);
    for (let c = 0; c < 3; c++) {
      assert.ok(Math.abs(mine[c]! - theirs[c]!) <= 1e-6, `1d channel ${c}: ${mine[c]} vs ${theirs[c]}`);
    }
  }
});

// ── (c) the frame apply ──────────────────────────────────────────────────────

test('applyLutFrame at intensity 1 matches darkroom applyPipelineLut byte-for-byte', () => {
  const rnd = seededRandom(0xc0ffee);
  const N = 9;
  const data = new Float32Array(N * N * N * 3);
  for (let i = 0; i < data.length; i++) data[i] = rnd();
  const lut: GradeLut = {
    kind: '3d', size: N, data, domainMin: [0, 0, 0], domainMax: [1, 1, 1], title: '',
  };

  const source = new Uint8ClampedArray(16 * 16 * 4);
  for (let i = 0; i < source.length; i++) source[i] = Math.floor(rnd() * 256);
  const mine = new Uint8ClampedArray(source);
  const theirs = new Uint8ClampedArray(source);

  applyLutFrame(mine, lut);
  darkroom.applyPipelineLut({ data: theirs }, lut);

  for (let i = 0; i < source.length; i++) {
    if (mine[i] !== theirs[i]) {
      assert.fail(`byte ${i} (px ${i >> 2}, ch ${i & 3}): ${mine[i]} vs ${theirs[i]} (was ${source[i]})`);
    }
  }
  // Sanity: the LUT is random, so it must actually have moved the frame.
  assert.notDeepEqual(Array.from(mine), Array.from(source));
});

test('applyLutFrame at intensity 1 matches on the N === 2 edge grid too', () => {
  const rnd = seededRandom(0x2222);
  const data = new Float32Array(2 * 2 * 2 * 3);
  for (let i = 0; i < data.length; i++) data[i] = rnd();
  const lut: GradeLut = {
    kind: '3d', size: 2, data, domainMin: [0, 0, 0], domainMax: [1, 1, 1], title: '',
  };
  const source = new Uint8ClampedArray([0, 0, 0, 255, 255, 255, 255, 255, 128, 64, 192, 7]);
  const mine = new Uint8ClampedArray(source);
  const theirs = new Uint8ClampedArray(source);
  applyLutFrame(mine, lut);
  darkroom.applyPipelineLut({ data: theirs }, lut);
  assert.deepEqual(Array.from(mine), Array.from(theirs));
});

// ── (d) the grain + vignette pass ────────────────────────────────────────────

/** A random RGBA frame, from a generator neither implementation uses. */
function randomFrame(px: number, rnd: () => number): Uint8ClampedArray {
  const d = new Uint8ClampedArray(px * 4);
  for (let i = 0; i < d.length; i++) d[i] = Math.floor(rnd() * 256);
  return d;
}

test('applyGrainVignette at frame 0 matches darkroom grainVignettePass byte-for-byte', () => {
  const rnd = seededRandom(0x9ea1);
  // Deliberately not a whole number of cells in either axis, so the lattice
  // edges and the fractional bilinear weights are both exercised.
  const W = 29;
  const H = 23;
  const p: GrainVignetteParams = { grain: 0.45, grainSize: 1.6, vignette: 0.7, seed: 7 };
  const source = randomFrame(W * H, rnd);
  const mine = new Uint8ClampedArray(source);
  const theirs = new Uint8ClampedArray(source);

  // Frame 0 and no reference edge: the still's own case, the one the engine's
  // two extra arguments have to collapse to.
  applyGrainVignette(mine, W, H, p, 0);
  darkroom.grainVignettePass(theirs, W, H, p);

  for (let i = 0; i < source.length; i++) {
    if (mine[i] !== theirs[i]) {
      assert.fail(`byte ${i} (px ${i >> 2}, ch ${i & 3}): ${mine[i]} vs ${theirs[i]} (was ${source[i]})`);
    }
  }
  // Sanity: a pass that did nothing would match trivially.
  assert.notDeepEqual(Array.from(mine), Array.from(source), 'the pass actually moved the frame');

  // Omitting frameIndex is frame 0, which is how the still path would call it.
  const implicit = new Uint8ClampedArray(source);
  applyGrainVignette(implicit, W, H, p);
  assert.deepEqual(Array.from(implicit), Array.from(theirs));
});

test('grain and vignette match separately, and across the grainSize range', () => {
  const rnd = seededRandom(0x77aa);
  // The two halves are independent, and either alone must still agree: a drift
  // in one would otherwise be masked by the other moving the same pixels.
  const cases: Array<[string, GrainVignetteParams]> = [
    ['grain only, cell 1 (the slider floor)', { grain: 0.8, grainSize: 1, vignette: 0, seed: 3 }],
    ['grain only, cell 4 (the slider ceiling)', { grain: 0.2, grainSize: 4, vignette: 0, seed: 991 }],
    ['vignette only', { grain: 0, grainSize: 2, vignette: 1, seed: 5 }],
    ['both, on a flat mid-grey field', { grain: 0.5, grainSize: 2.5, vignette: 0.4, seed: 4242 }],
    ['neither (the early return)', { grain: 0, grainSize: 2, vignette: 0, seed: 1 }],
  ];
  for (const [what, p] of cases) {
    for (const [W, H] of [[16, 16], [31, 9]] as Array<[number, number]>) {
      const source = randomFrame(W * H, rnd);
      const mine = new Uint8ClampedArray(source);
      const theirs = new Uint8ClampedArray(source);
      applyGrainVignette(mine, W, H, p, 0);
      darkroom.grainVignettePass(theirs, W, H, p);
      assert.deepEqual(Array.from(mine), Array.from(theirs), `${what} at ${W}×${H}`);
    }
  }
});

test('a LUT parsed by both readers grades a frame identically end to end', () => {
  // The whole chain at once: parse the same text with each copy, then grade the
  // same frame with each. This is the failure the guard actually exists for -
  // the video path reading a .cube and the tool reading the same .cube must
  // land on the same pixels.
  const text = cubeText(6, 'End to end');
  const mineLut = parseCubeLut(text);
  const theirsLut = darkroom.parseCube(text);
  const rnd = seededRandom(0x77);
  const source = new Uint8ClampedArray(16 * 16 * 4);
  for (let i = 0; i < source.length; i++) source[i] = Math.floor(rnd() * 256);
  const mine = new Uint8ClampedArray(source);
  const theirs = new Uint8ClampedArray(source);
  applyLutFrame(mine, mineLut);
  darkroom.applyPipelineLut({ data: theirs }, theirsLut);
  assert.deepEqual(Array.from(mine), Array.from(theirs));
});
