// SPDX-License-Identifier: MPL-2.0

import assert from 'node:assert/strict';
import test from 'node:test';
import type { ParserAssuranceRegistry } from '../scripts/check-parser-assurance.ts';
import {
  parseParserInventory,
  registeredFuzzTargets,
  validateParserAssurance,
} from '../scripts/check-parser-assurance.ts';
import { generateParserInventory, renderParserTable } from '../scripts/build-parser-inventory.ts';

const fuzzSource = `
export const alphaTarget: FuzzTarget = { name: 'alpha', async seeds() { return []; }, async invoke() {} };
export const spareTarget: FuzzTarget = { name: 'spare', async seeds() { return []; }, async invoke() {} };
export const ALL_TARGETS: FuzzTarget[] = [alphaTarget, spareTarget];
`;
const inventoryMarkdown = `
Fuzz coverage is the registered target list in \`tests/fuzz/targets.ts\`.

## The parsers

| Module | Input source | Bounds enforced | Direct test file | Fuzz target | Notes |
|---|---|---|---|---|---|
| \`engine/src/a.ts\` | hostile | cap | test | \`alpha\` (direct) | covered |
| \`engine/src/b.ts\` (reader) | hostile \`A \\| B\` | cap | test | none | waived |

## Writers, not parsers
`;

function registry(): ParserAssuranceRegistry {
  return {
    version: 1,
    inventory: 'docs/parser-inventory.md',
    parsers: {
      'engine/src/a.ts': {
        fuzzTargets: ['alpha'],
        details: {
          inputSource: 'hostile',
          bounds: 'cap',
          directTests: 'test',
          fuzzCoverage: '`alpha` (direct)',
          notes: 'covered',
        },
      },
      'engine/src/b.ts (reader)': {
        waiver: { owner: 'security', expires: '2099-01-01', reason: 'Direct mutation target is tracked for the next parser-hardening pass.' },
        details: {
          inputSource: 'hostile `A | B`',
          bounds: 'cap',
          directTests: 'test',
          fuzzCoverage: 'none',
          notes: 'waived',
        },
      },
    },
  };
}

test('inventory parser handles escaped table pipes and reads the actual target list', () => {
  const targets = registeredFuzzTargets(fuzzSource);
  assert.deepEqual([...targets], ['alpha', 'spare']);
  assert.deepEqual(parseParserInventory(inventoryMarkdown, targets), [
    {
      id: 'engine/src/a.ts',
      source: 'engine/src/a.ts',
      fuzzTargets: ['alpha'],
      details: { inputSource: 'hostile', bounds: 'cap', directTests: 'test', fuzzCoverage: '`alpha` (direct)', notes: 'covered' },
    },
    {
      id: 'engine/src/b.ts (reader)',
      source: 'engine/src/b.ts',
      fuzzTargets: [],
      details: { inputSource: 'hostile `A | B`', bounds: 'cap', directTests: 'test', fuzzCoverage: 'none', notes: 'waived' },
    },
  ]);
});

test('parser inventory table is generated from registry details and escapes cell pipes', () => {
  const table = renderParserTable(registry());
  assert.match(table, /generated by scripts\/build-parser-inventory\.ts/i);
  assert.match(table, /hostile `A \\| B`/);
  const generated = generateParserInventory(inventoryMarkdown, registry(), ['alpha', 'spare']);
  assert.match(generated, /There are 2: `alpha` and `spare`/);
  assert.deepEqual(
    validateParserAssurance({ inventoryMarkdown: generated, fuzzSource, registry: registry(), now: new Date('2026-09-04') }),
    [],
  );
});

test('coverage drift, stale entries and expired or missing waivers fail closed', () => {
  assert.deepEqual(
    validateParserAssurance({ inventoryMarkdown, fuzzSource, registry: registry(), now: new Date('2026-09-04') }),
    [],
  );

  const broken = registry();
  broken.parsers['engine/src/a.ts'] = {
    details: { inputSource: 'hostile', bounds: 'cap', directTests: 'test', fuzzCoverage: '`alpha` (direct)', notes: 'covered' },
  };
  broken.parsers['engine/src/b.ts (reader)']!.waiver!.expires = '2026-01-01';
  broken.parsers['stale.ts'] = {
    fuzzTargets: ['spare'],
    details: { inputSource: 'hostile', bounds: 'cap', directTests: 'test', fuzzCoverage: '`spare`', notes: 'stale' },
  };
  const errors = validateParserAssurance({ inventoryMarkdown, fuzzSource, registry: broken, now: new Date('2026-09-04') });
  assert.match(errors.join('\n'), /fuzz mapping drift/);
  assert.match(errors.join('\n'), /expired/);
  assert.match(errors.join('\n'), /stale registry entry/);
});
