// SPDX-License-Identifier: MPL-2.0
/**
 * The context every start feature module receives as its first argument: the
 * state mountStart() used to keep as closure variables, plus one namespace of bound
 * operations per module. Generated by scripts/split-closure.ts; edit by hand from here on.
 * Make it yours: brand rooms, source imports, exports and recovery.
 */
import type { PenpotUsage, TokensExtraction } from '@lolly/engine';
import type { ModalHandle } from '../../components/modal.ts';
import type { BrandEditorHandle } from '../../lib/brand-editor.ts';
import type { TokenRoleProposal } from '../../lib/brand-propose.ts';
import type { OverviewRoom } from '../../lib/design-system/rooms/overview.ts';
import type { UsageRoom } from '../../lib/design-system/rooms/usage.ts';
import type { VersionsRoom, mountVersionsRoom } from '../../lib/design-system/rooms/versions.ts';
import type { mountCheckpointRecovery } from '../../lib/design-system/checkpoint-recovery.ts';
import type { ColorTokenRow } from '../../lib/design-system/sources/file.ts';
import type { PdfLogoPick } from '../../lib/design-system/sources/pdf.ts';
import type { StartArea } from '../../lib/design-system/start-route.ts';
import type { Tray } from '../../lib/design-system/tray.ts';
import type { TrayUi } from '../../lib/design-system/tray-ui.ts';
import type { PaletteSheet } from '../../lib/design-system/palette-sheet.ts';
import type { PdfFontRow, PickerSource, StartHost } from './shared.ts';
import type { BackTarget } from '../../components/back-pill.ts';
import type { StartRoute } from '../../lib/design-system/start-route.ts';
import type { StudioState } from '../../lib/design-system/studio-state.ts';
import type { SiteTransport } from '../../lib/design-system/sources/website.ts';
import type { navigationOps } from './navigation.ts';
import type { feedbackOps } from './feedback.ts';
import type { brandOps } from './brand.ts';
import type { roomsOps } from './rooms.ts';
import type { exportingOps } from './exporting.ts';
import type { candidatesOps } from './candidates.ts';
import type { imagesOps } from './images.ts';
import type { pdfOps } from './pdf.ts';
import type { siteOps } from './site.ts';
import type { looksOps } from './looks.ts';
import type { referenceOps } from './reference.ts';
import type { AdoptionSnapshot } from '../../bridge/brand-adoption.ts';
import type { savedPageOps } from './saved-page.ts';
import type { sourcesOps } from './sources.ts';
import type { tokensOps } from './tokens.ts';
import type { lifecycleOps } from './lifecycle.ts';

export interface StartCtx {
  // ---- state (was: closure variables of mountStart) ----
  viewEl: HTMLElement;
  host: StartHost;
  params: string;
  backTarget: BackTarget;
  backHref: string;
  backPill: string;
  pillIsHome: boolean;
  homeFab: string;
  route: StartRoute;
  wantWheel: boolean;
  importOpen: boolean;
  focusDsName: boolean;
  urlPrefill: string;
  activeArea: StartArea;
  ROOM_LABELS: Record<StartArea, string>;
  shell: HTMLElement;
  importResult: HTMLElement;
  editorMount: HTMLElement;
  noteEl: HTMLElement | null;
  overviewPanel: HTMLElement;
  usagePanel: HTMLElement;
  usage: UsageRoom | null;
  versionsPanel: HTMLElement;
  versionsBtn: HTMLButtonElement | null;
  versionsLink: HTMLButtonElement | null;
  railEl: HTMLElement;
  roomBtns: HTMLButtonElement[];
  furnishedOnly: HTMLElement[];
  importBtn: HTMLButtonElement | null;
  studio: StudioState;
  tray: Tray;
  marksArriving: boolean;
  editor: BrandEditorHandle | null;
  overview: OverviewRoom | null;
  versions: VersionsRoom | null;
  editorRoot: HTMLElement | null;
  paletteSheet: PaletteSheet | null;
  trayUi: TrayUi | null;
  worthExporting: boolean;
  versionsOffered: boolean;
  openVersions: () => void;
  headDoc: Record<string, unknown> | null;
  getOnDeviceArmed: boolean;
  versionsCtx: { host: Parameters<typeof mountVersionsRoom>[1]["host"]; install: (doc: unknown, action: string) => Promise<void>; undo: () => Promise<boolean>; notify: (msg: string, isError?: boolean) => void; };
  recovery: ReturnType<typeof mountCheckpointRecovery> | null;
  unsubTray: (() => void) | null;
  unsubBeat: (() => void) | null;
  trayToggle: HTMLButtonElement | null;
  trayCountEl: HTMLElement | null;
  pdfPicks: PdfLogoPick[];
  pdfFonts: PdfFontRow[];
  pdfStem: string;
  siteTransport: SiteTransport | null;
  siteReady: boolean;
  siteMarks: File[];
  siteNameOffer: string;
  siteHostName: string;
  importHome: HTMLElement;
  importPanel: HTMLElement;
  importModal: ModalHandle<void> | null;
  SOURCE_NAME: Record<PickerSource, () => string>;
  importReady: Promise<void>;
  SOURCE_NOTE: Record<PickerSource, () => string>;
  handedOver: File;
  installing: boolean;
  importFile: HTMLInputElement;
  importedDoc: Record<string, unknown> | null;
  pendingUsage: PenpotUsage | null;
  pendingRoles: TokenRoleProposal | null;
  roleChoice: string | null;
  pendingTokens: ColorTokenRow[];
  pendingSvgColors: string[];
  importedLabel: string;
  SOURCE_LABEL: Record<TokensExtraction['source'], () => string>;
  dropEl: HTMLElement;
  // ---- operations, one namespace per module ----
  navigation: ReturnType<typeof navigationOps>;
  feedback: ReturnType<typeof feedbackOps>;
  brand: ReturnType<typeof brandOps>;
  rooms: ReturnType<typeof roomsOps>;
  exporting: ReturnType<typeof exportingOps>;
  candidates: ReturnType<typeof candidatesOps>;
  images: ReturnType<typeof imagesOps>;
  pdf: ReturnType<typeof pdfOps>;
  site: ReturnType<typeof siteOps>;
  reference: ReturnType<typeof referenceOps>;
  looks: ReturnType<typeof looksOps>;
  looksModal?: ModalHandle<void> | null;
  savedPage: ReturnType<typeof savedPageOps>;
  referenceRevision: number;
  referenceCancel?: () => void;
  referencePreviewCancel?: () => void;
  adoptionReviewBase?: Promise<AdoptionSnapshot | Error>;
  sources: ReturnType<typeof sourcesOps>;
  tokens: ReturnType<typeof tokensOps>;
  lifecycle: ReturnType<typeof lifecycleOps>;
}

/** A module function minus its leading context parameter. */
export type Op<F> = F extends (start: StartCtx, ...a: infer A) => infer R ? (...a: A) => R : never;

/** Bind a module function to one context so it can be passed around as a value. */
export function bindOp<F extends (start: StartCtx, ...a: never[]) => unknown>(start: StartCtx, f: F): Op<F> {
  return ((...a: never[]) => f(start, ...a)) as Op<F>;
}
