// SPDX-License-Identifier: MPL-2.0
/**
 * The context every catalog feature module receives as its first argument: the
 * state mountCatalog() used to keep as closure variables, plus one namespace of bound
 * operations per module. Generated by scripts/split-closure.ts; edit by hand from here on.
 * The asset catalog view.
 */
import type { CatSort, TypeFilter } from '../catalog-filter.ts';
import type { ModalHandle } from '../../components/modal.ts';
import type { FeaturedRowHandle, FeaturedViewMode } from '../../components/featured-row.ts';
import type { BulkBarConfig } from '../../lib/bulk-bar.ts';
import type { AudioCover } from '../../lib/audio-covers.ts';
import type { SwatchExportFormat } from '../../lib/swatch-export.ts';
import type { PaletteEntry } from '../../palette.ts';
import type { AssetRef, HostV1, Profile } from '@lolly-tools/core/host-v1';
import type { PhotoTreatment } from '../../../../../engine/src/photo-treatment.ts';
import type { IconTheme } from '../../../../../engine/src/icon-theme.ts';
import type { CatFont, CatalogHost } from './shared.ts';
import type { TileSelect } from '../../lib/tile-select.ts';
import type { TileContextMenuHandle } from '../../lib/context-menu.ts';
import type { tilesOps } from './tiles.ts';
import type { thumbsOps } from './thumbs.ts';
import type { filtersOps } from './filters.ts';
import type { sectionsOps } from './sections.ts';
import type { detailsOps } from './details.ts';
import type { userAssetsOps } from './user-assets.ts';
import type { bulkOps } from './bulk.ts';
import type { downloadsOps } from './downloads.ts';
import type { wiringOps } from './wiring.ts';

export interface CatCtx {
  // ---- state (was: closure variables of mountCatalog) ----
  viewEl: HTMLElement;
  hostIn: HostV1;
  params: string;
  host: CatalogHost;
  linkedAsset: string;
  linkedSections: string[];
  profile: Profile | null;
  allAssets: AssetRef[];
  assetById: Map<string, AssetRef>;
  pendingDeletes: Set<string>;
  favSet: Set<string>;
  hiddenSet: Set<string>;
  overrides: Record<string, string>;
  searchHaystack: Map<string, string> | null;
  headshotUrl: string;
  showHidden: boolean;
  loadFailed: boolean;
  urlType: string;
  typeFilter: TypeFilter;
  query: string;
  iconThemes: IconTheme[];
  catIconTheme: string | null;
  iconSvgCache: Map<string, string>;
  photoTreatments: PhotoTreatment[];
  catPhotoTreatment: string | null;
  TREATMENT_FILTER_PREFIX: "lolly-pt-";
  collapsed: Set<string>;
  mounted: boolean;
  firstPaint: boolean;
  dlDialog: HTMLDialogElement | null;
  dlModal: ModalHandle<void> | null;
  detailsDialog: HTMLDialogElement | null;
  detailsModal: ModalHandle<void> | null;
  palette: readonly PaletteEntry[];
  catFonts: CatFont[];
  coverMap: Map<string, AudioCover>;
  coverPool: string[];
  selected: Set<string>;
  tileSelect: TileSelect;
  tileMenu: TileContextMenuHandle;
  FAV_VIEW_KEY: "lolly-catalog-fav-view";
  FAV_STRIP_KEY: "lolly-catalog-fav-strip";
  favView: FeaturedViewMode;
  favStripOn: boolean;
  featuredHandle: FeaturedRowHandle | null;
  lottieThumbs: { destroy(): void } | null;
  audioThumbs: { destroy(): void } | null;
  textThumbs: { destroy(): void } | null;
  motionThumbs: { destroy(): void } | null;
  pdfThumbs: { destroy(): void } | null;
  viewOptsOpen: boolean;
  closeViewOpts: () => void;
  SORT_PREF_KEY: "lolly-catalog-sort";
  LAYOUT_PREF_KEY: "lolly-catalog-layout";
  DENSITY_PREF_KEY: "lolly-catalog-density";
  catLayout: 'grid' | 'list';
  catDensity: 'comfortable' | 'compact';
  CAT_SORTS: readonly CatSort[];
  catSort: CatSort;
  COLLAPSE_KEY: "lolly-catalog-collapsed";
  ALL_SECTION_KEYS: string[];
  FIRST_VISIT_COLLAPSED: string[];
  PASSPORT_CRED_CACHE: Map<string, { found: boolean; state: string; trusted: boolean; } | null>;
  modulesPlayable: boolean | null;
  SWATCH_DOWNLOADS: { fmt: SwatchExportFormat; label: string }[];
  bulkBarCfg: BulkBarConfig;
  dropzoneDispose: (() => void) | null;
  detailsMeterDispose: import('../../lib/audio-meter.ts').MeterHandle | null;
  detailsTransport: import('../../lib/audio-transport.ts').AudioTransport | null;
  vizTeardown: (() => void) | null;
  vizCycleStop: (() => void) | null;
  warmingFavArt: boolean;
  unwireEscape: () => void;
  sessionTexts: Array<{ slot: string; label: string; text: string }> | null;
  sessionTextsLoading: Promise<void> | null;
  releaseSearch: () => void;
  openTargets: string[];
  // ---- operations, one namespace per module ----
  tiles: ReturnType<typeof tilesOps>;
  thumbs: ReturnType<typeof thumbsOps>;
  filters: ReturnType<typeof filtersOps>;
  sections: ReturnType<typeof sectionsOps>;
  details: ReturnType<typeof detailsOps>;
  userAssets: ReturnType<typeof userAssetsOps>;
  bulk: ReturnType<typeof bulkOps>;
  downloads: ReturnType<typeof downloadsOps>;
  wiring: ReturnType<typeof wiringOps>;
}

/** A module function minus its leading context parameter. */
export type Op<F> = F extends (cat: CatCtx, ...a: infer A) => infer R ? (...a: A) => R : never;

/** Bind a module function to one context so it can be passed around as a value. */
export function bindOp<F extends (cat: CatCtx, ...a: never[]) => unknown>(cat: CatCtx, f: F): Op<F> {
  return ((...a: never[]) => f(cat, ...a)) as Op<F>;
}
