// SPDX-License-Identifier: MPL-2.0
/**
 * The context every details feature module receives as its first argument: the
 * state openDetails() used to keep as closure variables, plus one namespace of bound
 * operations per module. Generated by scripts/split-closure.ts; edit by hand from here on.
 * The catalog's details sheet for one asset (a second-level split of views/catalog/details.ts).
 */
import type { TextSignalPanel } from '../valid-text.ts';
import type { HumanizeResult, RewordCandidate, RewordSpan, RewordSuggestion } from '@lolly/engine';
import type { RewordStatus } from '../../lib/reworder.ts';
import type { AssetRef } from '@lolly-tools/core/host-v1';
import type { CatCtx } from './context.ts';
import type { ModalHandle } from '../../components/modal.ts';
import type { panelsOps } from './details-panels.ts';
import type { inlineModesOps } from './details-inline-modes.ts';
import type { sheetOps } from './details-sheet.ts';
import type { openDetails } from './details.ts';

export interface DetailsCtx {
  // ---- state (was: closure variables of openDetails) ----
  cat: CatCtx;
  ref: AssetRef;
  initialTheme: string | null | undefined;
  initialTreatment: string;
  PASSPORT_CRED_CACHE: CatCtx['PASSPORT_CRED_CACHE'];
  TREATMENT_FILTER_PREFIX: string;
  host: CatCtx['host'];
  nav: { prev: AssetRef | null; next: AssetRef | null; };
  base: string;
  isUser: boolean;
  fav: boolean;
  hidden: boolean;
  name: string;
  tags: string[];
  aiKind: string;
  showVerify: boolean;
  themable: boolean;
  treatable: boolean;
  configurable: boolean;
  dTheme: string | null;
  dTreatment: string | null;
  dBaseSvg: string | null;
  dTextContent: string | null;
  dCleanedText: string | null;
  dPreviewText: string | null;
  dWorkBase: string | null;
  dAnalysis: TextSignalPanel | null;
  dHumanizeResult: HumanizeResult | null;
  dSuggestions: RewordSuggestion[];
  dRewordSpans: RewordSpan[];
  dRewordAlts: Map<number, RewordCandidate[]>;
  dModelTouched: boolean;
  dRewordStatus: RewordStatus;
  dRewordBytes: number;
  dCard: HTMLElement | null;
  dTextZoom: number;
  isTextAsset: boolean;
  lottieJson: string;
  isMotionLottie: boolean;
  zoomable: boolean;
  croppable: boolean;
  canUpscale: boolean;
  canRetouch: boolean;
  canGrade: boolean;
  canMatte: boolean;
  ocrAvail: boolean;
  canOcr: boolean;
  canReadDoc: boolean;
  canReadVector: boolean;
  canExtractAudio: boolean;
  videoDecodable: boolean;
  videoEncodable: boolean;
  canVideoMatte: boolean;
  canVideoCrop: boolean;
  canVideoUpscale: boolean;
  canVideoGrade: boolean;
  canVideoTrim: boolean;
  trimmable: boolean;
  ttsBlock: { text?: unknown; voice?: unknown; };
  canEditScript: boolean;
  wasOpen: boolean;
  content: string;
  inlineTrim: (() => void) | null;
  dlAsPopover: import('../../components/body-popover.ts').BodyPopoverHandle | null;
  modal: ModalHandle<void>;
  dlg: HTMLDialogElement;
  inlineCrop: (() => void) | null;
  inlineRetouch: import('../retouch-inline.ts').RetouchInlineHandle | null;
  retouchEntering: boolean;
  inlineGrade: import('../grade-inline.ts').GradeInlineHandle | null;
  gradeEntering: boolean;
  inlineVideoEdit: import('../video-edit-inline.ts').VideoEditInlineHandle | null;
  videoEditEntering: boolean;
  cropEntering: boolean;
  trimEntering: boolean;
  swipeEl: HTMLElement;
  audioEl: HTMLAudioElement;
  // ---- operations, one namespace per module ----
  panels: ReturnType<typeof panelsOps>;
  inlineModes: ReturnType<typeof inlineModesOps>;
  sheet: ReturnType<typeof sheetOps>;
  /** The closure itself, for the moved code that re-enters it. */
  openDetails: typeof openDetails;
}

/** A module function minus its leading context parameter. */
export type Op<F> = F extends (dt: DetailsCtx, ...a: infer A) => infer R ? (...a: A) => R : never;

/** Bind a module function to one context so it can be passed around as a value. */
export function bindOp<F extends (dt: DetailsCtx, ...a: never[]) => unknown>(dt: DetailsCtx, f: F): Op<F> {
  return ((...a: never[]) => f(dt, ...a)) as Op<F>;
}
