// SPDX-License-Identifier: MPL-2.0
/**
 * The context every timeline-panel feature module receives as its first argument: the
 * state initTimelinePanel() used to keep as closure variables, plus one namespace of bound
 * operations per module. Generated by scripts/split-closure.ts; edit by hand from here on.
 * The timeline panel of the design tool.
 */
import type { ModalHandle } from '../../components/modal.ts';
import type { KfChannel } from '../../../../../engine/src/keyframes.ts';
import type { EasingEditorHandle } from '../../components/easing-editor.ts';
import type { SequenceClock } from '../sequence-clock.ts';
import type { RecordSession } from '@lolly-tools/core/host-v1';
import type { Gesture, InspectorGroup, KfBaseChannel, KfLatchRefs, KfPoseField, OnionPref, TakeKind, TakePhase, TimelineAddKind, TimelinePanelOpts } from './shared.ts';
import type { BodyPopoverHandle, PointAnchor } from '../../components/body-popover.ts';
import type { helpersOps } from './helpers.ts';
import type { rowsOps } from './rows.ts';
import type { menusOps } from './menus.ts';
import type { keyframesOps } from './keyframes.ts';
import type { cameraOps } from './camera.ts';
import type { kfDockOps } from './kf-dock.ts';
import type { inspectorPaneOps } from './inspector-pane.ts';
import type { thumbsOps } from './thumbs.ts';
import type { syncingOps } from './syncing.ts';
import type { gesturesOps } from './gestures.ts';
import type { playbackOps } from './playback.ts';
import type { clipsOps } from './clips.ts';
import type { editOps } from './edit.ts';
import type { recordingOps } from './recording.ts';
import type { subtitlesOps } from './subtitles.ts';
import type { panelOps } from './panel.ts';

export interface TpCtx {
  // ---- state (was: closure variables of initTimelinePanel) ----
  opts: TimelinePanelOpts;
  stageEl: TimelinePanelOpts['stageEl'];
  canvasEl: TimelinePanelOpts['canvasEl'];
  runtime: TimelinePanelOpts['runtime'];
  host: TimelinePanelOpts['host'];
  blockId: TimelinePanelOpts['blockId'];
  cfg: TimelinePanelOpts['cfg'];
  getBoxes: TimelinePanelOpts['getBoxes'];
  commit: TimelinePanelOpts['commit'];
  selection: TimelinePanelOpts['selection'];
  onDirty: TimelinePanelOpts['onDirty'];
  reserve: TimelinePanelOpts['reserve'];
  addKinds: TimelineAddKind[];
  open: boolean;
  disposed: boolean;
  seqHold: (() => void) | null;
  panelH: number;
  pxPerSec: number;
  fitPending: boolean;
  gesture: Gesture | null;
  lastKey: string;
  lastAppearance: string;
  focusedId: string;
  snapOn: boolean;
  onionPref: OnionPref | null;
  thumbAbort: AbortController | null;
  cancelIdle: (() => void) | null;
  syncScheduled: boolean;
  syncMissed: boolean;
  moveScheduled: boolean;
  bars: Map<string, HTMLElement>;
  chips: Map<string, HTMLElement>;
  root: HTMLDivElement;
  handle: HTMLDivElement;
  bar: HTMLDivElement;
  playBtn: HTMLButtonElement;
  timeEl: HTMLSpanElement;
  addBtn: HTMLButtonElement;
  splitBtn: HTMLButtonElement;
  snapBtn: HTMLButtonElement;
  onionBtn: HTMLButtonElement;
  zoomOutBtn: HTMLButtonElement;
  zoomInBtn: HTMLButtonElement;
  fitBtn: HTMLButtonElement;
  keysBtn: HTMLButtonElement;
  mobileToolsBtn: HTMLButtonElement;
  micBtn: HTMLButtonElement;
  scriptBtn: HTMLButtonElement;
  camBtn: HTMLButtonElement;
  screenBtn: HTMLButtonElement;
  kfBtn: HTMLButtonElement;
  transcriptBtn: HTMLButtonElement;
  rec: HTMLDivElement;
  recDot: HTMLSpanElement;
  recTime: HTMLSpanElement;
  recMeter: HTMLSpanElement;
  recFill: HTMLSpanElement;
  recNote: HTMLSpanElement;
  transport: HTMLDivElement;
  tools: HTMLDivElement;
  inspector: HTMLDivElement;
  ruler: HTMLDivElement;
  rulerInner: HTMLDivElement;
  tracks: HTMLDivElement;
  inner: HTMLDivElement;
  laneWrap: HTMLDivElement;
  scenery: HTMLDivElement;
  playhead: HTMLDivElement;
  snapline: HTMLDivElement;
  extent: HTMLDivElement;
  trimBadge: HTMLDivElement;
  marquee: HTMLDivElement;
  clock: SequenceClock;
  rulerKey: string;
  rulerNow: number;
  removedMs: { start: number; end: number }[];
  KIND_ICON: Map<string, "link" | "menu" | "search" | "table" | "plane" | "zap" | "help" | "info" | "alert" | "dashboard" | "home" | "shield" | "shieldCheck" | "chevronDown" | "chevronRight" | "chevronLeft" | "close" | "minus" | "menuDots" | "arrowRight" | "arrowLeft" | "check" | "star" | "pin" | "download" | "circleCheck" | "ring" | "sortDir" | "filterLines" | "history" | "play" | "skipBack" | "skipForward" | "externalLink" | "pen" | "move" | "trash" | "duplicate" | "share" | "full-width" | "folderPlus" | "filePlus" | "folder" | "package" | "pill" | "messageCircle" | "panelTop" | "toggleRight" | "credentialShield" | "hexagon" | "layersStack" | "megaphone" | "photos" | "headshot" | "shapes" | "penTool" | "filmStrip" | "palette" | "font" | "uploadImage" | "grid" | "globe" | "paintbrush" | "stamp" | "calendar" | "box" | "wrench" | "hammer" | "flask" | "users" | "sunburst" | "badgeCheck" | "image" | "music" | "tokens" | "document" | "eye" | "eyeOff" | "heart" | "clock" | "hash" | "userCheck" | "sparkle" | "lollipop" | "tag" | "tool" | "user" | "seal" | "mail" | "building" | "cpu" | "lock" | "mapPin" | "camera" | "aiSpark" | "checklist" | "imprint" | "crop" | "droplet" | "opacity" | "convert" | "resize" | "arrowsV" | "arrowsH" | "rotateCw" | "moveX" | "moveY" | "sliders" | "grip" | "fitCover" | "fitContain" | "layers" | "mic" | "speech" | "transcript" | "monitor" | "neuroBeat" | "volumeOn" | "volumeOff" | "refresh" | "repeat" | "dock" | "plus" | "upload" | "zoomIn" | "zoomOut" | "pause" | "scissors" | "animate" | "keyframe" | "unlink" | "cloudRain" | "waves" | "wind" | "flame" | "noise" | "cloudLightning" | "bird" | "moon" | "chimes" | "coffee" | "city" | "train" | "keyboard" | "alignL" | "alignC" | "alignR" | "alignT" | "alignM" | "alignB" | "distH" | "distV" | "orderFront" | "orderForward" | "orderBackward" | "orderBack" | "undo" | "redo" | "fitAll" | "fitArtboard" | "timeline">;
  addMenu: BodyPopoverHandle;
  onionMenu: BodyPopoverHandle;
  onionHold: ReturnType<typeof setTimeout> | 0;
  onionHeld: boolean;
  staggerPoint: PointAnchor;
  staggerIds: string[];
  lastStaggerMs: number;
  staggerPop: BodyPopoverHandle;
  ctxPoint: PointAnchor;
  ctxId: string;
  ctxMulti: string[] | null;
  ctxMenu: BodyPopoverHandle;
  kfCtxPoint: PointAnchor;
  kfCtxId: string;
  kfCtxT: number;
  kfCtxMenu: BodyPopoverHandle;
  inspectorKey: string;
  inspectorShown: boolean;
  inspectorId: string;
  inspectorEnterT: ReturnType<typeof setTimeout> | null;
  easePoint: PointAnchor;
  easeId: string;
  easeField: string;
  easeEditor: EasingEditorHandle | null;
  easeMenu: BodyPopoverHandle;
  kfBtnKey: string;
  kfLatch: KfLatchRefs | null;
  kfLatchKey: string;
  kfCam: { id: string; fields: KfPoseField[] } | null;
  kfCamKey: string;
  kfPoseKey: string;
  KF_POSE_FIELDS: ReadonlyArray<{
    ch: KfChannel;
    label: string;
    step: number;
    range: readonly [number, number];

    slider?: readonly [number, number];

    base?: KfBaseChannel;
  }>;
  KF_CAMERA_FIELDS: ReadonlyArray<{
    ch: KfChannel;
    label: string;
    step: number;
    range: readonly [number, number];
    hint?: string;
  }>;
  groupsById: Map<string, InspectorGroup>;
  openGroup: { gid: string; id: string } | null;
  groupPopHost: HTMLElement | null;
  groupPoint: PointAnchor;
  groupPop: BodyPopoverHandle;
  snappedAt: number | null;
  LANE_DRAG_PX: 14;
  LANE_EDGE_PX: 6;
  playBtnPlaying: boolean | null;
  pinchDist: number;
  splitBtnKey: string;
  focusedEdge: 'in' | 'out' | null;
  takePhase: TakePhase;
  takeKind: TakeKind;
  takeSession: RecordSession | null;
  takeLevelOff: (() => void) | null;
  takeMeterRefs: number;
  takeSeq: number;
  takeStartSec: number;
  takeStartedAt: number;
  takeTimer: number;
  takeCountTimer: number;
  takeWarned: boolean;
  lastMuteAt: number;
  takeReplaceId: string;
  takeMuted: Set<HTMLElement>;
  noteTimer: number;
  camView: HTMLElement | null;
  camPreviewOff: (() => void) | null;
  assetFieldCache: string;
  scriptBusy: boolean;
  subtitlesPending: Set<string>;
  keysModal: ModalHandle<void> | null;
  hovered: boolean;
  unsubRuntime: undefined | (() => void);
  unsubSelection: () => void;
  lastTimeKey: string;
  unsubTick: () => void;
  unsubShot: () => void;
  unsubPose: () => void;
  ro: ResizeObserver | null;
  // ---- operations, one namespace per module ----
  helpers: ReturnType<typeof helpersOps>;
  rows: ReturnType<typeof rowsOps>;
  menus: ReturnType<typeof menusOps>;
  keyframes: ReturnType<typeof keyframesOps>;
  camera: ReturnType<typeof cameraOps>;
  kfDock: ReturnType<typeof kfDockOps>;
  inspectorPane: ReturnType<typeof inspectorPaneOps>;
  thumbs: ReturnType<typeof thumbsOps>;
  syncing: ReturnType<typeof syncingOps>;
  gestures: ReturnType<typeof gesturesOps>;
  playback: ReturnType<typeof playbackOps>;
  clips: ReturnType<typeof clipsOps>;
  edit: ReturnType<typeof editOps>;
  recording: ReturnType<typeof recordingOps>;
  subtitles: ReturnType<typeof subtitlesOps>;
  panel: ReturnType<typeof panelOps>;
}

/** A module function minus its leading context parameter. */
export type Op<F> = F extends (tp: TpCtx, ...a: infer A) => infer R ? (...a: A) => R : never;

/** Bind a module function to one context so it can be passed around as a value. */
export function bindOp<F extends (tp: TpCtx, ...a: never[]) => unknown>(tp: TpCtx, f: F): Op<F> {
  return ((...a: never[]) => f(tp, ...a)) as Op<F>;
}
