// SPDX-License-Identifier: MPL-2.0

const COMMANDS: &[&str] = &["authenticate", "google_authorize"];

#[path = "build/swift-runtime-exports.rs"]
mod swift_runtime_exports;

fn main() {
    // Writes the per-command permissions under permissions/autogenerated, sets
    // the `mobile` and `desktop` cfg flags, and, when building for a phone,
    // copies the Tauri native API next to the plugin and compiles the Swift
    // package (iOS) or registers the Gradle module (Android).
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
    println!("cargo:rerun-if-changed=build/swift-runtime-exports.rs");
    swift_runtime_exports::repair_from_env()
        .unwrap_or_else(|error| panic!("SwiftRs runtime export repair: {error}"));
}
