// SPDX-License-Identifier: MPL-2.0
/** Tools ship data: compile the shared planner into a portable hook region. */
import { readFile, writeFile } from 'node:fs/promises';
import { build } from 'esbuild';

const result = await build({ entryPoints: ['engine/src/slide-composition.ts'], bundle: true, write: false,
  format: 'iife', globalName: 'LollySlideComposition', platform: 'neutral', target: 'es2022', minify: true, legalComments: 'none' });
const source = `// SPDX-License-Identifier: MPL-2.0\n// Generated by scripts/build-slide-composition.ts from engine/src/slide-composition.ts.\n// === lolly:shared slide-composition - canonical source; generated by scripts/build-slide-composition.ts ===\n${result.outputFiles[0]!.text.trim()}\n// === /lolly:shared slide-composition ===\n`;
const path = 'community/_shared/slide-composition.js';
if (process.argv.includes('--check')) {
  if (await readFile(path, 'utf8').catch(() => '') !== source) throw new Error('Run node scripts/build-slide-composition.ts and pnpm run sync:shared.');
} else await writeFile(path, source);
