// SPDX-License-Identifier: MPL-2.0
/**
 * Build the portable scalar maths module and embed its bytes in the engine.
 *
 *   node scripts/build-portable-math.ts           rebuild with pinned Rust, then embed
 *   node scripts/build-portable-math.ts --check   no Rust needed: the engine embed must
 *                                                  equal the committed .wasm byte for byte
 *
 * The TypeScript geometry and the portable fitting artifact both call these
 * functions, so a rebuild that changes a byte changes geometry answers and must be
 * recorded as a geometry revision.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { chmodSync, copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = fileURLToPath(new URL('../', import.meta.url));
const source = join(repo, 'packages/node-shell/wasm/portable-math');
const wasmFile = join(source, 'portable-math.wasm');
const embedFile = join(repo, 'engine/src/geom/portable-math-wasm.ts');
const option = (name: string) => process.argv.find(arg => arg.startsWith(`--${name}=`))?.slice(name.length + 3);

function embed(bytes: Buffer): string {
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  const base64 = bytes.toString('base64');
  const lines = base64.match(/.{1,100}/g) ?? [];
  return `// SPDX-License-Identifier: MPL-2.0
// GENERATED by scripts/build-portable-math.ts from packages/node-shell/wasm/portable-math/.
// Do not edit; rebuild, or run the script with --check to compare with the committed module.
/** ${bytes.length} bytes, sha256 ${sha256}. */
export const PORTABLE_MATH_SHA256 = '${sha256}';
export const PORTABLE_MATH_WASM =
${lines.map(line => `  '${line}'`).join(' +\n')};
`;
}

if (process.argv.includes('--check')) {
  const expected = embed(readFileSync(wasmFile));
  if (readFileSync(embedFile, 'utf8') !== expected) {
    console.error('engine/src/geom/portable-math-wasm.ts does not match portable-math.wasm. Run node scripts/build-portable-math.ts.');
    process.exit(1);
  }
  console.log('portable maths embed matches the committed module');
} else {
  const target = resolve(option('target-dir') ?? join(repo, 'plans/295-validation/portable-math-target'));
  mkdirSync(target, { recursive: true });
  execFileSync('cargo', ['build', '--release', '--locked', '--target', 'wasm32-unknown-unknown', '--target-dir', target], {
    cwd: source,
    stdio: 'inherit',
    env: {
      ...process.env,
      RUSTFLAGS: '-C link-arg=--initial-memory=131072 -C link-arg=--max-memory=131072 -C link-arg=-zstack-size=65536',
    },
  });
  copyFileSync(join(target, 'wasm32-unknown-unknown/release/lolly_portable_math.wasm'), wasmFile);
  chmodSync(wasmFile, 0o644);
  writeFileSync(embedFile, embed(readFileSync(wasmFile)));
  console.log(`portable maths rebuilt and embedded (${readFileSync(wasmFile).length} bytes)`);
}
