// SPDX-License-Identifier: MPL-2.0
/** Build the portable hooks and browser renderer from the same geographic model. */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { build } from 'esbuild';

const root = resolve(import.meta.dirname, '..');
const dir = resolve(root, 'community/timezone');
const check = process.argv.includes('--check');
for (const name of ['hooks', 'renderer']) {
  const result = await build({
    entryPoints: [resolve(dir, `src/${name}.ts`)],
    bundle: true,
    write: false,
    format: 'iife',
    globalName: name === 'hooks' ? 'TimezoneHooks' : 'LollyTimezone',
    platform: 'browser',
    target: 'es2022',
    minify: true,
    legalComments: 'none',
    banner: {
      js: '/*! Lolly Timezone · MPL-2.0 · Generated by scripts/build-timezone.ts. See THIRD_PARTY.md for data and library licences. */',
    },
    footer:
      name === 'hooks'
        ? {
            js: 'var onInit=TimezoneHooks.onInit,onInput=TimezoneHooks.onInput,beforeExport=TimezoneHooks.beforeExport;',
          }
        : undefined,
  });
  const path = resolve(dir, name === 'hooks' ? 'hooks.js' : 'lib/renderer.min.js'),
    text = result.outputFiles[0]!.text;
  if (check) {
    if (readFileSync(path, 'utf8') !== text)
      throw new Error(`${path} has drifted; run node scripts/build-timezone.ts`);
  } else writeFileSync(path, text);
  console.log(`${check ? 'checked' : 'built'} ${name}: ${(text.length / 1024).toFixed(0)} KB`);
}
