// SPDX-License-Identifier: MPL-2.0
/**
 * Bundles the CA (C2PA device-enrollment) serverless handler into a single
 * self-contained `api/ca/[...path].js` - the same fix as scripts/build-mcp-fn.ts.
 *
 * WHY: @vercel/node transpiles each `.ts`/`.mjs` file individually and leaves
 * import specifiers untouched. services/ca/lib/enroll.mjs imports
 * `../../../engine/src/x509.ts`; engine's x509.ts gets transpiled to x509.js, but
 * the `.ts` specifier stays → `ERR_MODULE_NOT_FOUND` at cold start, 500ing every
 * /api/ca/* route. esbuild inlines all first-party code (resolving the .ts
 * specifier); node_modules stay external for Vercel's tracer. CA is catch-all so
 * the output keeps the `[...path]` filename.
 *
 * Runs during the Vercel build (see `build:ca-fn` in package.json / vercel.json
 * buildCommand). The output is generated and committed (present at function-
 * detection time); the buildCommand regenerates it fresh each deploy. Only the
 * .map is git-ignored.
 */
import { build } from 'esbuild';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { assertNoBareWorkspaceImports, workspaceAliases } from './lib/workspace-aliases.ts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outfile = path.join(root, 'api/ca/[...path].js');

await build({
  entryPoints: [path.join(root, 'services/ca/vercel-entry.mjs')],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  packages: 'external',
  // …but the workspace packages ARE first-party source: alias each to its real
  // entry so esbuild inlines it rather than leaving a bare, dangling import. Left
  // external, a workspace subpath resolves at runtime to a TYPESCRIPT file that is
  // not in the deployed function - ERR_MODULE_NOT_FOUND on every request, the whole
  // service 500ing on module load. The aliases come from each package's own
  // exports map (scripts/lib/workspace-aliases.ts), same as build-mcp-fn.ts.
  alias: workspaceAliases(root),
  banner: { js: '// GENERATED by scripts/build-ca-fn.ts - do not edit by hand.' },
  logLevel: 'info',
});

assertNoBareWorkspaceImports(await readFile(outfile, 'utf-8'), 'api/ca/[...path].js');
console.log('✓ bundled api/ca/[...path].js');
