#!/usr/bin/env node
// SPDX-License-Identifier: MPL-2.0

/** Generate the parser table and target census in docs/parser-inventory.md from
 * security/parser-assurance.json plus the fuzz harness's real ALL_TARGETS list. */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import {
  registeredFuzzTargets,
  type ParserAssuranceRegistry,
  type ParserInventoryDetails,
} from './check-parser-assurance.ts';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const docsPath = path.join(repoRoot, 'docs', 'parser-inventory.md');
const registryPath = path.join(repoRoot, 'security', 'parser-assurance.json');
const fuzzPath = path.join(repoRoot, 'tests', 'fuzz', 'targets.ts');
const GENERATED_NOTICE = '<!-- The parser table and fuzz-target census are generated by scripts/build-parser-inventory.ts. Edit security/parser-assurance.json. -->';

function tableCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ').trim();
}

export function renderParserTable(registry: ParserAssuranceRegistry): string {
  const rows = Object.entries(registry.parsers).map(([id, entry]) => {
    const details = entry.details as ParserInventoryDetails | undefined;
    if (!details) throw new Error(`${id}: registry entry has no inventory details`);
    const cells = [
      `\`${id}\``,
      details.inputSource,
      details.bounds,
      details.directTests,
      details.fuzzCoverage,
      details.notes,
    ].map(tableCell);
    return `| ${cells.join(' | ')} |`;
  });
  return [
    '## The parsers',
    '',
    GENERATED_NOTICE,
    '',
    '| Module | Input source | Bounds enforced | Direct test file | Fuzz target | Notes |',
    '|---|---|---|---|---|---|',
    ...rows,
  ].join('\n');
}

export function renderTargetCensus(targets: string[]): string {
  const names = targets.map((target) => `\`${target}\``);
  const listed = names.length > 1
    ? `${names.slice(0, -1).join(', ')} and ${names.at(-1)}`
    : (names[0] ?? 'none');
  return `Fuzz coverage is the registered target list in \`tests/fuzz/targets.ts\` (\`ALL_TARGETS\`, at the end of the file). There are ${targets.length}: ${listed}. \`tests/fuzz-regression.test.ts\` replays the eight saved regression inputs in \`tests/fuzz/regressions/\` and runs a few hundred seeded mutations per target inside the normal \`npm test\` glob; \`node tests/fuzz/run.ts\` is the standalone soak.`;
}

export function generateParserInventory(
  current: string,
  registry: ParserAssuranceRegistry,
  targets: string[],
): string {
  const censusStart = current.indexOf('Fuzz coverage is the registered target list');
  const censusEnd = current.indexOf('\n\n', censusStart);
  if (censusStart < 0 || censusEnd < 0) throw new Error('parser inventory has no replaceable fuzz census');
  let generated = `${current.slice(0, censusStart)}${renderTargetCensus(targets)}${current.slice(censusEnd)}`;
  const parserStart = generated.indexOf('## The parsers\n');
  const parserEnd = generated.indexOf('\n## ', parserStart + 1);
  if (parserStart < 0 || parserEnd < 0) throw new Error('parser inventory has no replaceable parser table');
  generated = `${generated.slice(0, parserStart)}${renderParserTable(registry)}\n${generated.slice(parserEnd + 1)}`;
  return generated.endsWith('\n') ? generated : `${generated}\n`;
}

function main(): void {
  const current = readFileSync(docsPath, 'utf8');
  const registry = JSON.parse(readFileSync(registryPath, 'utf8')) as ParserAssuranceRegistry;
  const targets = [...registeredFuzzTargets(readFileSync(fuzzPath, 'utf8'))];
  const generated = generateParserInventory(current, registry, targets);
  if (process.argv.includes('--check')) {
    if (current !== generated) {
      throw new Error('docs/parser-inventory.md is stale; run npm run build:parser-inventory');
    }
    console.log(`Parser inventory is current (${Object.keys(registry.parsers).length} rows, ${targets.length} fuzz targets).`);
    return;
  }
  writeFileSync(docsPath, generated);
  console.log(`Wrote docs/parser-inventory.md (${Object.keys(registry.parsers).length} rows, ${targets.length} fuzz targets).`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
