// SPDX-License-Identifier: MPL-2.0
/**
 * Bundles the CA (C2PA device-enrollment) serverless handler into a single
 * self-contained `api/ca/[...path].js` - the same fix as scripts/build-mcp-fn.ts.
 *
 * WHY: @vercel/node transpiles each `.ts`/`.mjs` file individually and leaves
 * import specifiers untouched. services/ca/lib/enroll.mjs imports
 * `../../../engine/src/x509.ts`; engine's x509.ts gets transpiled to x509.js, but
 * the `.ts` specifier stays → `ERR_MODULE_NOT_FOUND` at cold start, 500ing every
 * /api/ca/* route. esbuild inlines all first-party code (resolving the .ts
 * specifier); node_modules stay external for Vercel's tracer. CA is catch-all so
 * the output keeps the `[...path]` filename.
 *
 * Runs during the Vercel build (see `build:ca-fn` in package.json / vercel.json
 * buildCommand). The output is generated and committed (present at function-
 * detection time); the buildCommand regenerates it fresh each deploy. Only the
 * .map is git-ignored.
 */
import { build } from 'esbuild';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

await build({
  entryPoints: [path.join(root, 'services/ca/vercel-entry.mjs')],
  outfile: path.join(root, 'api/ca/[...path].js'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  packages: 'external',
  // …but the workspace packages ARE first-party source: alias each to its real
  // entry so esbuild inlines it rather than leaving a bare, dangling import.
  // `@lolly-tools/core` matters as much as the engine and is easy to miss: the
  // engine VALUE-imports it (preflight.ts, loader.ts, rate-card.ts), not just for
  // types, and its package `exports` map points at `./src/index.ts`. Left external
  // that resolves, at runtime, to a TYPESCRIPT file inside the deployed function -
  // ERR_MODULE_NOT_FOUND on every request, the whole service 500ing on module load
  // rather than failing the build. That is exactly how it broke on 2026-08-01, so
  // every code subpath in the exports map is aliased here, not just the barrel.
  alias: {
    '@lolly/engine': path.join(root, 'engine/src/index.ts'),
    '@lolly-tools/core': path.join(root, 'packages/core/src/index.ts'),
    '@lolly-tools/core/host-v1': path.join(root, 'packages/core/src/host-v1.ts'),
    '@lolly-tools/core/contract': path.join(root, 'packages/core/src/contract.ts'),
    '@lolly-tools/core/preflight': path.join(root, 'packages/core/src/preflight.ts'),
  },
  banner: { js: '// GENERATED by scripts/build-ca-fn.ts — do not edit by hand.' },
  logLevel: 'info',
});

console.log('✓ bundled api/ca/[...path].js');
