// SPDX-License-Identifier: MPL-2.0
/**
 * Bundles the MCP serverless handler into a single self-contained
 * `api/mcp/[...path].js` - a catch-all so ONE function serves the JSON-RPC
 * endpoint (`/api/mcp`), the OAuth flow (`/api/mcp/{register,authorize,token}`),
 * and the `/.well-known/oauth-*` discovery docs (routed in via vercel.json).
 *
 * WHY THIS EXISTS
 * Vercel's @vercel/node builder transpiles each `.ts` file to `.js` individually
 * but leaves import *specifiers* untouched. The repo deliberately writes explicit
 * `.ts` extensions (so Node can run the sources directly - see CLAUDE.md), so the
 * traced function ends up full of `import ... from './x.ts'` pointing at files
 * that are now `x.js` → `ERR_MODULE_NOT_FOUND` at runtime.
 *
 * esbuild resolves and inlines ALL first-party code (api entry + services/mcp +
 * engine, following the `.ts` specifiers correctly) into one module. node_modules
 * stay EXTERNAL (`packages: 'external'`) so Vercel's file-tracer includes them
 * normally - this keeps native/wasm deps (@resvg/resvg-js, harfbuzz, jsdom) out
 * of the bundle where esbuild would choke on them.
 *
 * Runs during the Vercel build (see `build:mcp-fn` in package.json / vercel.json
 * buildCommand). The output `api/mcp/[...path].js` (a catch-all route) is
 * generated and committed (so it's present at Vercel function-detection time);
 * the buildCommand regenerates it fresh on every deploy. Only the sibling
 * `api/mcp/[...path].js.map` is git-ignored.
 */
import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Catch-all route file: api/mcp/[...path].js (the dir must exist for esbuild).
const outfile = path.join(root, 'api/mcp/[...path].js');
await mkdir(path.dirname(outfile), { recursive: true });

await build({
  entryPoints: [path.join(root, 'services/mcp/src/vercel-entry.ts')],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  // node_modules stay external - Vercel's tracer bundles them into the function.
  packages: 'external',
  // …but the workspace packages ARE first-party source: alias each to its real
  // entry so esbuild inlines it rather than leaving a bare, dangling import.
  // `@lolly-tools/core` matters as much as the engine and is easy to miss: the
  // engine VALUE-imports it (preflight.ts, loader.ts, rate-card.ts), not just for
  // types, and its package `exports` map points at `./src/index.ts`. Left external
  // that resolves, at runtime, to a TYPESCRIPT file inside the deployed function -
  // ERR_MODULE_NOT_FOUND on every request, the whole service 500ing on module load
  // rather than failing the build. That is exactly how it broke on 2026-08-01, so
  // every code subpath in the exports map is aliased here, not just the barrel.
  alias: {
    '@lolly/engine': path.join(root, 'engine/src/index.ts'),
    '@lolly-tools/core': path.join(root, 'packages/core/src/index.ts'),
    '@lolly-tools/core/host-v1': path.join(root, 'packages/core/src/host-v1.ts'),
    '@lolly-tools/core/contract': path.join(root, 'packages/core/src/contract.ts'),
    '@lolly-tools/core/preflight': path.join(root, 'packages/core/src/preflight.ts'),
  },
  banner: { js: '// GENERATED by scripts/build-mcp-fn.ts — do not edit by hand.' },
  logLevel: 'info',
});

console.log('✓ bundled api/mcp/[...path].js');
