#!/usr/bin/env node
// SPDX-License-Identifier: MPL-2.0
/**
 * Build packages/rondo's generated files from the vendored upstream source.
 *
 *   node scripts/build-rondo.ts            write generated/stage.js, generated/render.mjs, src/node-types.generated.ts
 *                                          and engine/src/rondo-share-dict.ts
 *   node scripts/build-rondo.ts --check    rebuild in memory, exit 1 if any committed file differs
 *   node scripts/build-rondo.ts --golden   also re-record test/fixtures/{examples,golden}.json from upstream's
 *                                          ALL-NATIVE render (no vm), the reference the vm path must match
 *
 * Two bundles, two trust levels (packages/rondo/src/vm.ts explains the split):
 *   stage.js    IIFE evaluated only inside QuickJS. Carries upstream's evaluation core.
 *   render.mjs  ESM for the trusted realm. Upstream's DSP and graph checks only; the
 *               build refuses it if the evaluation core leaked in.
 */
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import * as esbuild from 'esbuild';
import ts from 'typescript';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = path.join(repo, 'packages/rondo');
const upstream = path.join(pkg, 'upstream');
const args = new Set(process.argv.slice(2));
const CHECK = args.has('--check');
const GOLDEN = args.has('--golden');

const BANNER = '/*! rondocode (c) 2026 Vijay Pemmaraju, MIT License. Bundled by Lolly from packages/rondo/upstream; see packages/rondo/UPSTREAM.md. */';

const alias = {
  '@rondocode/engine': path.join(upstream, 'packages/engine/src/index.ts'),
  '@rondocode/pattern': path.join(upstream, 'packages/pattern/src/index.ts'),
  '@rondocode/rondo': path.join(upstream, 'packages/rondo/src/index.ts'),
};

/** Upstream's modules are side-effect free; saying so lets an unused import drop out of a bundle. */
const pureUpstream: esbuild.Plugin = {
  name: 'pure-upstream',
  setup(build) {
    build.onResolve({ filter: /.*/ }, async (a) => {
      if (a.pluginData === 'pure-upstream' || a.kind === 'entry-point') return undefined;
      const r = await build.resolve(a.path, { kind: a.kind, resolveDir: a.resolveDir, importer: a.importer, pluginData: 'pure-upstream' });
      if (r.errors.length) return undefined;
      if (r.path.startsWith(upstream + path.sep)) return { path: r.path, sideEffects: false };
      return undefined;
    });
  },
};

async function bundle(opts: esbuild.BuildOptions): Promise<string> {
  const r = await esbuild.build({
    bundle: true,
    write: false,
    alias,
    absWorkingDir: repo,
    logLevel: 'warning',
    legalComments: 'none',
    banner: { js: BANNER },
    minify: true,
    charset: 'utf8',
    ...opts,
  });
  const out = r.outputFiles?.[0];
  if (!out) throw new Error('esbuild produced no output');
  return out.text;
}

function nodeTypesSource(): string {
  const graph = readFileSync(path.join(upstream, 'packages/engine/src/graph.ts'), 'utf8');
  const m = /export type NodeType =([\s\S]*?)\n\n/.exec(graph);
  if (!m?.[1]) throw new Error('could not find the NodeType union in upstream graph.ts');
  const types = [...m[1].replace(/\/\/[^\n]*/g, '').matchAll(/'([a-z0-9]+)'/g)].map((x) => x[1] as string);
  if (types.length < 20) throw new Error(`NodeType union looks wrong (${types.length} names)`);
  const lines = types.map((t) => `  '${t}',`).join('\n');
  return `// SPDX-License-Identifier: MPL-2.0
// GENERATED by scripts/build-rondo.ts from upstream packages/engine/src/graph.ts. Do not edit.
// The closed set of DSP node types the staged-data validator accepts.

export const NODE_TYPES: readonly string[] = Object.freeze([
${lines}
]);
`;
}

/**
 * Upstream's share links are raw DEFLATE primed with a preset dictionary
 * (app/src/session/share.ts). The engine decodes those links without importing
 * upstream, so the dictionary is lifted out of the source with the TypeScript
 * parser (a concatenation of string literals) and written into the engine.
 */
function shareDictionarySource(): string {
  const file = path.join(upstream, 'packages/app/src/session/share.ts');
  const sf = ts.createSourceFile(file, readFileSync(file, 'utf8'), ts.ScriptTarget.Latest, true);
  let text: string | null = null;
  const literal = (e: ts.Expression): string => {
    if (ts.isStringLiteral(e) || ts.isNoSubstitutionTemplateLiteral(e)) return e.text;
    if (ts.isParenthesizedExpression(e)) return literal(e.expression);
    if (ts.isBinaryExpression(e) && e.operatorToken.kind === ts.SyntaxKind.PlusToken) return literal(e.left) + literal(e.right);
    throw new Error('DICT_TEXT in upstream share.ts is no longer a concatenation of string literals');
  };
  sf.forEachChild(function visit(node) {
    if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name) && node.name.text === 'DICT_TEXT' && node.initializer) {
      text = literal(node.initializer);
    }
    node.forEachChild(visit);
  });
  if (!text) throw new Error('could not find DICT_TEXT in upstream share.ts');
  return `// SPDX-License-Identifier: MIT
// GENERATED by scripts/build-rondo.ts from rondocode's app/src/session/share.ts
// (MIT, Vijay Pemmaraju; packages/rondo/upstream). Do not edit.
//
// The preset DEFLATE dictionary rondocode share links are compressed with. A
// link decodes only with the dictionary it was made with, so this file follows
// the pinned upstream commit.

export const RONDO_SHARE_DICTIONARY_TEXT: string = ${JSON.stringify(text)};
`;
}

async function build(): Promise<Record<string, string>> {
  const stage = await bundle({
    entryPoints: [path.join(pkg, 'src/stage-entry.ts')],
    format: 'iife',
    globalName: '__rondoStage',
    platform: 'neutral',
    mainFields: ['module', 'main'],
    target: 'es2020',
  });
  const render = await bundle({
    entryPoints: [path.join(pkg, 'src/render-entry.ts')],
    format: 'esm',
    platform: 'neutral',
    mainFields: ['module', 'main'],
    target: 'es2022',
    // Only here: the stage bundle keeps upstream's bare side-effect imports
    // (pattern/src/controls.ts installs the combinators that way). The render
    // bundle never calls pattern code, so dropping those imports is the point.
    plugins: [pureUpstream],
    logOverride: { 'ignored-bare-import': 'silent' },
  });
  for (const banned of ['new Function', 'acorn']) {
    if (render.includes(banned)) throw new Error(`generated/render.mjs contains "${banned}": the evaluation core leaked into the trusted bundle`);
  }
  return {
    'packages/rondo/generated/stage.js': stage,
    'packages/rondo/generated/render.mjs': render,
    'packages/rondo/src/node-types.generated.ts': nodeTypesSource(),
    'engine/src/rondo-share-dict.ts': shareDictionarySource(),
  };
}

const pcmHash = (left: Float32Array, right: Float32Array): string =>
  createHash('sha256')
    .update(new Uint8Array(left.buffer, left.byteOffset, left.byteLength))
    .update(new Uint8Array(right.buffer, right.byteOffset, right.byteLength))
    .digest('hex');

/** Re-record the reference: upstream's own all-native path, run exactly as upstream's render-example script does. */
async function golden(): Promise<void> {
  const dir = mkdtempSync(path.join(tmpdir(), 'rondo-golden-'));
  try {
    const entry = path.join(dir, 'golden-entry.ts');
    writeFileSync(entry, `
import { stageCode, runPatterns, renderMix, mixOptsFor } from ${JSON.stringify(path.join(upstream, 'packages/server/src/render-runner'))}
import { compile } from ${JSON.stringify(path.join(upstream, 'packages/rondo/src/index'))}
import { EXAMPLES } from ${JSON.stringify(path.join(upstream, 'packages/app/src/examples/index'))}
export { EXAMPLES }
export function nativeRender(source: string, lang: string, cycles: number) {
  let js = source
  if (lang === 'rondo') { const c = compile(source); if (!c.ok || c.code == null) throw new Error('rondo compile failed'); js = c.code }
  const s = stageCode(js)
  if (!s.ok) throw new Error('stage failed')
  const cps = s.cps ?? 0.5
  const events = runPatterns(s.patterns, { cycles, cps })
  return renderMix(s.synths, events, cycles / cps, mixOptsFor(s, { sampleRate: 48000 }))
}
`);
    const out = path.join(dir, 'golden.mjs');
    await esbuild.build({ entryPoints: [entry], bundle: true, format: 'esm', platform: 'node', target: 'node22', alias, outfile: out, logLevel: 'warning', absWorkingDir: repo });
    const mod = (await import(pathToFileURL(out).href)) as {
      EXAMPLES: { name: string; code: string; rondo?: string }[];
      nativeRender: (s: string, l: string, c: number) => { left: Float32Array; right: Float32Array };
    };
    const CYCLES = 8;
    const examples = mod.EXAMPLES.map((e) => ({ name: e.name, js: e.code, ...(e.rondo ? { rondo: e.rondo } : {}) }));
    const hashes: Record<string, { js?: string; rondo?: string }> = {};
    for (const e of examples) {
      const h: { js?: string; rondo?: string } = {};
      const js = mod.nativeRender(e.js, 'js', CYCLES);
      h.js = pcmHash(js.left, js.right);
      if (e.rondo) {
        const r = mod.nativeRender(e.rondo, 'rondo', CYCLES);
        h.rondo = pcmHash(r.left, r.right);
      }
      hashes[e.name] = h;
    }
    const fixtures = path.join(pkg, 'test/fixtures');
    writeFileSync(path.join(fixtures, 'examples.json'), `${JSON.stringify({ source: 'upstream packages/app/src/examples/index.ts (MIT, Vijay Pemmaraju)', examples }, null, 1)}\n`);
    writeFileSync(path.join(fixtures, 'golden.json'), `${JSON.stringify({ cycles: CYCLES, sampleRate: 48000, hash: 'sha256 of left then right Float32 PCM', reference: 'upstream all-native render', pcm: hashes }, null, 1)}\n`);
    console.log(`golden: ${examples.length} examples recorded`);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

const files = await build();
let drift = 0;
for (const [rel, text] of Object.entries(files)) {
  const abs = path.join(repo, rel);
  let current = '';
  try {
    current = readFileSync(abs, 'utf8');
  } catch {
    // missing counts as drift
  }
  if (current === text) continue;
  if (CHECK) {
    drift++;
    console.error(`drift: ${rel} differs from a fresh build`);
  } else {
    writeFileSync(abs, text);
    console.log(`wrote ${rel} (${(text.length / 1024).toFixed(0)} KB)`);
  }
}
if (CHECK && drift) {
  console.error('Run `node scripts/build-rondo.ts` and commit the result.');
  process.exit(1);
}
if (GOLDEN) await golden();
