// SPDX-License-Identifier: MPL-2.0
/**
 * Bundles the Penpot RPC proxy handler into a single self-contained
 * `api/penpot/[...path].js` - the same fix as scripts/build-mcp-fn.ts.
 *
 * WHY: @vercel/node transpiles each `.ts` file individually and leaves import
 * specifiers untouched, so the repo's explicit `.ts` extensions would dangle at
 * runtime (`ERR_MODULE_NOT_FOUND`). esbuild inlines the first-party source;
 * node_modules stay external for Vercel's tracer. The proxy is a catch-all so
 * the output keeps the `[...path]` filename. Unlike mcp/ca the entry has no
 * engine/workspace imports, so no aliases are needed.
 *
 * Runs during the Vercel build (see `build:penpot-fn` in package.json /
 * vercel.json buildCommand). The output is generated and committed (present at
 * function-detection time); the buildCommand regenerates it fresh each deploy.
 * Only the .map is git-ignored.
 */
import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Catch-all route file: api/penpot/[...path].js (the dir must exist for esbuild).
const outfile = path.join(root, 'api/penpot/[...path].js');
await mkdir(path.dirname(outfile), { recursive: true });

await build({
  entryPoints: [path.join(root, 'services/penpot/vercel-entry.ts')],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  // node_modules stay external - Vercel's tracer bundles them into the function.
  packages: 'external',
  banner: { js: '// GENERATED by scripts/build-penpot-fn.ts - do not edit by hand.' },
  logLevel: 'info',
});

console.log('✓ bundled api/penpot/[...path].js');
