#!/usr/bin/env node
// SPDX-License-Identifier: MPL-2.0
/**
 * Cargo license-map freshness gate.
 *
 * Run as: npm run check:cargo-licenses  (CI's audit job runs this)
 *
 * The problem this closes: `cargo-licenses.json` is generated by
 * scripts/build-cargo-licenses.ts, which shells out to `cargo metadata`. CI has
 * no Rust toolchain, so - unlike the SBOM and the third-party notices - the map
 * CANNOT be regenerated-and-diffed there. That left the one artifact a `cargo
 * update` invalidates as the only one with no drift guard: crate licenses could
 * silently go stale while the audit job still went green, which is worse than an
 * ungenerated file because a stale map LOOKS authoritative.
 *
 * The fix is to check coverage rather than regenerate: every `[[package]]` in
 * every shipped Cargo.lock must have an entry in the committed map. That needs
 * only the lockfiles and the map - no cargo, no network - so it runs anywhere.
 *
 * What it catches:
 *   - `cargo update` / a new crate: new name@version pairs are absent from the
 *     map → FAIL, with the exact crates to re-run the generator for.
 *   - A crate VERSION bump on a license-file crate (the hand-reviewed
 *     LICENSE_FILE_OVERRIDES entries are version-pinned on purpose): the new
 *     version is uncovered → FAIL, forcing a fresh read of the license file
 *     instead of silently carrying the old verdict forward.
 *   - A crate dropped from the graph: reported as a stale extra (warning only - 
 *     an unused entry misleads nobody, and pruning it needs the generator).
 *
 * What it deliberately does NOT do: re-derive licenses. It only asserts the map
 * covers the graph. Whether an entry is CORRECT is the generator's job (it reads
 * cargo metadata) and, for license-file crates, a human's.
 */

import { readFileSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// The Cargo.lock files whose crates the SBOM describes - same set as
// scripts/build-sbom.ts and scripts/build-cargo-licenses.ts.
const LOCKFILES = [
  'shells/tauri-desktop/src-tauri/Cargo.lock',
  'shells/tauri-mobile/src-tauri/Cargo.lock',
];

// Parse a Cargo.lock for its [[package]] name/version pairs. Cargo.lock is TOML,
// but the [[package]] blocks are a flat, quoted-string subset - the same shape
// scripts/build-sbom.ts reads - so a line scan avoids a TOML dependency.
function crateKeys(rel: string): string[] {
  const abs = join(ROOT, rel);
  if (!existsSync(abs)) return [];
  const keys: string[] = [];
  let name: string | null = null;
  let version: string | null = null;
  const flush = () => {
    if (name && version) keys.push(`${name}@${version}`);
    name = null;
    version = null;
  };
  for (const line of readFileSync(abs, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (trimmed === '[[package]]') {
      flush();
      continue;
    }
    const m = /^(name|version)\s*=\s*"([^"]*)"$/.exec(trimmed);
    if (!m) continue;
    if (m[1] === 'name') name = m[2]!;
    else version = m[2]!;
  }
  flush();
  return keys;
}

const mapPath = join(ROOT, 'cargo-licenses.json');
if (!existsSync(mapPath)) {
  console.error('✗ cargo-licenses.json is missing — run: npm run build:cargo-licenses');
  process.exit(1);
}
const doc = JSON.parse(readFileSync(mapPath, 'utf8'));
const licenses: Record<string, string> = doc?.licenses ?? {};

// Only check lockfiles that are actually present. The Tauri shells are
// submodules, so a shallow clone legitimately has neither; with no lockfile
// there is no graph to be stale against and the gate is a no-op by design.
const present = LOCKFILES.filter((rel) => existsSync(join(ROOT, rel)));
if (!present.length) {
  console.log('• No Tauri Cargo.lock present (submodules not checked out) — nothing to verify');
  process.exit(0);
}

const graph = new Set<string>();
for (const rel of present) for (const key of crateKeys(rel)) graph.add(key);

const missing = [...graph].filter((k) => !licenses[k]).sort();
const extra = Object.keys(licenses).filter((k) => !graph.has(k)).sort();

for (const k of extra) console.warn(`⚠ stale entry (no longer in any Cargo.lock): ${k}`);

if (missing.length) {
  console.error(
    `✗ ${missing.length} crate(s) in Cargo.lock have no license in cargo-licenses.json:`,
  );
  for (const k of missing) console.error(`    ${k}`);
  console.error('');
  console.error('  The crate graph moved without the license map being regenerated.');
  console.error('  Run:  npm run build:cargo-licenses && npm run build:sbom');
  console.error('  then commit both files. A crate declaring a `license-file` rather');
  console.error('  than an SPDX expression needs its license read by hand and pinned');
  console.error('  in LICENSE_FILE_OVERRIDES (scripts/build-cargo-licenses.ts).');
  process.exit(1);
}

console.log(
  `✓ cargo-licenses.json covers all ${graph.size} crates across ${present.length} lockfile(s)` +
    (extra.length ? ` (${extra.length} stale entr${extra.length === 1 ? 'y' : 'ies'})` : ''),
);
