#!/usr/bin/env node
// SPDX-License-Identifier: MPL-2.0
/**
 * onnxruntime-web runtime copier for @huggingface/transformers - the sibling of
 * scripts/copy-ort.ts, for a DIFFERENT onnxruntime-web build.
 *
 * Run as: npm run build:ort  (part of build:web; also runs standalone).
 *
 * transformers.js pins its own onnxruntime-web (a dev build, e.g.
 * 1.22.0-dev.*, npm keeps it un-hoisted under
 * node_modules/@huggingface/transformers/node_modules/) and its wasm binding is
 * NOT interchangeable with the 1.27 runtime already served at /ort/ - loading
 * mismatched .mjs/.wasm pairs fails at session init. So the speech worker
 * (shells/web/src/lib/speech-kokoro-worker.ts) points
 * env.backends.onnx.wasm.wasmPaths at its own same-origin dir, and this script
 * fills it. Same rationale as copy-ort.ts otherwise: exact copies of the
 * installed dependency's dist files, gitignored, regenerated at build time,
 * never a CDN.
 *
 * The served path is VERSIONED: /ort-hf/<onnxruntime-web version>/. The SW
 * caches /ort-hf/ cache-first in a never-evicted bucket (lolly-ort), and the
 * wasm filenames themselves are stable - so a flat /ort-hf/ would pin the
 * first-ever-fetched wasm on every installed client forever, across
 * transformers.js upgrades that ship an incompatible new runtime under the
 * same URLs. A version segment makes an upgrade a cache MISS instead.
 *
 * The version the worker must request is emitted as a small generated,
 * COMMITTED constants file: shells/web/src/lib/ort-hf-base.ts (ORT_HF_BASE) - 
 * committed so tsc works on a fresh clone, rewritten here only when the
 * content actually changes so a no-op run causes no churn.
 */

import { readdirSync, copyFileSync, mkdirSync, existsSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DEST_ROOT = join(ROOT, 'shells/web/public/ort-hf');
const BASE_TS = join(ROOT, 'shells/web/src/lib/ort-hf-base.ts');

// transformers.js's pinned onnxruntime-web is a dev version, so npm cannot hoist
// it over the root's stable 1.27 - it stays nested. Probe the nested locations
// first, then the (unlikely) hoisted fallbacks, and REFUSE the root's own
// onnxruntime-web if transformers is installed but its nested copy is missing:
// serving the wrong runtime is worse than failing loudly.
const CANDIDATES = [
  join(ROOT, 'node_modules/@huggingface/transformers/node_modules/onnxruntime-web/dist'),
  join(ROOT, 'shells/web/node_modules/@huggingface/transformers/node_modules/onnxruntime-web/dist'),
];
const DIST = CANDIDATES.find(existsSync);

if (!DIST) {
  console.error(
    `[copy-transformers-ort] transformers.js's pinned onnxruntime-web dist not found in any of:\n  ${CANDIDATES.join('\n  ')}\n  is @huggingface/transformers installed?`,
  );
  process.exit(1);
}

// The staged package's own version names the served subdir.
const pkg = JSON.parse(readFileSync(join(DIST, '..', 'package.json'), 'utf8')) as { version?: string };
const version = pkg.version;
if (!version) {
  console.error(`[copy-transformers-ort] no version in ${join(DIST, '..', 'package.json')}`);
  process.exit(1);
}
const DEST = join(DEST_ROOT, version);

// Drop anything under public/ort-hf/ that is NOT this version's subdir - old
// version dirs and the pre-versioning flat files would otherwise ship in every
// deploy (and re-seed exactly the stale-wasm cache this layout exists to end).
if (existsSync(DEST_ROOT)) {
  for (const entry of readdirSync(DEST_ROOT)) {
    if (entry !== version) rmSync(join(DEST_ROOT, entry), { recursive: true, force: true });
  }
}
mkdirSync(DEST, { recursive: true });

let n = 0;
for (const f of readdirSync(DIST)) {
  // Only the wasm binding the speech worker actually loads (plain + jsep) - the
  // ort.*.js/mjs bundles are the full library, which transformers.js bundles
  // itself; copying them would triple the directory for files never requested.
  if ((f.endsWith('.wasm') || f.endsWith('.mjs')) && f.startsWith('ort-wasm')) {
    copyFileSync(join(DIST, f), join(DEST, f));
    n++;
  }
}

// Emit the ORT_HF_BASE constant the speech worker imports. Deterministic: same
// version → byte-identical content → no write, no churn.
const baseTs = `// GENERATED by scripts/copy-transformers-ort.ts - do not hand-edit.
// SPDX-License-Identifier: MPL-2.0
// The same-origin base path of transformers.js's pinned onnxruntime-web wasm
// runtime (env.backends.onnx.wasm.wasmPaths in lib/speech-kokoro-worker.ts).
// Versioned so the SW's never-evicted cache-first /ort-hf/ bucket misses (and
// refetches) when a transformers.js upgrade ships a new runtime. Committed so
// tsc works on a fresh clone; regenerated by npm run build:ort.
export const ORT_HF_BASE = '/ort-hf/${version}/';
`;
const existing = existsSync(BASE_TS) ? readFileSync(BASE_TS, 'utf8') : null;
if (existing !== baseTs) {
  writeFileSync(BASE_TS, baseTs);
  console.log(`[copy-transformers-ort] wrote ${BASE_TS.replace(`${ROOT}/`, '')} (ORT_HF_BASE = '/ort-hf/${version}/')`);
}

console.log(`[copy-transformers-ort] copied ${n} pinned onnxruntime-web runtime files → ${DEST.replace(`${ROOT}/`, '')}`);
