// SPDX-License-Identifier: MPL-2.0
/**
 * Generate shells/web/src/lib/lolly-mark.ts from the source-of-truth brand logo
 * at the repo root (icon.svg), so the app's inline Lolly mark is always THE
 * current logo rather than a hand-copied stale one.
 *
 * The raw icon.svg ships a C2PA manifest and paints its coloured spiral as a flat
 * `#008657` with mix-blend-mode:multiply over grey candy gradients, with its three
 * nested layers already grouped as .lolly-outer / .lolly-mid / .lolly-inner. This
 * script strips the manifest and rewires it for UI use, exactly the treatment the
 * export shutter's mark gets (lib/shutter-mark.ts):
 *   - drop <metadata> (the C2PA blob) and the c2pa namespace + wrapper class;
 *   - the spiral fill `#008657` → `var(--lolly-swirl, #008657)` so a surface can
 *     brand-tint it (falls back to the logo green);
 *   - the three layers → .lolly-mark__spin-{1,2,3} so a surface can spin them
 *     (transform-box: fill-box) without colliding with anything.
 *
 * Run:  node scripts/gen-lolly-mark.ts      (re-run whenever icon.svg changes)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const SRC = `${ROOT}icon.svg`;
const OUT = `${ROOT}shells/web/src/lib/lolly-mark.ts`;

let svg = readFileSync(SRC, 'utf-8');

// 1. Drop the C2PA manifest block AND the inline <style> - icon.svg animates its
//    own layers always-on (animation: … infinite), but the app drives a hover-only
//    spin from its own stylesheet (styles/parts/ask.css). Strip both.
svg = svg.replace(/<metadata>[\s\S]*?<\/metadata>/g, '');
svg = svg.replace(/<style>[\s\S]*?<\/style>/g, '');
// 2. Clean the root <svg>: no c2pa namespace, no wrapper class (viewBox + xmlns stay).
svg = svg.replace(/\s+xmlns:c2pa="[^"]*"/g, '').replace(/\s+class="lolly-icon"/g, '');
// 3. Brand-tint the spiral (three layers share the one flat green).
svg = svg.replace(/fill="#008657"/g, 'fill="var(--lolly-swirl, #008657)"');
// 4. Rename the spin layers to neutral, collision-free names.
svg = svg
  .replace(/class="lolly-outer"/g, 'class="lolly-mark__spin-1"')
  .replace(/class="lolly-mid"/g, 'class="lolly-mark__spin-2"')
  .replace(/class="lolly-inner"/g, 'class="lolly-mark__spin-3"');
// Tidy: collapse the inter-tag whitespace the defs block carries, trim.
svg = svg.replace(/>\s+</g, '><').trim();

if (svg.includes('c2pa') || svg.includes('#008657"') || /lolly-(outer|mid|inner)/.test(svg)) {
  throw new Error('gen-lolly-mark: a transform did not apply - check icon.svg structure');
}
if (svg.includes('`') || svg.includes('${')) {
  throw new Error('gen-lolly-mark: icon.svg contains a backtick or ${ - would break the template literal');
}

const out = `// SPDX-License-Identifier: MPL-2.0
// GENERATED by scripts/gen-lolly-mark.ts from the root icon.svg - do not edit by hand.
/**
 * The Lolly swirl mark for inline UI use - THE current brand logo (root icon.svg),
 * cleaned for the app: the C2PA manifest is stripped, its coloured spiral inherits
 * \`--lolly-swirl\` (falls back to the logo green), and its three layers are named
 * \`lolly-mark__spin-{1,2,3}\` so a surface can spin them (transform-box: fill-box)
 * about their own centres. Set \`--lolly-swirl\` on any ancestor to brand-tint it.
 * Re-run scripts/gen-lolly-mark.ts whenever icon.svg changes.
 */
export const LOLLY_MARK_SVG = ${'`'}${svg}${'`'};
`;

writeFileSync(OUT, out, 'utf-8');
console.log(`gen-lolly-mark: wrote ${OUT} (${svg.length} bytes of SVG)`);
