// SPDX-License-Identifier: MPL-2.0
/** Generate the inline UI mark from the authored primary/reverse artwork.
 * Keep gradients, highlights and blend modes; strip editor metadata and animation.
 * Run: node scripts/gen-lolly-mark.ts [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const OUT = `${ROOT}shells/web/src/lib/lolly-mark.ts`;
const NS = 'http://www.w3.org/2000/svg';
const SPIN: Record<string, string> = {
  'lolly-outer': 'lolly-mark__spin-1',
  'lolly-mid': 'lolly-mark__spin-2',
  'lolly-inner': 'lolly-mark__spin-3',
};

function variant(name: 'primary' | 'reverse'): string {
  const source = `${ROOT}icon-${name}.svg`;
  const root = new JSDOM(readFileSync(source, 'utf8'), { contentType: 'image/svg+xml' }).window.document.documentElement;
  if (root.getAttribute('viewBox') !== '0 0 285.75 285.75') throw new Error(`${source}: unexpected viewBox`);
  // Parse XML instead of matching <style> pairs: a self-closing style previously
  // swallowed the following artwork when the generated string was parsed as HTML.
  for (const el of [...root.querySelectorAll('*')]) {
    if (el.namespaceURI !== NS || ['metadata', 'style'].includes(el.localName)) el.remove();
  }
  const ids = new Map([...root.querySelectorAll('[id]')].map(el => [el.id, `lolly-${name}-${el.id}`]));
  for (const el of root.querySelectorAll('*')) {
    for (const attr of [...el.attributes]) {
      if (attr.namespaceURI || attr.name === 'version') { el.removeAttributeNode(attr); continue; }
      let value = attr.value;
      if (attr.name === 'id') value = ids.get(value)!;
      if (attr.name === 'href' && value.startsWith('#')) value = `#${ids.get(value.slice(1)) ?? value.slice(1)}`;
      if (attr.name === 'class') value = SPIN[value] ?? value;
      if (attr.name === 'fill' && value === '#008657') value = 'var(--lolly-swirl, #008657)';
      value = value.replace(/url\(#([^)]+)\)/g, (_, id: string) => `url(#${ids.get(id) ?? id})`);
      el.setAttribute(attr.name, value);
    }
  }
  const markup = [...root.children].map(el => el.outerHTML).join('').replace(/>\s+</g, '><');
  if (root.querySelectorAll('[class^="lolly-mark__spin-"]').length !== 3) throw new Error(`${source}: missing spin layers`);
  return `<g class="lolly-mark__${name}">${markup}</g>`;
}

const svg = `<svg xmlns="${NS}" viewBox="0 0 285.75 285.75" class="lolly-mark" aria-hidden="true">${variant('primary')}${variant('reverse')}</svg>`;
const out = `// SPDX-License-Identifier: MPL-2.0
// GENERATED by scripts/gen-lolly-mark.ts from icon-primary.svg and icon-reverse.svg.
/** Full-colour UI artwork. Theme CSS selects primary/reverse shading; --lolly-swirl
 * tints the coloured spiral. The three spin classes support interaction-only motion. */
export const LOLLY_MARK_SVG = ${JSON.stringify(svg)};
`;
if (process.argv.includes('--check')) {
  if (readFileSync(OUT, 'utf8') !== out) throw new Error('Lolly UI mark is stale; run node scripts/gen-lolly-mark.ts');
  console.log('Lolly UI mark matches the primary/reverse artwork.');
} else {
  writeFileSync(OUT, out, 'utf8');
  console.log(`Generated Lolly primary/reverse mark (${svg.length} bytes).`);
}
