// SPDX-License-Identifier: MPL-2.0
/** Validate repository closure and generate the release checklist. */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { loadInventory as loadDependencies, validateCoverage as validateDependencies } from './audit-all.ts';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const INVENTORY_PATH = path.join(REPO, 'security', 'repository-inventory.json');
const OUTPUT = path.join(REPO, 'security', 'release-checklist.md');

interface Repository { id: string; path: string; owner: string; required: boolean }
interface GeneratedArtifact { id: string; paths: string[]; repair: string; check: string }
interface ReleaseTarget { id: string; build: string; tests: string[]; signing: boolean }
interface Inventory {
  schemaVersion: 1;
  repositories: Repository[];
  generatedArtifacts: GeneratedArtifact[];
  releaseTargets: ReleaseTarget[];
  platformMatrix: Record<string, string[]>;
}

export function submodulePaths(source = readFileSync(path.join(REPO, '.gitmodules'), 'utf8')): string[] {
  return [...source.matchAll(/^\s*path\s*=\s*(.+?)\s*$/gm)].map((match) => match[1]!).sort();
}

export function validateRepositoryInventory(inventory: Inventory): void {
  if (inventory.schemaVersion !== 1) throw new Error('repository inventory schemaVersion must be 1');
  const declared = inventory.repositories.filter((repo) => repo.path !== '.').map((repo) => repo.path).sort();
  const actual = submodulePaths();
  if (JSON.stringify(declared) !== JSON.stringify(actual)) {
    throw new Error(`repository inventory does not match .gitmodules\ndeclared: ${declared.join(', ')}\nactual: ${actual.join(', ')}`);
  }
  const scripts = (JSON.parse(readFileSync(path.join(REPO, 'package.json'), 'utf8')) as { scripts: Record<string, string> }).scripts;
  const referencedScripts = new Set<string>();
  const collect = (command: string): void => {
    for (const match of command.matchAll(/npm run ([\w:-]+)/g)) referencedScripts.add(match[1]!);
  };
  for (const artifact of inventory.generatedArtifacts) {
    for (const filename of artifact.paths) if (!existsSync(path.join(REPO, filename))) throw new Error(`${artifact.id}: missing ${filename}`);
    collect(artifact.repair); collect(artifact.check);
  }
  for (const target of inventory.releaseTargets) {
    collect(target.build);
    for (const test of target.tests) referencedScripts.add(test);
  }
  for (const tests of Object.values(inventory.platformMatrix)) for (const test of tests) referencedScripts.add(test);
  const missing = [...referencedScripts].filter((script) => !scripts[script]).sort();
  if (missing.length) throw new Error(`repository inventory references missing package scripts: ${missing.join(', ')}`);
  validateDependencies(loadDependencies());
}

export function renderChecklist(inventory: Inventory): string {
  const lines = [
    '<!-- Generated by scripts/release-checklist.ts; do not edit by hand. -->',
    '# Release checklist',
    '',
    'This is the repository-closure checklist. Commands are authoritative; tick boxes are intentionally reset on every generated copy.',
    '',
    '## Repository closure',
    '',
    '- [ ] `git submodule status --recursive` has no missing (`-`) or conflicted (`U`) checkout.',
    '- [ ] Intended changes are committed in each child repository before its parent gitlink.',
    '- [ ] `npm run audit:all`, `npm run secrets:scan:checkout`, and `npm run check:workflow-pins` pass.',
    '- [ ] `npm run typecheck`, `npm run check:maintainability`, and `npm run lint:changed -- --all` pass.',
    '',
    '| Repository | Path | Required |',
    '|---|---|---|',
    ...inventory.repositories.map((repo) => `| ${repo.owner} | \`${repo.path}\` | ${repo.required ? 'yes' : 'optional/private'} |`),
    '',
    '## Generated artifacts',
    '',
    '| Artifact | Outputs | Repair | Verify |',
    '|---|---|---|---|',
    ...inventory.generatedArtifacts.map((artifact) => `| ${artifact.id} | ${artifact.paths.map((item) => `\`${item}\``).join('<br>')} | \`${artifact.repair}\` | \`${artifact.check}\` |`),
    '',
    '## Target builds',
    '',
    '| Target | Build | Required test shards | Catalogue signature |',
    '|---|---|---|---|',
    ...inventory.releaseTargets.map((target) => `| ${target.id} | \`${target.build}\` | ${target.tests.map((test) => `\`npm run ${test}\``).join('<br>')} | ${target.signing ? 'required' : 'not applicable'} |`),
    '',
    'For signed targets, provide `LOLLY_CATALOG_SIGNING_PRIVATE_JWK` and `LOLLY_CATALOG_SIGNING_PUBLIC_JWK`; the release wrapper verifies that they match without printing either value.',
    '',
    '## Platform evidence',
    '',
    ...Object.entries(inventory.platformMatrix).map(([platform, tests]) => `- [ ] **${platform}:** ${tests.map((test) => `\`npm run ${test}\``).join(', ')}`),
    '',
    '## Publication',
    '',
    '- [ ] Catalogue/profile views were rebuilt for every mounted profile after community manifest changes.',
    '- [ ] Release artifacts have recorded SHA-256 digests and their source commit/submodule pointers are recoverable.',
    '- [ ] SBOM, third-party notices, release notes, privacy/security docs, and vulnerability-reporting links match the shipped target.',
    '- [ ] Credentials used by the release came from managed secret storage and no plaintext deployment file is included.',
    '',
  ];
  return `${lines.join('\n')}\n`;
}

export function main(argv = process.argv.slice(2)): number {
  const inventory = JSON.parse(readFileSync(INVENTORY_PATH, 'utf8')) as Inventory;
  validateRepositoryInventory(inventory);
  const rendered = renderChecklist(inventory);
  if (argv.includes('--write')) {
    writeFileSync(OUTPUT, rendered);
    console.log('wrote security/release-checklist.md');
    return 0;
  }
  if (!existsSync(OUTPUT) || readFileSync(OUTPUT, 'utf8') !== rendered) {
    console.error('release checklist drift: run npm run build:release-checklist');
    return 1;
  }
  console.log(`release inventory: ${inventory.repositories.length} repositories, ${inventory.generatedArtifacts.length} artifact groups, ${inventory.releaseTargets.length} targets`);
  return 0;
}

const invoked = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : '';
if (import.meta.url === invoked) {
  try { process.exitCode = main(); }
  catch (error) { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; }
}
