#!/usr/bin/env node
/**
 * Catalog validator.
 *
 * Run as: npm run validate:catalog
 *
 * Verifies every tool and asset against its JSON Schema, plus structural
 * invariants the schemas can't express on their own:
 *
 *   - No duplicate tool IDs across the catalog
 *   - No duplicate asset IDs
 *   - Every tool referenced in tools/index.json has a tool.json under tools/<id>/
 *   - tools/index.json entries match their manifest (no denormalisation drift)
 *   - Every asset format URL resolves to a file that exists on disk
 *   - Every asset checksum matches the file's actual SHA-256 on disk
 *   - Default `bindToProfile` values reference real profile fields
 *   - `palette` references on color inputs point to real palette assets
 *   - `replacedBy` on deprecated assets points to a real, non-deprecated asset
 *   - Brand-overlay declarations (`extends`) are sound: base exists in
 *     community/, community tools never declare one, overlay keeps the base id
 *
 * Index and checksums are generated by `npm run build:catalog`. This validator
 * is the guard that fails CI if either was committed stale.
 *
 * Exit code: 0 on success, 1 on any failure. Designed to run in CI before
 * publishing the catalog.
 */

import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
// Schemas declare the draft 2020-12 dialect, so use Ajv's 2020 build (the
// default export only knows draft-07 and throws on the unknown meta-schema).
import Ajv from 'ajv/dist/2020.js';
// Shared catalog-entry derivation — the single source of truth for how a manifest
// maps to a tools/index.json entry (including the `exportable` flag). Importing it
// here (rather than re-deriving) prevents the two scripts from drifting. The build
// script only writes the index when run directly, so this import has no side effect.
import { entryFromManifest } from './build-catalog-index.ts';
// Brand palette (pure data — no DOM/browser deps, safe to import in Node). Used
// below to assert no hex carries two conflicting CMYK ink values, since the PDF
// export's hex→CMYK lookup (buildCmykPaletteMap) is keyed on hex and would
// silently resolve such a clash by entry order.
import { PALETTE } from '../shells/web/src/palette.ts';
import { isThemableIconSvg, parseThemedAssetId, parseIconThemesDoc } from '../engine/src/icon-theme.ts';
import { LANGS } from '../engine/src/lang.ts';
// Shared-hook-region drift guard — the writer (npm run sync:shared) and this
// check share one parser (same import-without-side-effect pattern as
// entryFromManifest above), so "what sync writes" and "what CI accepts" can't
// drift apart.
import { verifySharedRegions } from './sync-shared-hooks.ts';

// Fields tools/index.json mirrors from each manifest — kept in sync with
// scripts/build-catalog-index.ts.
const INDEX_FIELDS = ['name', 'description', 'version', 'status', 'category'];

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const PROFILE_FIELDS = new Set([
  'firstname', 'lastname', 'email', 'phone', 'city', 'country', 'headshot',
]);

// ─── Load schemas ───────────────────────────────────────────────────────────

const toolSchema = readJson('schemas/tool.schema.json');
const assetSchema = readJson('schemas/asset.schema.json');
const tokensSchema = readJson('schemas/tokens.schema.json');

const ajv = new Ajv({ allErrors: true, strict: false });
const validateTool = ajv.compile<any>(toolSchema);
const validateAsset = ajv.compile<any>(assetSchema);
const validateTokens = ajv.compile<any>(tokensSchema);

// ─── Collect everything ─────────────────────────────────────────────────────

const errors: string[] = [];
const warnings: string[] = [];

const toolsDir = join(ROOT, 'tools');
const assetsIndex = readJson('catalog/assets/index.json');
const toolsIndex = readJson('catalog/tools/index.json');

// Underscore-prefixed dirs are pack infrastructure (community/_shared, the
// canonical hook-helper corpus), not tools — use-profile.ts excludes them from
// the view, and this filter keeps a stale view from failing as "missing tool.json".
const toolDirs = readdirSync(toolsDir).filter(d =>
  !d.startsWith('_') && statSync(join(toolsDir, d)).isDirectory(),
);

// ─── Tool validation ────────────────────────────────────────────────────────

const seenToolIds = new Set<string>();
// Dynamic manifest/index/asset JSON is validated against its JSON Schema at
// runtime; typing it as `any` here keeps the validator faithful without
// re-declaring every schema shape in TypeScript.
const toolManifests = new Map<string, any>(); // id → manifest

for (const dir of toolDirs) {
  const manifestPath = `tools/${dir}/tool.json`;
  const manifest = readJsonOptional(manifestPath);
  if (!manifest) {
    errors.push(`[${dir}] missing tool.json`);
    continue;
  }

  if (manifest.id !== dir) {
    errors.push(`[${dir}] manifest id "${manifest.id}" doesn't match directory name`);
  }

  if (seenToolIds.has(manifest.id)) {
    errors.push(`[${dir}] duplicate tool id "${manifest.id}"`);
  }
  seenToolIds.add(manifest.id);
  toolManifests.set(manifest.id, manifest);

  if (!validateTool(manifest)) {
    for (const err of validateTool.errors ?? []) {
      errors.push(`[${dir}] schema: ${err.instancePath || '/'} ${err.message}`);
    }
    continue;
  }

  // Required files present?
  if (!existsSync(join(ROOT, `tools/${dir}/template.html`))) {
    errors.push(`[${dir}] missing template.html`);
  }
  if (manifest.hooks && !existsSync(join(ROOT, `tools/${dir}/hooks.js`))) {
    errors.push(`[${dir}] manifest declares hooks but hooks.js is missing`);
  }

  // On-device utility conventions (privacy:'on-device'): the tool processes the
  // user's OWN content, so its output must never be watermarked or stamped with
  // provenance. An experimental tool force-watermarks its exports, which directly
  // contradicts that — so the two are mutually exclusive. (The no-metadata side is
  // enforced at runtime: the exportFile path embeds nothing, and the render path
  // skips provenance for on-device tools.)
  if (manifest.privacy === 'on-device' && manifest.status === 'experimental') {
    errors.push(`[${dir}] privacy:'on-device' tools must not be status:'experimental' (experimental force-watermarks exports, which must never happen to a user's own file)`);
  }

  // bindToProfile checks
  for (const input of manifest.inputs) {
    if (input.bindToProfile && !PROFILE_FIELDS.has(input.bindToProfile)) {
      warnings.push(`[${dir}] input "${input.id}" bindToProfile "${input.bindToProfile}" is not a known profile field`);
    }
  }

  // composes: ids must be unique within the manifest (they key {{asset <id>}} +
  // the render memo, so a duplicate silently shadows the earlier one).
  if (Array.isArray(manifest.composes)) {
    const seen = new Set<string>();
    for (const c of manifest.composes) {
      if (c && typeof c.id === 'string') {
        if (seen.has(c.id)) errors.push(`[${dir}] duplicate composes id "${c.id}"`);
        seen.add(c.id);
      }
    }
    if (manifest.composes.length && !(manifest.capabilities ?? []).includes('compose')) {
      errors.push(`[${dir}] declares "composes" but is missing the "compose" capability`);
    }
  }
}

// composes must reference real tools — a typo'd child id would only 404 at render
// time (and silently collapse the embed slot), so catch it here.
for (const [id, manifest] of toolManifests) {
  for (const c of manifest.composes ?? []) {
    if (c?.tool && !toolManifests.has(c.tool)) {
      errors.push(`[${id}] composes references unknown tool "${c.tool}"`);
    }
  }
}

// Cross-check the tool index references real tools, and that each entry matches
// its manifest. The manifest is the source of truth; the index is generated.
const indexedIds = new Set<string>();
for (const entry of toolsIndex.tools) {
  indexedIds.add(entry.id);
  const manifest = toolManifests.get(entry.id);
  if (!manifest) {
    errors.push(`tools/index.json references unknown tool "${entry.id}"`);
    continue;
  }
  for (const field of INDEX_FIELDS) {
    if (entry[field] !== manifest[field]) {
      errors.push(`tools/index.json: "${entry.id}" ${field} "${entry[field]}" ≠ manifest "${manifest[field]}" — run \`npm run build:catalog\``);
    }
  }
  // Derived flags: reuse the shared derivation so the generator and validator
  // can't drift on what they mean. `exportable` mirrors isExportable();
  // `personalized` (bindToProfile present) gates profile-aware gallery previews —
  // both are manifest-derived, so a forgotten `npm run build:catalog` after adding
  // bindToProfile would otherwise silently leave a tool un-personalized. (icon is
  // disk-derived and intentionally not checked here; `preview` IS checked below.)
  const derived: any = entryFromManifest(manifest);
  if (entry.exportable !== derived.exportable) {
    errors.push(`tools/index.json: "${entry.id}" exportable ${entry.exportable} ≠ derived ${derived.exportable} — run \`npm run build:catalog\``);
  }
  if (!!entry.personalized !== !!derived.personalized) {
    errors.push(`tools/index.json: "${entry.id}" personalized ${!!entry.personalized} ≠ derived ${!!derived.personalized} — run \`npm run build:catalog\``);
  }
  // Preview path is disk-derived: build-previews rasterises expensive-to-paint SVGs
  // (huge paths / thousands of dots) to .png, so entryFromManifest picks the extension
  // that actually exists on disk. A stale index — pointing at .svg when the committed
  // preview is .png — renders as a broken image in the gallery. Flag the drift, but
  // only when the derived path points at a file that exists: a fresh checkout with no
  // generated previews yet is fine (the gallery tolerates an absent preview), so we
  // don't force a regeneration there.
  if (
    entry.preview !== derived.preview &&
    typeof derived.preview === 'string' &&
    existsSync(join(ROOT, derived.preview.replace(/^\//, '')))
  ) {
    errors.push(`tools/index.json: "${entry.id}" preview ${entry.preview} ≠ derived ${derived.preview} — run \`npm run build:catalog\` (after \`npm run previews\`)`);
  }
}
// Every tool with a manifest must appear in the index.
for (const id of toolManifests.keys()) {
  if (!indexedIds.has(id)) {
    errors.push(`tools/index.json is missing tool "${id}" — run \`npm run build:catalog\``);
  }
}

// ─── Canonical input registry (soft check) ──────────────────────────────────
// Tools SHOULD reuse canonical input ids + constraints so the /pro batch grid
// collapses them into one bulk-writable column. Divergence is a warning, not an
// error: a tool may legitimately need different constraints, but it then forfeits
// the shared column. Keeps schemas/canonical-inputs.json honest as tools evolve.
const canonicalInputs = readJsonOptional('schemas/canonical-inputs.json')?.inputs ?? {};
for (const [toolId, manifest] of toolManifests) {
  for (const input of manifest.inputs) {
    const canon = canonicalInputs[input.id];
    if (!canon) continue;
    if (input.type !== canon.type) {
      warnings.push(`[${toolId}] input "${input.id}" type "${input.type}" diverges from canonical "${canon.type}" — won't share the /pro column (schemas/canonical-inputs.json)`);
      continue; // type mismatch already breaks the column; constraint checks are moot
    }
    const numKeys = canon.type === 'number' ? ['min', 'max', 'step'] : [];
    for (const k of numKeys) {
      if (canon[k] !== undefined && (input[k] ?? null) !== canon[k]) {
        warnings.push(`[${toolId}] input "${input.id}" ${k}=${input[k] ?? 'unset'} diverges from canonical ${k}=${canon[k]} — breaks bulk-fill in /pro (schemas/canonical-inputs.json)`);
      }
    }
    if (canon.type === 'select' && Array.isArray(canon.options)) {
      const norm = (opts: any): string => (opts ?? []).map((o: any) => (o && typeof o === 'object' ? o.value : o)).join('|');
      if (norm(input.options) !== norm(canon.options)) {
        warnings.push(`[${toolId}] input "${input.id}" options diverge from canonical — breaks bulk-fill in /pro (schemas/canonical-inputs.json)`);
      }
    }
  }
}

// ─── i18n sidecars (plans/localize.md §7) ──────────────────────────────────
// tools/<id>/i18n/<lang>.json is a flat, dotted-path overlay onto the
// manifest's own user-facing strings (engine/src/loader.ts's
// applyManifestI18n applies it at load time; build-catalog-index.ts folds
// name/description/featured.blurb into the catalog index). Every key must
// resolve to a real manifest field — an orphaned key (after a manifest
// refactor renamed/removed an input) would silently translate nothing.
const SIDECAR_LANGS = new Set(LANGS.filter(l => l !== 'en'));
for (const [toolId, manifest] of toolManifests) {
  const i18nDir = join(ROOT, `tools/${toolId}/i18n`);
  if (!existsSync(i18nDir)) continue;
  for (const file of readdirSync(i18nDir)) {
    if (!file.endsWith('.json')) continue;
    const lang = file.replace(/\.json$/, '');
    if (!SIDECAR_LANGS.has(lang as any)) {
      errors.push(`[${toolId}] i18n/${file}: "${lang}" is not a supported language (${[...SIDECAR_LANGS].join(', ')})`);
      continue;
    }
    const overlay = readJsonOptional(`tools/${toolId}/i18n/${file}`);
    if (!overlay) continue; // readJsonOptional already recorded a parse error
    if (typeof overlay !== 'object' || Array.isArray(overlay)) {
      errors.push(`[${toolId}] i18n/${file} must be a flat JSON object`);
      continue;
    }
    for (const [key, value] of Object.entries(overlay)) {
      if (typeof value !== 'string') {
        errors.push(`[${toolId}] i18n/${file}: "${key}" value must be a string`);
        continue;
      }
      const reason = unresolvedSidecarKey(manifest, key);
      if (reason) errors.push(`[${toolId}] i18n/${file}: key "${key}" ${reason}`);
    }
  }
}

// ─── Palette consistency ────────────────────────────────────────────────────
// The CMYK-aware PDF export builds a hex→CMYK lookup (buildCmykPaletteMap in
// shells/web/src/bridge/export.js) keyed on each swatch's hex. The brand palette
// deliberately repeats hexes (e.g. Pine/Black/White appear as ramp endpoints),
// which is fine — but only as long as the repeats agree on their ink values
// (null = "unspecified" is always compatible). If two entries with the SAME hex
// declared DIFFERENT non-null CMYK, the lookup's result would depend purely on
// array order — a silent, order-dependent ink mismatch. Catch that here.
{
  const cmykByHex = new Map<string, { cmyk: readonly [number, number, number, number]; label: string }>(); // normalised hex → { cmyk, label }
  for (const { hex, cmyk, label } of PALETTE) {
    if (!cmyk) continue; // null = unspecified, never conflicts
    const key = String(hex).replace('#', '').toLowerCase();
    const prev = cmykByHex.get(key);
    if (prev && JSON.stringify(prev.cmyk) !== JSON.stringify(cmyk)) {
      errors.push(`palette: hex "${hex}" has conflicting CMYK — "${prev.label}" ${JSON.stringify(prev.cmyk)} vs "${label}" ${JSON.stringify(cmyk)} (the PDF export's hex→CMYK lookup would resolve this by entry order)`);
    } else if (!prev) {
      cmykByHex.set(key, { cmyk, label });
    }
  }
}

// ─── Asset validation ───────────────────────────────────────────────────────

const seenAssetIds = new Set<string>();
const assetById = new Map<string, any>();
const iconThemePalettes: { assetId: string; themes: ReturnType<typeof parseIconThemesDoc> }[] = [];     // { assetId, themes } per icon-themes palette
const themableIconDefaults: { assetId: string; c1: string; c2: string }[] = [];  // { assetId, c1, c2 } per themable icon

for (const asset of assetsIndex.assets) {
  if (seenAssetIds.has(asset.id)) {
    errors.push(`duplicate asset id "${asset.id}"`);
  }
  seenAssetIds.add(asset.id);
  assetById.set(asset.id, asset);

  if (!validateAsset(asset)) {
    for (const err of validateAsset.errors ?? []) {
      errors.push(`[asset ${(asset as { id: string }).id}] schema: ${err.instancePath || '/'} ${err.message}`);
    }
    continue;
  }

  // Format files exist on disk, and their checksums match the actual bytes?
  const formatLists = [asset.formats, ...Object.values(asset.locales ?? {})];
  for (const formats of formatLists) {
    for (const fmt of formats ?? []) {
      const absPath = join(ROOT, fmt.url.replace(/^\//, ''));
      if (!existsSync(absPath)) {
        errors.push(`[asset ${asset.id}] format "${fmt.format}" url "${fmt.url}" does not exist on disk`);
        continue;
      }
      const bytes = readFileSync(absPath);
      if (fmt.checksum === 'sha256-PLACEHOLDER') {
        warnings.push(`[asset ${asset.id}] format "${fmt.format}" has placeholder checksum — run \`npm run build:catalog\``);
      } else {
        const actual = `sha256-${createHash('sha256').update(bytes).digest('base64')}`;
        if (fmt.checksum !== actual) {
          errors.push(`[asset ${asset.id}] format "${fmt.format}" checksum stale — run \`npm run build:catalog\``);
        }
      }

      // Tokens assets carry a DTCG document — validate its structure too.
      if (asset.type === 'tokens' && fmt.format === 'json') {
        let doc;
        try { doc = JSON.parse(bytes.toString('utf8')); } catch {
          errors.push(`[asset ${asset.id}] tokens doc "${fmt.url}" is not valid JSON`);
          continue;
        }
        if (!validateTokens(doc)) {
          for (const err of validateTokens.errors ?? []) {
            errors.push(`[asset ${asset.id}] tokens: ${err.instancePath || '/'} ${err.message}`);
          }
        }
      }

      // Icon-themes palettes: the colour pairings the shells offer for themable
      // icons. parseIconThemesDoc is the runtime's reader — any entry it drops
      // (bad id charset, unusable colour) would silently vanish from the UI, so
      // dropping is an authoring error here.
      if (asset.type === 'palette' && asset.tags?.includes('icon-themes') && fmt.format === 'json') {
        let doc;
        try { doc = JSON.parse(bytes.toString('utf8')); } catch {
          errors.push(`[asset ${asset.id}] icon-themes doc "${fmt.url}" is not valid JSON`);
          continue;
        }
        const themes = parseIconThemesDoc(doc);
        const declared = Array.isArray(doc?.themes) ? doc.themes.length : 0;
        if (!declared) {
          errors.push(`[asset ${asset.id}] icon-themes doc has no themes[] array`);
        } else if (themes.length !== declared) {
          errors.push(`[asset ${asset.id}] icon-themes doc has ${declared - themes.length} entr${declared - themes.length === 1 ? 'y' : 'ies'} the runtime would drop (theme ids must be [a-z0-9-], c1/c2 must be simple CSS colours)`);
        }
        const ids = themes.map(t => t.id);
        if (new Set(ids).size !== ids.length) {
          errors.push(`[asset ${asset.id}] icon-themes doc has duplicate theme ids`);
        }
        iconThemePalettes.push({ assetId: asset.id, themes });
      }

      // Themable two-colour icons (tag "themable"): the shells' theme baking is
      // a string rewrite, so the SVG must follow the exact contract the engine's
      // isThemableIconSvg/applyIconTheme expect — one default
      // <defs><style>.c1{fill:…}.c2{fill:…}</style></defs> block, shape classes
      // limited to c1/c2, and no stray style/stroke attributes.
      if (asset.tags?.includes('themable') && fmt.format === 'svg') {
        const svg = bytes.toString('utf8');
        const styleBlocks = svg.match(/<style>/g) ?? [];
        if (!isThemableIconSvg(svg)) {
          errors.push(`[asset ${asset.id}] themable icon missing the default .c1/.c2 style block`);
        } else if (styleBlocks.length !== 1) {
          errors.push(`[asset ${asset.id}] themable icon must contain exactly one <style> block`);
        } else {
          const fills = svg.match(/\.c1\{fill:([^}]*)\}\.c2\{fill:([^}]*)\}/);
          themableIconDefaults.push({ assetId: asset.id, c1: fills![1]!, c2: fills![2]! });
        }
        const body = svg.replace(/<defs><style>[\s\S]*?<\/style><\/defs>/, '');
        const badClass = [...body.matchAll(/class="([^"]*)"/g)].find(m => m[1] !== 'c1' && m[1] !== 'c2');
        if (badClass) errors.push(`[asset ${asset.id}] themable icon has a class other than c1/c2: "${badClass[1]}"`);
        if (/style="/.test(body)) errors.push(`[asset ${asset.id}] themable icon has an inline style attribute`);
        if (/\bstroke[-\w]*\s*[:=]/.test(body)) errors.push(`[asset ${asset.id}] themable icon has stroke styling (fills only)`);
      }
    }
  }
}

// The first icon-themes pairing is the DEFAULT the picker maps to a plain
// (suffix-less) id — it only reads true if it matches the fills actually baked
// into the icons. Reordering the palette without recolouring the icons would
// silently mislabel every default pick.
for (const pal of iconThemePalettes) {
  const first = pal.themes[0];
  if (!first) continue;
  for (const icon of themableIconDefaults) {
    if (icon.c1.toLowerCase() !== first.c1.toLowerCase() || icon.c2.toLowerCase() !== first.c2.toLowerCase()) {
      errors.push(`[asset ${icon.assetId}] default fills (${icon.c1}/${icon.c2}) don't match the first icon-themes pairing "${first.id}" (${first.c1}/${first.c2}) in ${pal.assetId}`);
    }
  }
}

// Resolve replacedBy
for (const asset of assetsIndex.assets) {
  if (asset.deprecated && asset.replacedBy) {
    const replacement = assetById.get(asset.replacedBy);
    if (!replacement) {
      errors.push(`[asset ${asset.id}] replacedBy "${asset.replacedBy}" doesn't exist`);
    } else if (replacement.deprecated) {
      errors.push(`[asset ${asset.id}] replacedBy "${asset.replacedBy}" is also deprecated`);
    }
  }
}

// Default favourites (seeded on first run) must each reference a real asset — a typo'd
// id would silently seed a favourite that never resolves to a tile.
if (assetsIndex.defaultFavourites !== undefined) {
  if (!Array.isArray(assetsIndex.defaultFavourites)) {
    errors.push(`assets/index.json: "defaultFavourites" must be an array of asset ids`);
  } else {
    for (const id of assetsIndex.defaultFavourites) {
      if (typeof id !== 'string' || !assetById.has(id)) {
        errors.push(`assets/index.json: defaultFavourites entry "${id}" is not a known asset id`);
      }
    }
  }
}

// ─── Cross-references: tools → assets ───────────────────────────────────────

for (const [toolId, manifest] of toolManifests) {
  for (const input of manifest.inputs) {
    // Default asset refs must resolve. A default may carry an icon theme
    // suffix (`<id>?theme=<t>`) — parse it exactly the way the runtime does,
    // so anything that validates here also resolves at mount.
    if (input.type === 'asset' && typeof input.default === 'string') {
      const { baseId, theme } = parseThemedAssetId(input.default);
      if (baseId.includes('?')) {
        errors.push(`[${toolId}] input "${input.id}" default asset "${input.default}" has a malformed ?theme= suffix (theme ids are [a-z0-9-])`);
      } else if (!assetById.has(baseId)) {
        errors.push(`[${toolId}] input "${input.id}" default asset "${input.default}" not in catalog`);
      } else if (theme && !iconThemePalettes.some(p => p.themes.some(t => t.id === theme))) {
        errors.push(`[${toolId}] input "${input.id}" default asset theme "${theme}" not in any icon-themes palette`);
      }
    }
    // Color palette refs must resolve
    if (input.type === 'color' && input.palette) {
      const ref = assetById.get(input.palette);
      if (!ref) {
        errors.push(`[${toolId}] input "${input.id}" palette "${input.palette}" not in catalog`);
      } else if (ref.type !== 'palette') {
        errors.push(`[${toolId}] input "${input.id}" palette "${input.palette}" exists but isn't of type 'palette'`);
      }
    }
  }
}

// ─── Brand overlay declarations (extends) ───────────────────────────────────
// A brand-pack tool may declare `"extends": "community"` — scripts/use-profile.ts
// then composes its view dir per-file from community/<id>/ + the overlay
// (overlay wins, `extends` stripped from the composed tool.json). The composed
// RESULT is already validated as a normal tool by the per-tool checks above,
// which run against the tools/ VIEW. What the view can't tell us is whether the
// DECLARATIONS in the pack sources are sound — so walk the real packs here
// (community/ + brands/*/tools/, same as the shared-hooks guard below), even
// for tools outside the active profile:
//   - community tools must never declare an overlay (they are the bases)
//   - the only supported base pack in v1 is "community"
//   - the overlay dir must keep the base's id (ids are permanent contracts)
//   - the base community/<id>/tool.json must exist (missing base = the profile
//     build fails loudly; catch the authoring error here too, before a switch)
{
  const packToolDirs = (root: string): string[] => {
    const abs = join(ROOT, root);
    if (!existsSync(abs)) return []; // private pack not mounted — nothing to check
    return readdirSync(abs).filter((d) =>
      !d.startsWith('.') && !d.startsWith('_') && d !== 'node_modules' &&
      statSync(join(abs, d)).isDirectory());
  };

  for (const dir of packToolDirs('community')) {
    const manifest = readJsonOptional(`community/${dir}/tool.json`);
    if (manifest && manifest.extends !== undefined) {
      errors.push(`[community/${dir}] declares "extends" — community tools are overlay bases; only a brand pack may declare an overlay`);
    }
  }

  const brandsRoot = join(ROOT, 'brands');
  const brands = existsSync(brandsRoot)
    ? readdirSync(brandsRoot).filter((b) =>
        !b.startsWith('.') && statSync(join(brandsRoot, b)).isDirectory() &&
        existsSync(join(brandsRoot, b, 'tools')))
    : [];
  for (const brand of brands) {
    for (const dir of packToolDirs(`brands/${brand}/tools`)) {
      const rel = `brands/${brand}/tools/${dir}`;
      const manifest = readJsonOptional(`${rel}/tool.json`);
      if (!manifest || manifest.extends === undefined) continue;
      if (manifest.extends !== 'community') {
        errors.push(`[${rel}] "extends": ${JSON.stringify(manifest.extends)} — v1 supports only "community" as the base pack`);
        continue;
      }
      if (manifest.id !== dir) {
        errors.push(`[${rel}] overlay id "${manifest.id}" doesn't match its directory name — an overlay and its base share the same tool id`);
      }
      if (!existsSync(join(ROOT, 'community', dir, 'tool.json'))) {
        errors.push(`[${rel}] extends "community" but community/${dir}/tool.json does not exist — the overlay's base is missing (the profile build would fail loudly on this)`);
      }
    }
  }
}

// ─── Shared hook regions (community/_shared) ────────────────────────────────
// Tool hooks.js ship self-contained (no imports), so shared helper blocks are
// byte-copies of community/_shared/*.js regions between `lolly:shared` markers,
// maintained by `npm run sync:shared`. A hand-edited consumer region (or a
// canonical edit that skipped the sync) would silently re-fork the corpus the
// same way the old copy-paste did — fail closed here, exactly like the
// tools/index.json drift check above. This walks the real pack sources
// (community/ + brands/*/tools/), not the tools/ view, so even tools outside
// the active profile are guarded.
for (const err of verifySharedRegions()) {
  errors.push(`shared-hooks: ${err}`);
}

// ─── Report ─────────────────────────────────────────────────────────────────

if (warnings.length) {
  console.warn(`\nWarnings (${warnings.length}):`);
  for (const w of warnings) console.warn(`  ⚠ ${w}`);
}

if (errors.length) {
  console.error(`\nErrors (${errors.length}):`);
  for (const e of errors) console.error(`  ✗ ${e}`);
  console.error(`\nCatalog validation failed.`);
  process.exit(1);
}

console.log(`\n✓ Catalog OK — ${toolManifests.size} tools, ${assetById.size} assets`);
if (warnings.length) console.log(`  (with ${warnings.length} warning${warnings.length === 1 ? '' : 's'})`);

// ─── Helpers ────────────────────────────────────────────────────────────────

function readJson(rel: string): any {
  return JSON.parse(readFileSync(join(ROOT, rel), 'utf8'));
}

// Mirrors the traversal engine/src/loader.ts's applyManifestI18n uses to apply
// a sidecar overlay — but reports WHY a key doesn't resolve instead of
// silently skipping it (silent-skip is the right runtime behaviour; a build-time
// validator's job is to catch the authoring mistake that would cause it).
function unresolvedSidecarKey(manifest: any, key: string): string | null {
  if (key === 'name' || key === 'description' || key === 'a11yLabel') return null;
  if (key === 'featured.blurb') return manifest.featured ? null : 'references featured.blurb but the manifest has no featured block';

  const m = /^inputs\.([^.]+)\.(.+)$/.exec(key);
  if (!m) return 'does not match any known overlay path (name, description, a11yLabel, featured.blurb, inputs.<id>.…)';
  const [, inputId, rest] = m as unknown as [string, string, string];
  const input = (manifest.inputs ?? []).find((i: any) => i.id === inputId);
  if (!input) return `references unknown input "${inputId}"`;

  if (['label', 'help', 'placeholder', 'section', 'suffix'].includes(rest)) return null;
  // (.*) not (.+): mirrors applyManifestI18n — an option's value may be ''.
  const optMatch = /^options\.(.*)$/.exec(rest);
  if (optMatch) {
    const found = (input.options ?? []).some((o: any) => o.value === optMatch[1]);
    return found ? null : `references unknown option "${optMatch[1]}" on input "${inputId}"`;
  }
  if (rest === 'addMenu.label') return input.addMenu ? null : `input "${inputId}" has no addMenu`;
  const fieldMatch = /^fields\.([^.]+)\.(.+)$/.exec(rest);
  if (fieldMatch) {
    const [, fieldId, fieldRest] = fieldMatch as unknown as [string, string, string];
    const field = (input.fields ?? []).find((f: any) => f.id === fieldId);
    if (!field) return `references unknown field "${fieldId}" on input "${inputId}"`;
    if (['label', 'help', 'placeholder'].includes(fieldRest)) return null;
    const fieldOptMatch = /^options\.(.*)$/.exec(fieldRest);
    if (fieldOptMatch) {
      const found = (field.options ?? []).some((o: any) => o.value === fieldOptMatch[1]);
      return found ? null : `references unknown option "${fieldOptMatch[1]}" on field "${fieldId}" (input "${inputId}")`;
    }
  }
  return 'does not match any known overlay path';
}

function readJsonOptional(rel: string): any {
  const p = join(ROOT, rel);
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(readFileSync(p, 'utf8'));
  } catch (e) {
    errors.push(`[${rel}] not valid JSON: ${(e as Error).message}`);
    return null;
  }
}
