#!/usr/bin/env node
/**
 * Catalog validator.
 *
 * Run as: npm run validate:catalog
 *
 * Verifies every tool and asset against its JSON Schema, plus structural
 * invariants the schemas can't express on their own:
 *
 *   - No duplicate tool IDs across the catalog
 *   - No duplicate asset IDs
 *   - Every tool referenced in tools/index.json has a tool.json under tools/<id>/
 *   - tools/index.json entries match their manifest (no denormalisation drift)
 *   - Every asset format URL resolves to a file that exists on disk
 *   - Every asset checksum matches the file's actual SHA-256 on disk
 *   - Default `bindToProfile` values reference real profile fields
 *   - `palette` references on color inputs point to real palette assets
 *   - `replacedBy` on deprecated assets points to a real, non-deprecated asset
 *
 * Index and checksums are generated by `npm run build:catalog`. This validator
 * is the guard that fails CI if either was committed stale.
 *
 * Exit code: 0 on success, 1 on any failure. Designed to run in CI before
 * publishing the catalog.
 */

import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
// Schemas declare the draft 2020-12 dialect, so use Ajv's 2020 build (the
// default export only knows draft-07 and throws on the unknown meta-schema).
import Ajv from 'ajv/dist/2020.js';
// Shared catalog-entry derivation — the single source of truth for how a manifest
// maps to a tools/index.json entry (including the `exportable` flag). Importing it
// here (rather than re-deriving) prevents the two scripts from drifting. The build
// script only writes the index when run directly, so this import has no side effect.
import { entryFromManifest } from './build-catalog-index.js';
// Brand palette (pure data — no DOM/browser deps, safe to import in Node). Used
// below to assert no hex carries two conflicting CMYK ink values, since the PDF
// export's hex→CMYK lookup (buildCmykPaletteMap) is keyed on hex and would
// silently resolve such a clash by entry order.
import { PALETTE } from '../shells/web/src/palette.js';

// Fields tools/index.json mirrors from each manifest — kept in sync with
// scripts/build-catalog-index.js.
const INDEX_FIELDS = ['name', 'description', 'version', 'status', 'category'];

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const PROFILE_FIELDS = new Set([
  'firstname', 'lastname', 'email', 'phone', 'city', 'country', 'headshot',
]);

// ─── Load schemas ───────────────────────────────────────────────────────────

const toolSchema = readJson('schemas/tool.schema.json');
const assetSchema = readJson('schemas/asset.schema.json');
const tokensSchema = readJson('schemas/tokens.schema.json');

const ajv = new Ajv({ allErrors: true, strict: false });
const validateTool = ajv.compile(toolSchema);
const validateAsset = ajv.compile(assetSchema);
const validateTokens = ajv.compile(tokensSchema);

// ─── Collect everything ─────────────────────────────────────────────────────

const errors = [];
const warnings = [];

const toolsDir = join(ROOT, 'tools');
const assetsIndex = readJson('catalog/assets/index.json');
const toolsIndex = readJson('catalog/tools/index.json');

const toolDirs = readdirSync(toolsDir).filter(d =>
  statSync(join(toolsDir, d)).isDirectory(),
);

// ─── Tool validation ────────────────────────────────────────────────────────

const seenToolIds = new Set();
const toolManifests = new Map(); // id → manifest

for (const dir of toolDirs) {
  const manifestPath = `tools/${dir}/tool.json`;
  const manifest = readJsonOptional(manifestPath);
  if (!manifest) {
    errors.push(`[${dir}] missing tool.json`);
    continue;
  }

  if (manifest.id !== dir) {
    errors.push(`[${dir}] manifest id "${manifest.id}" doesn't match directory name`);
  }

  if (seenToolIds.has(manifest.id)) {
    errors.push(`[${dir}] duplicate tool id "${manifest.id}"`);
  }
  seenToolIds.add(manifest.id);
  toolManifests.set(manifest.id, manifest);

  if (!validateTool(manifest)) {
    for (const err of validateTool.errors) {
      errors.push(`[${dir}] schema: ${err.instancePath || '/'} ${err.message}`);
    }
    continue;
  }

  // Required files present?
  if (!existsSync(join(ROOT, `tools/${dir}/template.html`))) {
    errors.push(`[${dir}] missing template.html`);
  }
  if (manifest.hooks && !existsSync(join(ROOT, `tools/${dir}/hooks.js`))) {
    errors.push(`[${dir}] manifest declares hooks but hooks.js is missing`);
  }

  // On-device utility conventions (privacy:'on-device'): the tool processes the
  // user's OWN content, so its output must never be watermarked or stamped with
  // provenance. An experimental tool force-watermarks its exports, which directly
  // contradicts that — so the two are mutually exclusive. (The no-metadata side is
  // enforced at runtime: the exportFile path embeds nothing, and the render path
  // skips provenance for on-device tools.)
  if (manifest.privacy === 'on-device' && manifest.status === 'experimental') {
    errors.push(`[${dir}] privacy:'on-device' tools must not be status:'experimental' (experimental force-watermarks exports, which must never happen to a user's own file)`);
  }

  // bindToProfile checks
  for (const input of manifest.inputs) {
    if (input.bindToProfile && !PROFILE_FIELDS.has(input.bindToProfile)) {
      warnings.push(`[${dir}] input "${input.id}" bindToProfile "${input.bindToProfile}" is not a known profile field`);
    }
  }

  // composes: ids must be unique within the manifest (they key {{asset <id>}} +
  // the render memo, so a duplicate silently shadows the earlier one).
  if (Array.isArray(manifest.composes)) {
    const seen = new Set();
    for (const c of manifest.composes) {
      if (c && typeof c.id === 'string') {
        if (seen.has(c.id)) errors.push(`[${dir}] duplicate composes id "${c.id}"`);
        seen.add(c.id);
      }
    }
    if (manifest.composes.length && !(manifest.capabilities ?? []).includes('compose')) {
      errors.push(`[${dir}] declares "composes" but is missing the "compose" capability`);
    }
  }
}

// composes must reference real tools — a typo'd child id would only 404 at render
// time (and silently collapse the embed slot), so catch it here.
for (const [id, manifest] of toolManifests) {
  for (const c of manifest.composes ?? []) {
    if (c?.tool && !toolManifests.has(c.tool)) {
      errors.push(`[${id}] composes references unknown tool "${c.tool}"`);
    }
  }
}

// Cross-check the tool index references real tools, and that each entry matches
// its manifest. The manifest is the source of truth; the index is generated.
const indexedIds = new Set();
for (const entry of toolsIndex.tools) {
  indexedIds.add(entry.id);
  const manifest = toolManifests.get(entry.id);
  if (!manifest) {
    errors.push(`tools/index.json references unknown tool "${entry.id}"`);
    continue;
  }
  for (const field of INDEX_FIELDS) {
    if (entry[field] !== manifest[field]) {
      errors.push(`tools/index.json: "${entry.id}" ${field} "${entry[field]}" ≠ manifest "${manifest[field]}" — run \`npm run build:catalog\``);
    }
  }
  // Derived flags: reuse the shared derivation so the generator and validator
  // can't drift on what they mean. `exportable` mirrors isExportable();
  // `personalized` (bindToProfile present) gates profile-aware gallery previews —
  // both are manifest-derived, so a forgotten `npm run build:catalog` after adding
  // bindToProfile would otherwise silently leave a tool un-personalized. (icon /
  // preview are disk-derived and intentionally not checked here.)
  const derived = entryFromManifest(manifest);
  if (entry.exportable !== derived.exportable) {
    errors.push(`tools/index.json: "${entry.id}" exportable ${entry.exportable} ≠ derived ${derived.exportable} — run \`npm run build:catalog\``);
  }
  if (!!entry.personalized !== !!derived.personalized) {
    errors.push(`tools/index.json: "${entry.id}" personalized ${!!entry.personalized} ≠ derived ${!!derived.personalized} — run \`npm run build:catalog\``);
  }
}
// Every tool with a manifest must appear in the index.
for (const id of toolManifests.keys()) {
  if (!indexedIds.has(id)) {
    errors.push(`tools/index.json is missing tool "${id}" — run \`npm run build:catalog\``);
  }
}

// ─── Canonical input registry (soft check) ──────────────────────────────────
// Tools SHOULD reuse canonical input ids + constraints so the /pro batch grid
// collapses them into one bulk-writable column. Divergence is a warning, not an
// error: a tool may legitimately need different constraints, but it then forfeits
// the shared column. Keeps schemas/canonical-inputs.json honest as tools evolve.
const canonicalInputs = readJsonOptional('schemas/canonical-inputs.json')?.inputs ?? {};
for (const [toolId, manifest] of toolManifests) {
  for (const input of manifest.inputs) {
    const canon = canonicalInputs[input.id];
    if (!canon) continue;
    if (input.type !== canon.type) {
      warnings.push(`[${toolId}] input "${input.id}" type "${input.type}" diverges from canonical "${canon.type}" — won't share the /pro column (schemas/canonical-inputs.json)`);
      continue; // type mismatch already breaks the column; constraint checks are moot
    }
    const numKeys = canon.type === 'number' ? ['min', 'max', 'step'] : [];
    for (const k of numKeys) {
      if (canon[k] !== undefined && (input[k] ?? null) !== canon[k]) {
        warnings.push(`[${toolId}] input "${input.id}" ${k}=${input[k] ?? 'unset'} diverges from canonical ${k}=${canon[k]} — breaks bulk-fill in /pro (schemas/canonical-inputs.json)`);
      }
    }
    if (canon.type === 'select' && Array.isArray(canon.options)) {
      const norm = opts => (opts ?? []).map(o => (o && typeof o === 'object' ? o.value : o)).join('|');
      if (norm(input.options) !== norm(canon.options)) {
        warnings.push(`[${toolId}] input "${input.id}" options diverge from canonical — breaks bulk-fill in /pro (schemas/canonical-inputs.json)`);
      }
    }
  }
}

// ─── Palette consistency ────────────────────────────────────────────────────
// The CMYK-aware PDF export builds a hex→CMYK lookup (buildCmykPaletteMap in
// shells/web/src/bridge/export.js) keyed on each swatch's hex. The brand palette
// deliberately repeats hexes (e.g. Pine/Black/White appear as ramp endpoints),
// which is fine — but only as long as the repeats agree on their ink values
// (null = "unspecified" is always compatible). If two entries with the SAME hex
// declared DIFFERENT non-null CMYK, the lookup's result would depend purely on
// array order — a silent, order-dependent ink mismatch. Catch that here.
{
  const cmykByHex = new Map(); // normalised hex → { cmyk, label }
  for (const { hex, cmyk, label } of PALETTE) {
    if (!cmyk) continue; // null = unspecified, never conflicts
    const key = String(hex).replace('#', '').toLowerCase();
    const prev = cmykByHex.get(key);
    if (prev && JSON.stringify(prev.cmyk) !== JSON.stringify(cmyk)) {
      errors.push(`palette: hex "${hex}" has conflicting CMYK — "${prev.label}" ${JSON.stringify(prev.cmyk)} vs "${label}" ${JSON.stringify(cmyk)} (the PDF export's hex→CMYK lookup would resolve this by entry order)`);
    } else if (!prev) {
      cmykByHex.set(key, { cmyk, label });
    }
  }
}

// ─── Asset validation ───────────────────────────────────────────────────────

const seenAssetIds = new Set();
const assetById = new Map();

for (const asset of assetsIndex.assets) {
  if (seenAssetIds.has(asset.id)) {
    errors.push(`duplicate asset id "${asset.id}"`);
  }
  seenAssetIds.add(asset.id);
  assetById.set(asset.id, asset);

  if (!validateAsset(asset)) {
    for (const err of validateAsset.errors) {
      errors.push(`[asset ${asset.id}] schema: ${err.instancePath || '/'} ${err.message}`);
    }
    continue;
  }

  // Format files exist on disk, and their checksums match the actual bytes?
  const formatLists = [asset.formats, ...Object.values(asset.locales ?? {})];
  for (const formats of formatLists) {
    for (const fmt of formats ?? []) {
      const absPath = join(ROOT, fmt.url.replace(/^\//, ''));
      if (!existsSync(absPath)) {
        errors.push(`[asset ${asset.id}] format "${fmt.format}" url "${fmt.url}" does not exist on disk`);
        continue;
      }
      if (fmt.checksum === 'sha256-PLACEHOLDER') {
        warnings.push(`[asset ${asset.id}] format "${fmt.format}" has placeholder checksum — run \`npm run build:catalog\``);
        continue;
      }
      const actual = `sha256-${createHash('sha256').update(readFileSync(absPath)).digest('base64')}`;
      if (fmt.checksum !== actual) {
        errors.push(`[asset ${asset.id}] format "${fmt.format}" checksum stale — run \`npm run build:catalog\``);
      }

      // Tokens assets carry a DTCG document — validate its structure too.
      if (asset.type === 'tokens' && fmt.format === 'json') {
        let doc;
        try { doc = JSON.parse(readFileSync(absPath, 'utf8')); } catch {
          errors.push(`[asset ${asset.id}] tokens doc "${fmt.url}" is not valid JSON`);
          continue;
        }
        if (!validateTokens(doc)) {
          for (const err of validateTokens.errors) {
            errors.push(`[asset ${asset.id}] tokens: ${err.instancePath || '/'} ${err.message}`);
          }
        }
      }

      // Themable two-colour icons (tag "themable"): the shells' theme baking is
      // a string rewrite, so the SVG must follow the exact contract — one
      // default <defs><style>.c1{fill:…}.c2{fill:…}</style></defs> block, shape
      // classes limited to c1/c2, and no stray style/stroke attributes.
      if (asset.tags?.includes('themable') && fmt.format === 'svg') {
        const svg = readFileSync(absPath, 'utf8');
        const styleBlocks = svg.match(/<style>/g) ?? [];
        if (!/<defs><style>\.c1\{fill:[^}]+\}\.c2\{fill:[^}]+\}<\/style><\/defs>/.test(svg)) {
          errors.push(`[asset ${asset.id}] themable icon missing the default .c1/.c2 style block`);
        } else if (styleBlocks.length !== 1) {
          errors.push(`[asset ${asset.id}] themable icon must contain exactly one <style> block`);
        }
        const body = svg.replace(/<defs><style>[\s\S]*?<\/style><\/defs>/, '');
        const badClass = [...body.matchAll(/class="([^"]*)"/g)].find(m => m[1] !== 'c1' && m[1] !== 'c2');
        if (badClass) errors.push(`[asset ${asset.id}] themable icon has a class other than c1/c2: "${badClass[1]}"`);
        if (/style="/.test(body)) errors.push(`[asset ${asset.id}] themable icon has an inline style attribute`);
        if (/stroke/.test(body)) errors.push(`[asset ${asset.id}] themable icon has stroke styling (fills only)`);
      }
    }
  }
}

// Resolve replacedBy
for (const asset of assetsIndex.assets) {
  if (asset.deprecated && asset.replacedBy) {
    const replacement = assetById.get(asset.replacedBy);
    if (!replacement) {
      errors.push(`[asset ${asset.id}] replacedBy "${asset.replacedBy}" doesn't exist`);
    } else if (replacement.deprecated) {
      errors.push(`[asset ${asset.id}] replacedBy "${asset.replacedBy}" is also deprecated`);
    }
  }
}

// ─── Cross-references: tools → assets ───────────────────────────────────────

for (const [toolId, manifest] of toolManifests) {
  for (const input of manifest.inputs) {
    // Default asset refs must resolve. A default may carry an icon theme
    // suffix (`<id>?theme=<t>`) — the catalog id is the part before it.
    if (input.type === 'asset' && typeof input.default === 'string') {
      const baseId = input.default.split('?theme=')[0];
      if (!assetById.has(baseId)) {
        errors.push(`[${toolId}] input "${input.id}" default asset "${input.default}" not in catalog`);
      }
    }
    // Color palette refs must resolve
    if (input.type === 'color' && input.palette) {
      const ref = assetById.get(input.palette);
      if (!ref) {
        errors.push(`[${toolId}] input "${input.id}" palette "${input.palette}" not in catalog`);
      } else if (ref.type !== 'palette') {
        errors.push(`[${toolId}] input "${input.id}" palette "${input.palette}" exists but isn't of type 'palette'`);
      }
    }
  }
}

// ─── Report ─────────────────────────────────────────────────────────────────

if (warnings.length) {
  console.warn(`\nWarnings (${warnings.length}):`);
  for (const w of warnings) console.warn(`  ⚠ ${w}`);
}

if (errors.length) {
  console.error(`\nErrors (${errors.length}):`);
  for (const e of errors) console.error(`  ✗ ${e}`);
  console.error(`\nCatalog validation failed.`);
  process.exit(1);
}

console.log(`\n✓ Catalog OK — ${toolManifests.size} tools, ${assetById.size} assets`);
if (warnings.length) console.log(`  (with ${warnings.length} warning${warnings.length === 1 ? '' : 's'})`);

// ─── Helpers ────────────────────────────────────────────────────────────────

function readJson(rel) {
  return JSON.parse(readFileSync(join(ROOT, rel), 'utf8'));
}

function readJsonOptional(rel) {
  const p = join(ROOT, rel);
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(readFileSync(p, 'utf8'));
  } catch (e) {
    errors.push(`[${rel}] not valid JSON: ${e.message}`);
    return null;
  }
}
