#!/usr/bin/env node
// SPDX-License-Identifier: MPL-2.0
/**
 * Catalog validator.
 *
 * Run as: npm run validate:catalog
 *
 * Verifies every tool and asset against its JSON Schema, plus structural
 * invariants the schemas can't express on their own:
 *
 *   - No duplicate tool IDs across the catalog
 *   - No duplicate asset IDs
 *   - Every tool referenced in tools/index.json has a tool.json under tools/<id>/
 *   - tools/index.json entries match their manifest (no denormalisation drift)
 *   - Every asset format URL resolves to a file that exists on disk
 *   - Every asset checksum matches the file's actual SHA-256 on disk
 *   - Every asset `depth` label matches a re-sniff of the file's own header
 *     (and no unsniffable/non-raster format carries one)
 *   - Every `canvas.*Field` names a real sub-field id in the sibling `fields`
 *     array (an unknown canvas KEY is caught by the schema, which closes the
 *     set; a broken reference can only be caught here)
 *   - Default `bindToProfile` values reference real profile fields
 *   - `palette` references on color inputs point to real palette assets
 *   - `replacedBy` on deprecated assets points to a real, non-deprecated asset
 *   - Brand-overlay declarations (`extends`) are sound: base exists in
 *     community/, community tools never declare one, overlay keeps the base id
 *
 * Index and checksums are generated by `npm run build:catalog`. This validator
 * is the guard that fails CI if either was committed stale.
 *
 * Exit code: 0 on success, 1 on any failure. Designed to run in CI before
 * publishing the catalog.
 */

import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
// Schemas declare the draft 2020-12 dialect, so use Ajv's 2020 build (the
// default export only knows draft-07 and throws on the unknown meta-schema).
import Ajv from 'ajv/dist/2020.js';
// Shared catalog-entry derivation - the single source of truth for how a manifest
// maps to a tools/index.json entry (including the `exportable` flag). Importing it
// here (rather than re-deriving) prevents the two scripts from drifting. The build
// script only writes the index when run directly, so this import has no side effect.
import { entryFromManifest } from './build-catalog-index.ts';
// Brand palette (pure data - no DOM/browser deps, safe to import in Node). Used
// below to assert no hex carries two conflicting CMYK ink values, since the PDF
// export's hex→CMYK lookup (buildCmykPaletteMap) is keyed on hex and would
// silently resolve such a clash by entry order.
import { PALETTE } from '../shells/web/src/palette.ts';
import { isThemableIconSvg, parseThemedAssetId, parseIconThemesDoc } from '../engine/src/icon-theme.ts';
// The head-vs-version asset rule and the reserved head slug (plans/97 §6a). Imported
// rather than re-stated: if the validator's idea of "this is a version asset" drifts
// from the shells', it either passes a pack that cannot resolve or fails one that can.
import { isVersionAssetId, readVersionIndex, DESIGN_VERSION_LATEST } from '../engine/src/design-version.ts';
import { parseRateCard, isRateCardError } from '../engine/src/rate-card.ts';
import { LANGS } from '../engine/src/lang.ts';
// Shared-hook-region drift guard - the writer (npm run sync:shared) and this
// check share one parser (same import-without-side-effect pattern as
// entryFromManifest above), so "what sync writes" and "what CI accepts" can't
// drift apart.
import { verifySharedRegions } from './sync-shared-hooks.ts';
// The one bit-depth sniff (checksum-assets.ts writes `depth` with it; this
// re-sniffs and compares). Same import-without-side-effect pattern as above:
// that module only rewrites the index when run directly.
import { depthForFormat } from './checksum-assets.ts';
// The frozen CLI verb list has exactly one home (shells/cli/src/args.ts); a tool id that
// collides with one is unreachable from the terminal. See §1.1 of the GA contract.
import { RESERVED_SUBCOMMANDS } from '../shells/cli/src/args.ts';
// `canvas.*Field` → sub-field-id existence. The schema closes the canvas key SET;
// this closes the reference side, which no JSON Schema can (it has to look at a
// SIBLING array). Pure module so tests can drive it without running the script.
import { canvasFieldRefErrors } from './lib/canvas-refs.ts';

// Fields tools/index.json mirrors from each manifest - kept in sync with
// scripts/build-catalog-index.ts.
const INDEX_FIELDS = ['name', 'description', 'version', 'status', 'category'];

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const PROFILE_FIELDS = new Set([
  'firstname', 'lastname', 'email', 'phone', 'city', 'country', 'headshot',
]);

// ─── Load schemas ───────────────────────────────────────────────────────────

const toolSchema = readJson('schemas/tool.schema.json');
const assetSchema = readJson('schemas/asset.schema.json');
const tokensSchema = readJson('schemas/tokens.schema.json');
const rateCardSchema = readJson('schemas/ratecard.schema.json');

const ajv = new Ajv({ allErrors: true, strict: false });
const validateTool = ajv.compile<any>(toolSchema);
const validateAsset = ajv.compile<any>(assetSchema);
const validateTokens = ajv.compile<any>(tokensSchema);
const validateRateCard = ajv.compile<any>(rateCardSchema);

// ─── Collect everything ─────────────────────────────────────────────────────

const errors: string[] = [];
const warnings: string[] = [];

const toolsDir = join(ROOT, 'tools');
const assetsIndex = readJson('catalog/assets/index.json');
const toolsIndex = readJson('catalog/tools/index.json');

// Underscore-prefixed dirs are pack infrastructure (community/_shared, the
// canonical hook-helper corpus), not tools - use-profile.ts excludes them from
// the view, and this filter keeps a stale view from failing as "missing tool.json".
const toolDirs = readdirSync(toolsDir).filter(d =>
  !d.startsWith('_') && statSync(join(toolsDir, d)).isDirectory(),
);

// ─── Tool validation ────────────────────────────────────────────────────────

const seenToolIds = new Set<string>();
// Dynamic manifest/index/asset JSON is validated against its JSON Schema at
// runtime; typing it as `any` here keeps the validator faithful without
// re-declaring every schema shape in TypeScript.
const toolManifests = new Map<string, any>(); // id → manifest

for (const dir of toolDirs) {
  const manifestPath = `tools/${dir}/tool.json`;
  const manifest = readJsonOptional(manifestPath);
  if (!manifest) {
    errors.push(`[${dir}] missing tool.json`);
    continue;
  }

  if (manifest.id !== dir) {
    errors.push(`[${dir}] manifest id "${manifest.id}" doesn't match directory name`);
  }

  if (seenToolIds.has(manifest.id)) {
    errors.push(`[${dir}] duplicate tool id "${manifest.id}"`);
  }

  // A tool id may never be a CLI subcommand word (plans/73-cli-ga-contract.md §1.1). The
  // verbs win the first positional, so `brands/acme/tools/run/` would ship, pass every
  // other check, appear in `lolly list`, and be unreachable by any spelling - with no
  // diagnostic. Post-GA the only fixes are renaming a tool id (a permanent-contract
  // violation) or changing verb dispatch (breaking), so the guard belongs here, now.
  if ((RESERVED_SUBCOMMANDS as readonly string[]).includes(manifest.id)) {
    errors.push(
      `[${dir}] tool id "${manifest.id}" is a reserved CLI subcommand word ` +
      `(${RESERVED_SUBCOMMANDS.join(', ')}) — \`lolly ${manifest.id}\` would run the verb, ` +
      `so the tool would be permanently unreachable. Rename the tool.`,
    );
  }
  seenToolIds.add(manifest.id);
  toolManifests.set(manifest.id, manifest);

  if (!validateTool(manifest)) {
    for (const err of validateTool.errors ?? []) {
      errors.push(`[${dir}] schema: ${err.instancePath || '/'} ${err.message}`);
    }
    continue;
  }

  // Required files present?
  if (!existsSync(join(ROOT, `tools/${dir}/template.html`))) {
    errors.push(`[${dir}] missing template.html`);
  }
  if (manifest.hooks && !existsSync(join(ROOT, `tools/${dir}/hooks.js`))) {
    errors.push(`[${dir}] manifest declares hooks but hooks.js is missing`);
  }

  // "New from template" files (tools/<id>/templates/<tid>.json) - the SOURCE OF TRUTH
  // for the chooser + the reserved ?template=<id> launcher. Shape gate: each file must
  // parse, carry a non-empty string `id` and `name`, a plain-object `values` seed, the
  // basename must equal `id` (so <tid>.json ↔ id stays a stable, addressable contract),
  // and ids must be unique within the dir. (Like example looks, this does NOT resolve
  // the values map's asset refs - that scope matches the historical example validator.)
  const templatesDir = join(ROOT, `tools/${dir}/templates`);
  if (existsSync(templatesDir)) {
    const seenTemplateIds = new Set<string>();
    for (const file of readdirSync(templatesDir).sort()) {
      if (!file.endsWith('.json')) continue;
      const rel = `tools/${dir}/templates/${file}`;
      let t: any;
      try { t = JSON.parse(readFileSync(join(templatesDir, file), 'utf8')); } catch (e) {
        errors.push(`[${dir}] template ${file}: invalid JSON (${(e as Error).message})`);
        continue;
      }
      if (typeof t.id !== 'string' || !t.id) { errors.push(`[${dir}] template ${file}: missing/empty "id"`); continue; }
      if (typeof t.name !== 'string' || !t.name) errors.push(`[${dir}] template ${file}: missing/empty "name"`);
      if (!t.values || typeof t.values !== 'object' || Array.isArray(t.values)) {
        errors.push(`[${dir}] template ${file}: "values" must be a plain object (the input-id → value seed)`);
      }
      const base = file.replace(/\.json$/, '');
      if (t.id !== base) errors.push(`[${dir}] template ${file}: id "${t.id}" must match the file basename "${base}" (${rel})`);
      if (seenTemplateIds.has(t.id)) errors.push(`[${dir}] template ${file}: duplicate template id "${t.id}"`);
      seenTemplateIds.add(t.id);
    }
  }

  // On-device utility conventions (privacy:'on-device'): the tool processes the
  // user's OWN content, so its output must never be watermarked or stamped with
  // provenance. An experimental tool force-watermarks its exports, which directly
  // contradicts that - so the two are mutually exclusive. (The no-metadata side is
  // enforced at runtime: the exportFile path embeds nothing, and the render path
  // skips provenance for on-device tools.)
  if (manifest.privacy === 'on-device' && manifest.status === 'experimental') {
    errors.push(`[${dir}] privacy:'on-device' tools must not be status:'experimental' (experimental force-watermarks exports, which must never happen to a user's own file)`);
  }

  // bindToProfile checks
  for (const input of manifest.inputs) {
    if (input.bindToProfile && !PROFILE_FIELDS.has(input.bindToProfile)) {
      warnings.push(`[${dir}] input "${input.id}" bindToProfile "${input.bindToProfile}" is not a known profile field`);
    }
  }

  // Free-canvas field references. `canvas` itself is a CLOSED set in the schema
  // (additionalProperties:false), so a typo'd KEY is already an Ajv error above.
  // This is the half a JSON Schema cannot express: every `canvas.*Field` VALUE has
  // to name a real sub-field id in the sibling `fields` array, because nothing at
  // runtime notices when it doesn't - the overlay's write no-ops and the compact
  // blocks URL drops the undeclared field, so a mis-named control ships as one that
  // silently does nothing. An error, not a warning: the manifest is the contract.
  for (const msg of canvasFieldRefErrors(manifest)) {
    errors.push(`[${dir}] ${msg}`);
  }

  // composes: ids must be unique within the manifest (they key {{asset <id>}} +
  // the render memo, so a duplicate silently shadows the earlier one).
  if (Array.isArray(manifest.composes)) {
    const seen = new Set<string>();
    for (const c of manifest.composes) {
      if (c && typeof c.id === 'string') {
        if (seen.has(c.id)) errors.push(`[${dir}] duplicate composes id "${c.id}"`);
        seen.add(c.id);
      }
    }
    if (manifest.composes.length && !(manifest.capabilities ?? []).includes('compose')) {
      errors.push(`[${dir}] declares "composes" but is missing the "compose" capability`);
    }
  }
}

// composes must reference real tools - a typo'd child id would only 404 at render
// time (and silently collapse the embed slot), so catch it here.
for (const [id, manifest] of toolManifests) {
  for (const c of manifest.composes ?? []) {
    if (c?.tool && !toolManifests.has(c.tool)) {
      errors.push(`[${id}] composes references unknown tool "${c.tool}"`);
    }
  }
}

// Cross-check the tool index references real tools, and that each entry matches
// its manifest. The manifest is the source of truth; the index is generated.
const indexedIds = new Set<string>();
for (const entry of toolsIndex.tools) {
  indexedIds.add(entry.id);
  const manifest = toolManifests.get(entry.id);
  if (!manifest) {
    errors.push(`tools/index.json references unknown tool "${entry.id}"`);
    continue;
  }
  for (const field of INDEX_FIELDS) {
    if (entry[field] !== manifest[field]) {
      errors.push(`tools/index.json: "${entry.id}" ${field} "${entry[field]}" ≠ manifest "${manifest[field]}" — run \`npm run build:catalog\``);
    }
  }
  // Derived flags: reuse the shared derivation so the generator and validator
  // can't drift on what they mean. `exportable` mirrors isExportable();
  // `personalized` (bindToProfile present) gates profile-aware gallery previews - 
  // both are manifest-derived, so a forgotten `npm run build:catalog` after adding
  // bindToProfile would otherwise silently leave a tool un-personalized. (icon is
  // disk-derived and intentionally not checked here; `preview` IS checked below.)
  const derived: any = entryFromManifest(manifest);
  if (entry.exportable !== derived.exportable) {
    errors.push(`tools/index.json: "${entry.id}" exportable ${entry.exportable} ≠ derived ${derived.exportable} — run \`npm run build:catalog\``);
  }
  if (!!entry.personalized !== !!derived.personalized) {
    errors.push(`tools/index.json: "${entry.id}" personalized ${!!entry.personalized} ≠ derived ${!!derived.personalized} — run \`npm run build:catalog\``);
  }
  // Preview path is disk-derived: build-previews rasterises expensive-to-paint SVGs
  // (huge paths / thousands of dots) to .png, so entryFromManifest picks the extension
  // that actually exists on disk. A stale index - pointing at .svg when the committed
  // preview is .png - renders as a broken image in the gallery. Flag the drift, but
  // only when the derived path points at a file that exists: a fresh checkout with no
  // generated previews yet is fine (the gallery tolerates an absent preview), so we
  // don't force a regeneration there.
  if (
    entry.preview !== derived.preview &&
    typeof derived.preview === 'string' &&
    existsSync(join(ROOT, derived.preview.replace(/^\//, '')))
  ) {
    errors.push(`tools/index.json: "${entry.id}" preview ${entry.preview} ≠ derived ${derived.preview} — run \`npm run build:catalog\` (after \`npm run previews\`)`);
  }
  // "New from template" metadata. THE WHOLE-POINT INVARIANT: the synced index must carry
  // template METADATA ONLY - never the heavy `values` seed (that's fetched on demand). A
  // stray `values` key here would re-bloat every client's index, defeating the lazy-file
  // storage entirely.
  for (const tmpl of (entry.templates ?? []) as Array<Record<string, unknown>>) {
    if (tmpl && typeof tmpl === 'object' && 'values' in tmpl) {
      errors.push(`tools/index.json: "${entry.id}" template "${tmpl.id}" carries "values" — the index must be metadata-only (values live in tools/<id>/templates/<tid>.json); run \`npm run build:catalog\``);
    }
  }
  // Drift guard: entryFromManifest re-scans tools/<id>/templates/*.json, so a forgotten
  // build:catalog after adding/editing/removing a template file fails CI. Compare the
  // (deterministic) derived metadata against the committed index copy.
  if (JSON.stringify(entry.templates ?? null) !== JSON.stringify(derived.templates ?? null)) {
    errors.push(`tools/index.json: "${entry.id}" templates drifted from tools/${entry.id}/templates/*.json — run \`npm run build:catalog\``);
  }
}
// Every tool with a manifest must appear in the index.
for (const id of toolManifests.keys()) {
  if (!indexedIds.has(id)) {
    errors.push(`tools/index.json is missing tool "${id}" — run \`npm run build:catalog\``);
  }
}

// ─── Pre-rendered look bundle (first-paint guard) ───────────────────────────
// The gallery's example carousel + featured hero are bundle-FIRST: renderFeaturedVariant
// (shells/web/src/lib/featured-render.ts) asks bundledLook() for a committed data-URI out
// of catalog/previews/bundle.json BEFORE it will touch the engine, and only falls through
// to a LIVE off-screen render when a look is missing from the bundle or its sig no longer
// matches. That fallback is SILENT - the tile still fills, just by mounting a runtime - so
// editing a look's values in a manifest can quietly put an engine render back on the
// first-paint path. This guards the invariant that a pre-rendered look stays pre-rendered.
//
// The sig is one contract across three files and all three must agree:
//   build-preview-bundle.ts  JSON.stringify(looks[i].values ?? {})   ← written here
//   featured-render.ts:135   JSON.stringify(values)                  ← compared on the client
//   this check                                                        ← keeps them honest
//
// Severity split mirrors the tolerance the preview-path check above already applies:
// a STALE sig is an error (a demonstrable manifest↔bundle drift, always fixable by
// regenerating), while an ABSENT look is only a warning - build-previews is best-effort
// by design ("a look that fails just isn't bundled, and the gallery live-renders it as
// before"), so a missing entry must not turn a documented graceful degrade into a red
// build. No bundle at all = a checkout that hasn't generated previews: skip entirely.
const previewBundle = readJsonOptional('catalog/previews/bundle.json');
if (previewBundle) {
  for (const [id, manifest] of toolManifests) {
    // Canonical source is `examples`; `featured.variants` is the pre-`examples` alias.
    // Order MUST match build-preview-bundle.ts's looksOf() so the `<id>:<i>` keys line up.
    const looks: any[] = manifest.examples ?? manifest.featured?.variants ?? [];
    looks.forEach((look: any, i: number) => {
      const entry = previewBundle[`${id}:${i}`];
      const sig = JSON.stringify(look?.values ?? {});
      if (!entry) {
        warnings.push(`[${id}] example look ${i} is absent from catalog/previews/bundle.json — the gallery will LIVE-RENDER it on first paint; run \`npm run previews\` then \`npm run build:catalog\``);
      } else if (entry.sig !== sig) {
        errors.push(`[${id}] example look ${i} bundle sig is stale — the gallery will silently fall back to a live render on first paint; run \`npm run previews\` then \`npm run build:catalog\``);
      }
    });
  }
}

// ─── Canonical input registry (soft check) ──────────────────────────────────
// Tools SHOULD reuse canonical input ids + constraints so the /pro batch grid
// collapses them into one bulk-writable column. Divergence is a warning, not an
// error: a tool may legitimately need different constraints, but it then forfeits
// the shared column. Keeps schemas/canonical-inputs.json honest as tools evolve.
const canonicalInputs = readJsonOptional('schemas/canonical-inputs.json')?.inputs ?? {};
for (const [toolId, manifest] of toolManifests) {
  for (const input of manifest.inputs) {
    const canon = canonicalInputs[input.id];
    if (!canon) continue;
    if (input.type !== canon.type) {
      warnings.push(`[${toolId}] input "${input.id}" type "${input.type}" diverges from canonical "${canon.type}" — won't share the /pro column (schemas/canonical-inputs.json)`);
      continue; // type mismatch already breaks the column; constraint checks are moot
    }
    const numKeys = canon.type === 'number' ? ['min', 'max', 'step'] : [];
    for (const k of numKeys) {
      if (canon[k] !== undefined && (input[k] ?? null) !== canon[k]) {
        warnings.push(`[${toolId}] input "${input.id}" ${k}=${input[k] ?? 'unset'} diverges from canonical ${k}=${canon[k]} — breaks bulk-fill in /pro (schemas/canonical-inputs.json)`);
      }
    }
    if (canon.type === 'select' && Array.isArray(canon.options)) {
      const norm = (opts: any): string => (opts ?? []).map((o: any) => (o && typeof o === 'object' ? o.value : o)).join('|');
      if (norm(input.options) !== norm(canon.options)) {
        warnings.push(`[${toolId}] input "${input.id}" options diverge from canonical — breaks bulk-fill in /pro (schemas/canonical-inputs.json)`);
      }
    }
  }
}

// ─── i18n sidecars (plans/38-localize.md §7) ──────────────────────────────────
// tools/<id>/i18n/<lang>.json is a flat, dotted-path overlay onto the
// manifest's own user-facing strings (engine/src/loader.ts's
// applyManifestI18n applies it at load time; build-catalog-index.ts folds
// name/description/featured.blurb into the catalog index). Every key must
// resolve to a real manifest field - an orphaned key (after a manifest
// refactor renamed/removed an input) would silently translate nothing.
const SIDECAR_LANGS = new Set(LANGS.filter(l => l !== 'en'));
for (const [toolId, manifest] of toolManifests) {
  const i18nDir = join(ROOT, `tools/${toolId}/i18n`);
  if (!existsSync(i18nDir)) continue;
  for (const file of readdirSync(i18nDir)) {
    if (!file.endsWith('.json')) continue;
    const lang = file.replace(/\.json$/, '');
    if (!SIDECAR_LANGS.has(lang as any)) {
      errors.push(`[${toolId}] i18n/${file}: "${lang}" is not a supported language (${[...SIDECAR_LANGS].join(', ')})`);
      continue;
    }
    const overlay = readJsonOptional(`tools/${toolId}/i18n/${file}`);
    if (!overlay) continue; // readJsonOptional already recorded a parse error
    if (typeof overlay !== 'object' || Array.isArray(overlay)) {
      errors.push(`[${toolId}] i18n/${file} must be a flat JSON object`);
      continue;
    }
    for (const [key, value] of Object.entries(overlay)) {
      if (typeof value !== 'string') {
        errors.push(`[${toolId}] i18n/${file}: "${key}" value must be a string`);
        continue;
      }
      const reason = unresolvedSidecarKey(manifest, key);
      if (reason) errors.push(`[${toolId}] i18n/${file}: key "${key}" ${reason}`);
    }
  }
}

// ─── Palette consistency ────────────────────────────────────────────────────
// The CMYK-aware PDF export builds a hex→CMYK lookup (buildCmykPaletteMap in
// shells/web/src/bridge/export.js) keyed on each swatch's hex. The brand palette
// deliberately repeats hexes (e.g. Pine/Black/White appear as ramp endpoints),
// which is fine - but only as long as the repeats agree on their ink values
// (null = "unspecified" is always compatible). If two entries with the SAME hex
// declared DIFFERENT non-null CMYK, the lookup's result would depend purely on
// array order - a silent, order-dependent ink mismatch. Catch that here.
{
  const cmykByHex = new Map<string, { cmyk: readonly [number, number, number, number]; label: string }>(); // normalised hex → { cmyk, label }
  for (const { hex, cmyk, label } of PALETTE) {
    if (!cmyk) continue; // null = unspecified, never conflicts
    const key = String(hex).replace('#', '').toLowerCase();
    const prev = cmykByHex.get(key);
    if (prev && JSON.stringify(prev.cmyk) !== JSON.stringify(cmyk)) {
      errors.push(`palette: hex "${hex}" has conflicting CMYK — "${prev.label}" ${JSON.stringify(prev.cmyk)} vs "${label}" ${JSON.stringify(cmyk)} (the PDF export's hex→CMYK lookup would resolve this by entry order)`);
    } else if (!prev) {
      cmykByHex.set(key, { cmyk, label });
    }
  }
}

// ─── Asset validation ───────────────────────────────────────────────────────

const seenAssetIds = new Set<string>();
const assetById = new Map<string, any>();
const iconThemePalettes: { assetId: string; themes: ReturnType<typeof parseIconThemesDoc> }[] = [];     // { assetId, themes } per icon-themes palette
const themableIconDefaults: { assetId: string; c1: string; c2: string }[] = [];  // { assetId, c1, c2 } per themable icon

for (const asset of assetsIndex.assets) {
  if (seenAssetIds.has(asset.id)) {
    errors.push(`duplicate asset id "${asset.id}"`);
  }
  seenAssetIds.add(asset.id);
  assetById.set(asset.id, asset);

  if (!validateAsset(asset)) {
    for (const err of validateAsset.errors ?? []) {
      errors.push(`[asset ${(asset as { id: string }).id}] schema: ${err.instancePath || '/'} ${err.message}`);
    }
    continue;
  }

  // Format files exist on disk, and their checksums match the actual bytes?
  const formatLists = [asset.formats, ...Object.values(asset.locales ?? {})];
  for (const formats of formatLists) {
    for (const fmt of formats ?? []) {
      const absPath = join(ROOT, fmt.url.replace(/^\//, ''));
      if (!existsSync(absPath)) {
        errors.push(`[asset ${asset.id}] format "${fmt.format}" url "${fmt.url}" does not exist on disk`);
        continue;
      }
      const bytes = readFileSync(absPath);
      if (fmt.checksum === 'sha256-PLACEHOLDER') {
        warnings.push(`[asset ${asset.id}] format "${fmt.format}" has placeholder checksum — run \`npm run build:catalog\``);
      } else {
        const actual = `sha256-${createHash('sha256').update(bytes).digest('base64')}`;
        if (fmt.checksum !== actual) {
          errors.push(`[asset ${asset.id}] format "${fmt.format}" checksum stale — run \`npm run build:catalog\``);
        }
      }

      // Depth label matches a re-sniff of the actual bytes, in BOTH directions.
      // `depth` is generated, never hand-authored (plans/61-deeprichpixels.md §10
      // item 6): a present-but-wrong label would be exactly the "bits the
      // pipeline did not produce" the plan forbids, and a missing label on a
      // sniffable raster is a stale index. Same function the writer uses, so
      // the two can only disagree if the index is out of date.
      const expectedDepth = await depthForFormat(asset.type, bytes);
      if (expectedDepth == null && fmt.depth !== undefined) {
        errors.push(`[asset ${asset.id}] format "${fmt.format}" declares depth ${fmt.depth} but its bytes state no depth (not a raster, or an unsniffable container) — run \`npm run build:catalog\``);
      } else if (expectedDepth != null && fmt.depth !== expectedDepth) {
        errors.push(`[asset ${asset.id}] format "${fmt.format}" depth ${fmt.depth ?? '(absent)'} does not match the file's ${expectedDepth}-bit header — run \`npm run build:catalog\``);
      }

      // Tokens assets carry a DTCG document - validate its structure too.
      if (asset.type === 'tokens' && fmt.format === 'json') {
        let doc;
        try { doc = JSON.parse(bytes.toString('utf8')); } catch {
          errors.push(`[asset ${asset.id}] tokens doc "${fmt.url}" is not valid JSON`);
          continue;
        }
        if (!validateTokens(doc)) {
          for (const err of validateTokens.errors ?? []) {
            errors.push(`[asset ${asset.id}] tokens: ${err.instancePath || '/'} ${err.message}`);
          }
        }
      }

      // A brand-shipped house rate card (Phase 5). Schema-valid is not the same as
      // computable - run it through parseRateCard, the same reader the drop path
      // uses (the parseIconThemesDoc lesson, below).
      if (asset.type === 'ratecard' && fmt.format === 'json') {
        const digest = createHash('sha256').update(bytes).digest('hex').slice(0, 16);
        const card = parseRateCard(bytes, digest, validateRateCard);
        if (isRateCardError(card)) {
          errors.push(`[asset ${asset.id}] rate card "${fmt.url}" refused: ${card.error}`);
        } else if (!card.confidential) {
          // Phase 5: a brand/catalog-shipped house card ships trade rates to every
          // brand user. It MUST be confidential:true so `canShowMoney` can only ever
          // reveal it by the explicit per-device action, never automatically off a
          // link. A non-confidential catalog card would leak the rates.
          errors.push(`[asset ${asset.id}] rate card "${fmt.url}" is a catalog asset but is not confidential:true — a shipped house card must set confidential:true so its rates are protected`);
        }
      }

      // Icon-themes palettes: the colour pairings the shells offer for themable
      // icons. parseIconThemesDoc is the runtime's reader - any entry it drops
      // (bad id charset, unusable colour) would silently vanish from the UI, so
      // dropping is an authoring error here.
      if (asset.type === 'palette' && asset.tags?.includes('icon-themes') && fmt.format === 'json') {
        let doc;
        try { doc = JSON.parse(bytes.toString('utf8')); } catch {
          errors.push(`[asset ${asset.id}] icon-themes doc "${fmt.url}" is not valid JSON`);
          continue;
        }
        const themes = parseIconThemesDoc(doc);
        const declared = Array.isArray(doc?.themes) ? doc.themes.length : 0;
        if (!declared) {
          errors.push(`[asset ${asset.id}] icon-themes doc has no themes[] array`);
        } else if (themes.length !== declared) {
          errors.push(`[asset ${asset.id}] icon-themes doc has ${declared - themes.length} entr${declared - themes.length === 1 ? 'y' : 'ies'} the runtime would drop (theme ids must be [a-z0-9-], c1/c2 must be simple CSS colours)`);
        }
        const ids = themes.map(t => t.id);
        if (new Set(ids).size !== ids.length) {
          errors.push(`[asset ${asset.id}] icon-themes doc has duplicate theme ids`);
        }
        iconThemePalettes.push({ assetId: asset.id, themes });
      }

      // Themable two-colour icons (tag "themable"): the shells' theme baking is
      // a string rewrite, so the SVG must follow the exact contract the engine's
      // isThemableIconSvg/applyIconTheme expect - one default
      // <defs><style>.c1{fill:…}.c2{fill:…}</style></defs> block, shape classes
      // limited to c1/c2, and no stray style/stroke attributes.
      if (asset.tags?.includes('themable') && fmt.format === 'svg') {
        const svg = bytes.toString('utf8');
        const styleBlocks = svg.match(/<style>/g) ?? [];
        if (!isThemableIconSvg(svg)) {
          errors.push(`[asset ${asset.id}] themable icon missing the default .c1/.c2 style block`);
        } else if (styleBlocks.length !== 1) {
          errors.push(`[asset ${asset.id}] themable icon must contain exactly one <style> block`);
        } else {
          const fills = svg.match(/\.c1\{fill:([^}]*)\}\.c2\{fill:([^}]*)\}/);
          themableIconDefaults.push({ assetId: asset.id, c1: fills![1]!, c2: fills![2]! });
        }
        const body = svg.replace(/<defs><style>[\s\S]*?<\/style><\/defs>/, '');
        const badClass = [...body.matchAll(/class="([^"]*)"/g)].find(m => m[1] !== 'c1' && m[1] !== 'c2');
        if (badClass) errors.push(`[asset ${asset.id}] themable icon has a class other than c1/c2: "${badClass[1]}"`);
        if (/style="/.test(body)) errors.push(`[asset ${asset.id}] themable icon has an inline style attribute`);
        if (/\bstroke[-\w]*\s*[:=]/.test(body)) errors.push(`[asset ${asset.id}] themable icon has stroke styling (fills only)`);
      }
    }
  }
}

// The first icon-themes pairing is the DEFAULT the picker maps to a plain
// (suffix-less) id - it only reads true if it matches the fills actually baked
// into the icons. Reordering the palette without recolouring the icons would
// silently mislabel every default pick.
for (const pal of iconThemePalettes) {
  const first = pal.themes[0];
  if (!first) continue;
  for (const icon of themableIconDefaults) {
    if (icon.c1.toLowerCase() !== first.c1.toLowerCase() || icon.c2.toLowerCase() !== first.c2.toLowerCase()) {
      errors.push(`[asset ${icon.assetId}] default fills (${icon.c1}/${icon.c2}) don't match the first icon-themes pairing "${first.id}" (${first.c1}/${first.c2}) in ${pal.assetId}`);
    }
  }
}

// Resolve replacedBy
for (const asset of assetsIndex.assets) {
  if (asset.deprecated && asset.replacedBy) {
    const replacement = assetById.get(asset.replacedBy);
    if (!replacement) {
      errors.push(`[asset ${asset.id}] replacedBy "${asset.replacedBy}" doesn't exist`);
    } else if (replacement.deprecated) {
      errors.push(`[asset ${asset.id}] replacedBy "${asset.replacedBy}" is also deprecated`);
    }
  }
}

// Default favourites (seeded on first run) must each reference a real asset - a typo'd
// id would silently seed a favourite that never resolves to a tile.
if (assetsIndex.defaultFavourites !== undefined) {
  if (!Array.isArray(assetsIndex.defaultFavourites)) {
    errors.push(`assets/index.json: "defaultFavourites" must be an array of asset ids`);
  } else {
    for (const id of assetsIndex.defaultFavourites) {
      if (typeof id !== 'string' || !assetById.has(id)) {
        errors.push(`assets/index.json: defaultFavourites entry "${id}" is not a known asset id`);
      }
    }
  }
}

// ─── Design-system version pins (plans/97 §6a) ──────────────────────────────

// The version assets this catalog ships, by slug. A tokens asset is a VERSION when
// another tokens asset is its proper ancestor (`user/tokens/brand/jupiter` under
// `user/tokens/brand`) - the same descendant rule the shells' discovery applies, so
// the validator and the runtime cannot disagree about what is a head and what is a
// version. Only a single extra segment counts: a deeper id is not addressable by a
// slug, so it is not a version anything could pin to.
const tokensAssets = assetsIndex.assets.filter((a: { type?: string }) => a.type === 'tokens');
const tokensAssetIds = tokensAssets.map((a: { id: string }) => a.id);
const shippedVersionSlugs = new Set<string>();
for (const id of tokensAssetIds) {
  for (const head of tokensAssetIds) {
    if (head === id || !isVersionAssetId(id, head)) continue;
    const slug = id.slice(head.length + 1);
    if (!slug.includes('/')) shippedVersionSlugs.add(slug);
  }
}

// …and the slugs the HEAD document's ledger actually lists. This is the set that
// decides a pin at runtime: `resolveDesignVersion` reads `readVersionIndex(head)`
// and nothing consults the asset list at all (shells/cli/src/bridge.ts,
// shells/web/src/bridge/tokens.ts). A pack can drift either way - an asset with
// no ledger entry, or a ledger entry with no asset - and both make a pin fall
// silently through the ladder, which is precisely what this section exists to
// stop. So a slug has to be in BOTH.
const ledgerVersionSlugs = new Set<string>();
for (const head of tokensAssets) {
  // A head, not a version of another one.
  if (tokensAssetIds.some((other: string) => other !== head.id && isVersionAssetId(head.id, other))) continue;
  const url: string | undefined = head.formats?.[0]?.url;
  if (!url) continue;
  try {
    const doc: unknown = JSON.parse(readFileSync(join(ROOT, url.replace(/^\//, '')), 'utf8'));
    for (const entry of readVersionIndex(doc).versions) ledgerVersionSlugs.add(entry.slug);
  } catch { /* an unreadable/absent tokens file is already an error elsewhere */ }
}

for (const slug of shippedVersionSlugs) {
  if (!ledgerVersionSlugs.has(slug)) {
    errors.push(
      `assets/index.json: design-system version "${slug}" ships a tokens asset but the head ` +
      `document's version ledger does not list it — nothing can resolve it, since every shell ` +
      `reads the ledger, not the asset list`,
    );
  }
}
for (const slug of ledgerVersionSlugs) {
  if (!shippedVersionSlugs.has(slug)) {
    errors.push(
      `assets/index.json: the head document's version ledger lists "${slug}" but this catalog ` +
      `ships no tokens asset for it — a tool resolving to that version would render the edit head`,
    );
  }
}
/** What a `designVersion` pin can actually resolve to in this pack. */
const resolvableVersionSlugs = new Set([...shippedVersionSlugs].filter(s => ledgerVersionSlugs.has(s)));

// A tool's `designVersion` is a resolution hint, never a load gate (engine/src/
// loader.ts deliberately ignores it - an unresolvable pin falls through the ladder
// so the tool still draws). That leniency is exactly why a pack has to be checked
// here: at runtime a typo'd slug is invisible, and the tool quietly renders against
// a different design system than its author pinned it to.
for (const [toolId, manifest] of toolManifests) {
  const pin: unknown = manifest.designVersion;
  if (typeof pin !== 'string' || !pin || pin === DESIGN_VERSION_LATEST) continue;
  if (!resolvableVersionSlugs.size) {
    // A community tool pinned for another pack must not fail every pack that does
    // not ship versions - that would make one brand's pin everyone else's error.
    warnings.push(
      `[${toolId}] designVersion "${pin}" but this catalog ships no design-system versions — ` +
      `the pin falls through to the active version, then to the edit head`,
    );
    continue;
  }
  if (!resolvableVersionSlugs.has(pin)) {
    errors.push(
      `[${toolId}] designVersion "${pin}" names no version this catalog can resolve ` +
      `(available: ${[...resolvableVersionSlugs].sort().join(', ')}) — publish that version into the ` +
      `pack, fix the slug, or drop the pin so the tool follows the active version`,
    );
  }
}

// ─── Cross-references: tools → assets ───────────────────────────────────────

for (const [toolId, manifest] of toolManifests) {
  for (const input of manifest.inputs) {
    // Default asset refs must resolve. A default may carry an icon theme
    // suffix (`<id>?theme=<t>`) - parse it exactly the way the runtime does,
    // so anything that validates here also resolves at mount.
    if (input.type === 'asset' && typeof input.default === 'string') {
      const { baseId, theme } = parseThemedAssetId(input.default);
      if (baseId.includes('?')) {
        errors.push(`[${toolId}] input "${input.id}" default asset "${input.default}" has a malformed ?theme= suffix (theme ids are [a-z0-9-])`);
      } else if (!assetById.has(baseId)) {
        errors.push(`[${toolId}] input "${input.id}" default asset "${input.default}" not in catalog`);
      } else if (theme && !iconThemePalettes.some(p => p.themes.some(t => t.id === theme))) {
        errors.push(`[${toolId}] input "${input.id}" default asset theme "${theme}" not in any icon-themes palette`);
      }
    }
    // Color palette refs must resolve
    if (input.type === 'color' && input.palette) {
      const ref = assetById.get(input.palette);
      if (!ref) {
        errors.push(`[${toolId}] input "${input.id}" palette "${input.palette}" not in catalog`);
      } else if (ref.type !== 'palette') {
        errors.push(`[${toolId}] input "${input.id}" palette "${input.palette}" exists but isn't of type 'palette'`);
      }
    }
  }
}

// ─── Example looks (examples / deprecated featured.variants) ────────────────
// A look's `values` seed the gallery preview render exactly like batch-row
// values: renderRowToBlob spreads them into createRuntime's initialState, which
// resolves them BY INPUT ID ONLY (engine/src/inputs.ts resolveInitialValue). A
// key that matches nothing - or only a urlKey, which is URL-mode transport, not
// runtime state - silently renders the tool's DEFAULT look instead of the
// authored one, so both are errors. Asset refs get the same resolve-at-mount
// guarantee as input defaults: a typo'd id would only 404 at gallery paint.
{
  // Formats the gallery strip can show as an <img> - mirrors displayFormatOf/
  // rasterFormatOf in shells/web/src/lib/featured-render.ts.
  const DISPLAYABLE = new Set(['svg', 'png', 'jpg', 'jpeg', 'webp']);
  // A look whose asset value can't resolve at gallery-render time. Catalog ids
  // ride in a ref object (the URL-mode shape - assetRefId in engine/src/runtime.ts
  // ignores bare strings), optionally with a ?theme= suffix; http(s)/data refs
  // (e.g. canonical tool-embed URLs rendered via compose) resolve at runtime and
  // can't be checked here.
  const checkAssetValue = (toolId: string, at: string, spec: any, value: unknown): void => {
    if (spec.type !== 'asset' || value == null) return;
    if (typeof value === 'string') {
      errors.push(`[${toolId}] ${at}: asset input "${spec.id}" value ${JSON.stringify(value)} is a bare string — the runtime only resolves ref objects; use {"source":"library","id":"<asset-id>","_unresolved":true}`);
      return;
    }
    const id = (value as { id?: unknown })?.id;
    if (typeof id !== 'string' || /^(https?|data|blob):/.test(id)) return; // non-ref / runtime-fetched
    const { baseId, theme } = parseThemedAssetId(id);
    if (baseId.includes('?')) {
      errors.push(`[${toolId}] ${at}: asset "${id}" (input "${spec.id}") has a malformed ?theme= suffix (theme ids are [a-z0-9-])`);
    } else if (!assetById.has(baseId)) {
      errors.push(`[${toolId}] ${at}: asset "${id}" (input "${spec.id}") not in catalog`);
    } else if (theme && !iconThemePalettes.some(p => p.themes.some(t => t.id === theme))) {
      errors.push(`[${toolId}] ${at}: asset theme "${theme}" (input "${spec.id}") not in any icon-themes palette`);
    }
  };

  for (const [toolId, manifest] of toolManifests) {
    const sources: Array<[string, any[]]> = [];
    if (Array.isArray(manifest.examples)) sources.push(['examples', manifest.examples]);
    if (Array.isArray(manifest.featured?.variants)) sources.push(['featured.variants', manifest.featured.variants]);
    if (!sources.length) continue;

    // A look on a tool with no displayable format can never render in the strip - 
    // renderFeaturedVariant throws and the tile silently keeps its static preview.
    const formats: string[] = manifest.render?.formats ?? [];
    if (!formats.some(f => DISPLAYABLE.has(f))) {
      warnings.push(`[${toolId}] declares example looks but no gallery-displayable format (svg/png/jpg/jpeg/webp) — the preview strip can never render them`);
    }

    const inputById = new Map<string, any>((manifest.inputs ?? []).map((i: any) => [i.id, i]));
    const idByUrlKey = new Map<string, string>();
    for (const i of manifest.inputs ?? []) {
      if (typeof i.urlKey === 'string') idByUrlKey.set(i.urlKey, i.id);
    }

    for (const [src, looks] of sources) {
      // Advisory, like the canonical-input checks: each look is a live off-screen
      // engine render on the gallery, so an oversized strip is a perf smell, not
      // a correctness break.
      if (looks.length > 8) {
        warnings.push(`[${toolId}] ${src} has ${looks.length} looks — each is a live gallery render; keep it to 8 or fewer`);
      }
      looks.forEach((look: any, i: number) => {
        const at = `${src}[${i}]`;
        if (look?.label !== undefined && (typeof look.label !== 'string' || !look.label.trim())) {
          errors.push(`[${toolId}] ${at}: label must be a non-empty string`);
        }
        const values = look?.values;
        if (!values || typeof values !== 'object' || Array.isArray(values)) return; // shape is schema-enforced
        for (const [key, value] of Object.entries(values)) {
          const input = inputById.get(key);
          if (!input) {
            // width/height are honoured by featured-render as per-example preview
            // dimensions even when the tool declares no such inputs.
            if (key === 'width' || key === 'height') continue;
            const idForUrlKey = idByUrlKey.get(key);
            errors.push(idForUrlKey
              ? `[${toolId}] ${at}: values key "${key}" is input "${idForUrlKey}"'s urlKey — example values seed the runtime by input id (urlKey is URL-mode transport only)`
              : `[${toolId}] ${at}: values key "${key}" is not a declared input id`);
            continue;
          }
          checkAssetValue(toolId, at, input, value);
          // Blocks rows: keys must be declared field ids (an unknown key is as
          // silently inert as an unknown top-level key); asset-typed fields get
          // the same ref resolution check.
          if (input.type === 'blocks' && Array.isArray(value)) {
            const fieldById = new Map<string, any>((input.fields ?? []).map((f: any) => [f.id, f]));
            value.forEach((row: any, r: number) => {
              if (!row || typeof row !== 'object' || Array.isArray(row)) {
                errors.push(`[${toolId}] ${at}: values.${key}[${r}] must be an object of field values`);
                return;
              }
              for (const [fk, fv] of Object.entries(row)) {
                const field = fieldById.get(fk);
                if (!field) {
                  errors.push(`[${toolId}] ${at}: values.${key}[${r}] key "${fk}" is not a declared field of blocks input "${key}"`);
                  continue;
                }
                checkAssetValue(toolId, `${at} values.${key}[${r}]`, field, fv);
              }
            });
          }
        }
      });
    }
  }
}

// ─── Brand overlay declarations (extends) ───────────────────────────────────
// A brand-pack tool may declare `"extends": "community"` - scripts/use-profile.ts
// then composes its view dir per-file from community/<id>/ + the overlay
// (overlay wins, `extends` stripped from the composed tool.json). The composed
// RESULT is already validated as a normal tool by the per-tool checks above,
// which run against the tools/ VIEW. What the view can't tell us is whether the
// DECLARATIONS in the pack sources are sound - so walk the real packs here
// (community/ + brands/*/tools/, same as the shared-hooks guard below), even
// for tools outside the active profile:
//   - community tools must never declare an overlay (they are the bases)
//   - the only supported base pack in v1 is "community"
//   - the overlay dir must keep the base's id (ids are permanent contracts)
//   - the base community/<id>/tool.json must exist (missing base = the profile
//     build fails loudly; catch the authoring error here too, before a switch)
{
  const packToolDirs = (root: string): string[] => {
    const abs = join(ROOT, root);
    if (!existsSync(abs)) return []; // private pack not mounted - nothing to check
    return readdirSync(abs).filter((d) =>
      !d.startsWith('.') && !d.startsWith('_') && d !== 'node_modules' &&
      statSync(join(abs, d)).isDirectory());
  };

  for (const dir of packToolDirs('community')) {
    const manifest = readJsonOptional(`community/${dir}/tool.json`);
    if (manifest && manifest.extends !== undefined) {
      errors.push(`[community/${dir}] declares "extends" — community tools are overlay bases; only a brand pack may declare an overlay`);
    }
  }

  const brandsRoot = join(ROOT, 'brands');
  const brands = existsSync(brandsRoot)
    ? readdirSync(brandsRoot).filter((b) =>
        !b.startsWith('.') && statSync(join(brandsRoot, b)).isDirectory() &&
        existsSync(join(brandsRoot, b, 'tools')))
    : [];
  for (const brand of brands) {
    for (const dir of packToolDirs(`brands/${brand}/tools`)) {
      const rel = `brands/${brand}/tools/${dir}`;
      const manifest = readJsonOptional(`${rel}/tool.json`);
      if (!manifest || manifest.extends === undefined) continue;
      if (manifest.extends !== 'community') {
        errors.push(`[${rel}] "extends": ${JSON.stringify(manifest.extends)} — v1 supports only "community" as the base pack`);
        continue;
      }
      if (manifest.id !== dir) {
        errors.push(`[${rel}] overlay id "${manifest.id}" doesn't match its directory name — an overlay and its base share the same tool id`);
      }
      if (!existsSync(join(ROOT, 'community', dir, 'tool.json'))) {
        errors.push(`[${rel}] extends "community" but community/${dir}/tool.json does not exist — the overlay's base is missing (the profile build would fail loudly on this)`);
      }
    }
  }
}

// ─── Shared hook regions (community/_shared) ────────────────────────────────
// Tool hooks.js ship self-contained (no imports), so shared helper blocks are
// byte-copies of community/_shared/*.js regions between `lolly:shared` markers,
// maintained by `npm run sync:shared`. A hand-edited consumer region (or a
// canonical edit that skipped the sync) would silently re-fork the corpus the
// same way the old copy-paste did - fail closed here, exactly like the
// tools/index.json drift check above. This walks the real pack sources
// (community/ + brands/*/tools/), not the tools/ view, so even tools outside
// the active profile are guarded.
for (const err of verifySharedRegions()) {
  errors.push(`shared-hooks: ${err}`);
}

// ─── Report ─────────────────────────────────────────────────────────────────

if (warnings.length) {
  console.warn(`\nWarnings (${warnings.length}):`);
  for (const w of warnings) console.warn(`  ⚠ ${w}`);
}

if (errors.length) {
  console.error(`\nErrors (${errors.length}):`);
  for (const e of errors) console.error(`  ✗ ${e}`);
  console.error(`\nCatalog validation failed.`);
  process.exit(1);
}

console.log(`\n✓ Catalog OK — ${toolManifests.size} tools, ${assetById.size} assets`);
if (warnings.length) console.log(`  (with ${warnings.length} warning${warnings.length === 1 ? '' : 's'})`);

// ─── Helpers ────────────────────────────────────────────────────────────────

function readJson(rel: string): any {
  return JSON.parse(readFileSync(join(ROOT, rel), 'utf8'));
}

// Mirrors the traversal engine/src/loader.ts's applyManifestI18n uses to apply
// a sidecar overlay - but reports WHY a key doesn't resolve instead of
// silently skipping it (silent-skip is the right runtime behaviour; a build-time
// validator's job is to catch the authoring mistake that would cause it).
function unresolvedSidecarKey(manifest: any, key: string): string | null {
  if (key === 'name' || key === 'description' || key === 'a11yLabel') return null;
  if (key === 'featured.blurb') return manifest.featured ? null : 'references featured.blurb but the manifest has no featured block';
  if (key.startsWith('guide.')) return unresolvedGuideKey(manifest, key.slice('guide.'.length));

  const m = /^inputs\.([^.]+)\.(.+)$/.exec(key);
  if (!m) return 'does not match any known overlay path (name, description, a11yLabel, featured.blurb, guide.…, inputs.<id>.…)';
  const [, inputId, rest] = m as unknown as [string, string, string];
  const input = (manifest.inputs ?? []).find((i: any) => i.id === inputId);
  if (!input) return `references unknown input "${inputId}"`;

  if (['label', 'help', 'notice', 'placeholder', 'section', 'suffix'].includes(rest)) return null;
  // (.*) not (.+): mirrors applyManifestI18n - an option's value may be ''.
  const optMatch = /^options\.(.*)$/.exec(rest);
  if (optMatch) {
    const found = (input.options ?? []).some((o: any) => o.value === optMatch[1]);
    return found ? null : `references unknown option "${optMatch[1]}" on input "${inputId}"`;
  }
  if (rest === 'addMenu.label') return input.addMenu ? null : `input "${inputId}" has no addMenu`;
  const fieldMatch = /^fields\.([^.]+)\.(.+)$/.exec(rest);
  if (fieldMatch) {
    const [, fieldId, fieldRest] = fieldMatch as unknown as [string, string, string];
    const field = (input.fields ?? []).find((f: any) => f.id === fieldId);
    if (!field) return `references unknown field "${fieldId}" on input "${inputId}"`;
    if (['label', 'help', 'placeholder'].includes(fieldRest)) return null;
    const fieldOptMatch = /^options\.(.*)$/.exec(fieldRest);
    if (fieldOptMatch) {
      const found = (field.options ?? []).some((o: any) => o.value === fieldOptMatch[1]);
      return found ? null : `references unknown option "${fieldOptMatch[1]}" on field "${fieldId}" (input "${inputId}")`;
    }
  }
  return 'does not match any known overlay path';
}

// Mirrors applyGuideI18n in engine/src/loader.ts - a step index past the end of
// the track resolves to nothing at runtime, so it's an authoring error here.
function unresolvedGuideKey(manifest: any, rest: string): string | null {
  const guide = manifest.guide;
  if (!guide) return 'references guide.* but the manifest has no guide block';
  if (rest === 'title') return null;

  const m = /^tracks\.([^.]+)\.(.+)$/.exec(rest);
  if (!m) return 'does not match any known guide path (guide.title, guide.tracks.<id>.label/.note/.steps.<index>)';
  const [, trackId, field] = m as unknown as [string, string, string];
  const track = (guide.tracks ?? []).find((t: any) => t.id === trackId);
  if (!track) return `references unknown guide track "${trackId}"`;
  if (field === 'label' || field === 'note') return null;

  const stepMatch = /^steps\.(\d+)$/.exec(field);
  if (!stepMatch) return `does not match any known guide path on track "${trackId}" (label, note, steps.<index>)`;
  const idx = Number(stepMatch[1]);
  return (track.steps ?? [])[idx] === undefined
    ? `references step ${idx} but track "${trackId}" has ${(track.steps ?? []).length} step(s)`
    : null;
}

function readJsonOptional(rel: string): any {
  const p = join(ROOT, rel);
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(readFileSync(p, 'utf8'));
  } catch (e) {
    errors.push(`[${rel}] not valid JSON: ${(e as Error).message}`);
    return null;
  }
}
