// The Content-Credential line assembly. Split out of docs/build.ts's shotCredential:
// the FACTS come from DocsRenderContext.credential (filesystem/C2PA at build time, a
// shipped manifest at runtime); THIS owns every byte of the HTML so both hosts emit
// identical markup. Ported verbatim — the exact bit/fact/label/return structure is
// load-bearing for the byte-identical build gate. See plan, M0b.

import { esc } from './esc.ts';
import { PROV_SEAL, localeNum, approxCount } from './markdown.ts';
import type { CredentialFacts, DocsRenderContext } from './context.ts';

export interface CredentialRenderOpts {
  /** The served file's name, e.g. "gallery.svg" or "mascots/koala.webp". Drives the
   *  file-extension "kind" pill/label and (when fromPresent) the basename prov-file pill. */
  file: string;
  /** The wrapper class (shot-cred--alt / --asset / --mascot / --mast / --figure / ''). */
  extraClass: string;
  /** Whether this credential was requested for a PAGE ASSET (opts present at the call
   *  site) rather than a bare screenshot — drives the prov-file basename pill. */
  fromPresent: boolean;
}

/**
 * Render one Content-Credential line from its facts, or '' when there are none. Mirrors
 * docs/build.ts's shotCredential exactly. `ctx` supplies t / htmlLang / nextCredId /
 * docIcon; `facts` supplies everything read from the served bytes.
 */
export function renderCredential(
  facts: CredentialFacts | null,
  opts: CredentialRenderOpts,
  ctx: Pick<DocsRenderContext, 't' | 'htmlLang' | 'nextCredId' | 'docIcon'>,
): string {
  // No readable credential → no line (and NO id is minted — the byte-identical id
  // sequence must not advance on a miss, matching shotCredential's early return).
  if (!facts) return '';
  const { file, extraClass, fromPresent } = opts;
  const id = ctx.nextCredId();
  const t = (s: string) => ctx.t(s);
  const num = (v: number) => localeNum(v, ctx.htmlLang);

  const ext = (file.split('.').pop() ?? '').toUpperCase();
  // "vector SVG" earns its adjective; a raster says only what it is.
  const kind = ext === 'SVG' ? `${t('vector')} SVG` : ext;
  const day = facts.when?.slice(0, 10) ?? null;
  const src = facts.src;
  const def = facts.recipe;
  const anat = facts.anat;

  // ONE row, three facts, two actions.
  const bits: string[] = [];
  if (facts.signer) {
    bits.push(`<span class="prov-pill prov-sig">${PROV_SEAL}${esc(t('signed by'))} `
      + `<span class="prov-pill prov-entity">${esc(facts.signer)}</span></span>`);
  }
  // A page ASSET names the served FILE in its line (basename only); a screenshot omits it.
  if (fromPresent) bits.push(`<span class="prov-pill prov-detail prov-file">${esc(file.split('/').pop() ?? file)}</span>`);
  if (kind) bits.push(`<span class="prov-pill prov-detail">${esc(kind)}</span>`);
  if (day) bits.push(`<time class="prov-pill prov-detail" datetime="${esc(day)}">${esc(day)}</time>`);
  if (facts.ai) bits.push(`<span class="prov-pill prov-entity">${esc(t(facts.ai === 'generated' ? 'AI generated' : 'AI edited'))}</span>`);
  if (facts.model) {
    bits.push(`<span class="prov-pill prov-act prov-model">${esc(t('generated by'))} `
      + `<span class="prov-pill prov-entity">${esc(facts.model)}</span></span>`);
  }

  // The second row: what the file is made of. Renders only when there is something to say.
  const detail = (s: string) => `<span class="prov-pill prov-detail">${esc(s)}</span>`;
  const factPills: string[] = [];
  if (anat?.kind === 'vector') {
    if (anat.paths > 0) factPills.push(detail(`${num(anat.paths)} ${t(anat.paths === 1 ? 'path' : 'paths')}`));
    if (anat.nodes > 0) factPills.push(detail(`${approxCount(anat.nodes, ctx.htmlLang)} ${t(anat.nodes === 1 ? 'node' : 'nodes')}`));
    if (anat.groups > 0) factPills.push(detail(`${num(anat.groups)} ${t(anat.groups === 1 ? 'group' : 'groups')}`));
    if (anat.paths === 0 && anat.groups === 0) {
      factPills.push(detail(`${num(anat.elements)} ${t(anat.elements === 1 ? 'element' : 'elements')}`));
    }
    if (anat.images > 0) factPills.push(detail(`${num(anat.images)} ${t(anat.images === 1 ? 'image' : 'images')}`));
  } else if (anat) {
    factPills.push(detail(t('pixels, not shapes')));
  }
  if (anat) factPills.push(detail(`${num(Math.round(anat.bytes / 1024))} KB`));

  // The accessible label carries the facts the width-bound visible row has no room for.
  const shotAt = def?.width && def.height
    ? `${num(def.width)} × ${num(def.height)}${def.dpi ? ` @ ${num(def.dpi)} dpi` : ''}` : '';
  const structure = anat?.kind === 'vector'
    ? `${num(anat.elements)} ${t(anat.elements === 1 ? 'element' : 'elements')}` : '';
  const how = anat?.kind === 'vector' && def
    ? t(def.walker ? 'captured with the HTML walker' : 'captured with the print path') : '';
  const label = [facts.ai ? t(facts.ai === 'generated' ? 'AI generated' : 'AI edited') : '', t('Content Credentials'),
    facts.signer ? `${t('signed by')} ${facts.signer}` : '', kind, facts.dimensions, day, facts.generator,
    facts.model ? `${t('generated by')} ${facts.model}` : '', facts.oversight ?? '',
    structure, shotAt, how].filter(Boolean).join(' - ');

  // A page asset's / figure's line rests OPEN; a screenshot's rests closed.
  const restsOpen = extraClass.includes('shot-cred--asset') || extraClass.includes('shot-cred--figure');
  // "Copy signed source" — offered only where the served file is pasteable source text.
  const copy = facts.canCopySource
    ? `<button type="button" class="shot-cred-do shot-cred-copy" data-copy-src="${esc(src)}"`
      + ` data-copied="${esc(t('Copied'))}" data-copy-failed="${esc(t('Copy failed'))}">`
      + `<span class="shot-cred-copy-label" aria-live="polite">${esc(t('Copy signed source'))}</span></button>`
    : '';
  return `<span class="shot-cred${facts.ai ? ' shot-cred--ai' : ''}${extraClass ? ` ${extraClass}` : ''}"${restsOpen ? ' data-static' : ''}>`
    + `<button type="button" class="shot-cred-btn" aria-expanded="${restsOpen}" aria-controls="${id}" aria-label="${esc(label)}">`
    + `${ctx.docIcon('imprint')}</button>`
    + `<span class="shot-cred-line" id="${id}">`
    + `<span class="shot-cred-row">${bits.join('')}`
    + `<a class="shot-cred-do" href="/#/verify?src=${encodeURIComponent(src)}">${esc(t('Check it yourself'))}</a>`
    + `<a class="shot-cred-do" href="${src}" download>${esc(t('Get the signed file'))}</a>`
    + copy
    + `</span>`
    + (factPills.length ? `<span class="shot-cred-row shot-cred-anat">${factPills.join('')}</span>` : '')
    + `</span></span>`;
}
