// GENERATED by scripts/build-ca-fn.ts — do not edit by hand.

// services/ca/lib/oidc.mjs
var te = new TextEncoder();
var subtle = globalThis.crypto.subtle;
var b64uBytes = (str) => new Uint8Array(Buffer.from(String(str), "base64url"));
var b64uJson = (str) => JSON.parse(Buffer.from(String(str), "base64url").toString("utf8"));
var OAUTH_PROVIDERS = ["github", "google", "suse"];
function configuredProviders(env) {
  return {
    github: Boolean(env.GITHUB_CLIENT_ID && env.GITHUB_CLIENT_SECRET),
    google: Boolean(env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET),
    suse: Boolean(env.SUSE_ISSUER && env.SUSE_CLIENT_ID && env.SUSE_CLIENT_SECRET),
    email: Boolean(env.RESEND_API_KEY && env.EMAIL_FROM)
  };
}
var looksLikeEmail = (v) => typeof v === "string" && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
var jsonCache = /* @__PURE__ */ new Map();
var CACHE_TTL_MS = 36e5;
function cachedJson(url) {
  const hit = jsonCache.get(url);
  if (hit && Date.now() - hit.at < CACHE_TTL_MS) return hit.promise;
  const promise = fetch(url, { headers: { accept: "application/json" } }).then((r) => {
    if (!r.ok) throw new Error(`${url} \u2192 HTTP ${r.status}`);
    return r.json();
  });
  promise.catch(() => jsonCache.delete(url));
  jsonCache.set(url, { at: Date.now(), promise });
  return promise;
}
var GOOGLE_DISCOVERY = "https://accounts.google.com/.well-known/openid-configuration";
function discoveryUrl(provider, env) {
  if (provider === "google") return GOOGLE_DISCOVERY;
  return `${String(env.SUSE_ISSUER || "").replace(/\/$/, "")}/.well-known/openid-configuration`;
}
async function pkceChallengeS256(verifier) {
  return Buffer.from(new Uint8Array(await subtle.digest("SHA-256", te.encode(verifier)))).toString("base64url");
}
async function buildAuthorizeUrl(provider, env, { redirectUri, state, nonce, pkceVerifier }) {
  if (provider === "github") {
    const u2 = new URL("https://github.com/login/oauth/authorize");
    u2.searchParams.set("client_id", env.GITHUB_CLIENT_ID);
    u2.searchParams.set("redirect_uri", redirectUri);
    u2.searchParams.set("scope", "user:email");
    u2.searchParams.set("state", state);
    return u2.href;
  }
  const disco = await cachedJson(discoveryUrl(provider, env));
  const u = new URL(disco.authorization_endpoint);
  u.searchParams.set("client_id", provider === "google" ? env.GOOGLE_CLIENT_ID : env.SUSE_CLIENT_ID);
  u.searchParams.set("redirect_uri", redirectUri);
  u.searchParams.set("response_type", "code");
  u.searchParams.set("scope", provider === "google" ? "openid email" : "openid email profile");
  u.searchParams.set("state", state);
  u.searchParams.set("nonce", nonce);
  u.searchParams.set("code_challenge", await pkceChallengeS256(pkceVerifier));
  u.searchParams.set("code_challenge_method", "S256");
  return u.href;
}
async function verifyIdToken(idToken, { jwksUri, issuer, clientId, nonce }) {
  const parts = String(idToken).split(".");
  if (parts.length !== 3) throw new Error("id_token is not a JWT");
  const [h64, p64, s64] = parts;
  const header = b64uJson(h64);
  if (header.alg !== "RS256") throw new Error(`unsupported id_token alg: ${header.alg}`);
  const jwks = await cachedJson(jwksUri);
  const keys = Array.isArray(jwks.keys) ? jwks.keys : [];
  const jwk = keys.find((k) => k.kid === header.kid) || keys.find((k) => k.kty === "RSA" && (k.use || "sig") === "sig");
  if (!jwk) throw new Error("no matching key in the provider JWKS");
  const key = await subtle.importKey("jwk", { kty: "RSA", n: jwk.n, e: jwk.e }, { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" }, false, ["verify"]);
  const ok = await subtle.verify("RSASSA-PKCS1-v1_5", key, b64uBytes(s64), te.encode(`${h64}.${p64}`));
  if (!ok) throw new Error("id_token signature does not verify");
  const claims = b64uJson(p64);
  if (claims.iss !== issuer) throw new Error(`id_token issuer mismatch: ${claims.iss}`);
  const aud = Array.isArray(claims.aud) ? claims.aud : [claims.aud];
  if (!aud.includes(clientId)) throw new Error("id_token audience mismatch");
  if (typeof claims.exp !== "number" || claims.exp * 1e3 < Date.now()) throw new Error("id_token expired");
  if (nonce && claims.nonce !== nonce) throw new Error("id_token nonce mismatch");
  return claims;
}
async function exchangeOidc(provider, env, { code, redirectUri, pkceVerifier, nonce }) {
  const disco = await cachedJson(discoveryUrl(provider, env));
  const clientId = provider === "google" ? env.GOOGLE_CLIENT_ID : env.SUSE_CLIENT_ID;
  const clientSecret = provider === "google" ? env.GOOGLE_CLIENT_SECRET : env.SUSE_CLIENT_SECRET;
  const res = await fetch(disco.token_endpoint, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded", accept: "application/json" },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: redirectUri,
      client_id: clientId,
      client_secret: clientSecret,
      code_verifier: pkceVerifier
    })
  });
  const tok = await res.json().catch(() => ({}));
  if (!res.ok || !tok.id_token) {
    throw new Error(tok.error_description || tok.error || `${provider} token exchange failed (HTTP ${res.status})`);
  }
  return verifyIdToken(tok.id_token, { jwksUri: disco.jwks_uri, issuer: disco.issuer, clientId, nonce });
}
async function githubEmail(env, { code, redirectUri }) {
  const res = await fetch("https://github.com/login/oauth/access_token", {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded", accept: "application/json" },
    body: new URLSearchParams({
      client_id: env.GITHUB_CLIENT_ID,
      client_secret: env.GITHUB_CLIENT_SECRET,
      code,
      redirect_uri: redirectUri
    })
  });
  const tok = await res.json().catch(() => ({}));
  if (!res.ok || !tok.access_token) {
    throw new Error(tok.error_description || tok.error || `GitHub token exchange failed (HTTP ${res.status})`);
  }
  const gh = (path) => fetch(`https://api.github.com${path}`, {
    headers: { authorization: `Bearer ${tok.access_token}`, "user-agent": "lolly-ca", accept: "application/vnd.github+json" }
  });
  const emailsRes = await gh("/user/emails");
  if (emailsRes.ok) {
    const list = await emailsRes.json();
    if (Array.isArray(list)) {
      const best = list.find((e) => e.primary && e.verified) || list.find((e) => e.verified);
      if (best && looksLikeEmail(best.email)) return best.email;
    }
  }
  const userRes = await gh("/user");
  const user = userRes.ok ? await userRes.json() : {};
  if (looksLikeEmail(user.email)) return user.email;
  throw new Error("GitHub account has no verified email");
}
async function fetchVerifiedEmail(provider, env, { code, redirectUri, pkceVerifier, nonce }) {
  if (provider === "github") return githubEmail(env, { code, redirectUri });
  const claims = await exchangeOidc(provider, env, { code, redirectUri, pkceVerifier, nonce });
  if (provider === "google") {
    if (claims.email_verified !== true) throw new Error("Google account email is not verified");
    if (!looksLikeEmail(claims.email)) throw new Error("Google id_token carries no email");
    return claims.email;
  }
  if (claims.email_verified === false) throw new Error("account email is not verified");
  if (!looksLikeEmail(claims.email)) throw new Error("id_token carries no verified email claim");
  return claims.email;
}

// services/ca/lib/tokens.mjs
var te2 = new TextEncoder();
var subtle2 = globalThis.crypto.subtle;
var b64u = (bytes) => Buffer.from(bytes).toString("base64url");
var b64uToBytes = (str) => new Uint8Array(Buffer.from(String(str), "base64url"));
var randomB64u = (n = 32) => b64u(globalThis.crypto.getRandomValues(new Uint8Array(n)));
async function hmac(secret, text) {
  if (!secret) throw new Error("CA_SERVICE_SECRET is not set");
  const key = await subtle2.importKey("raw", te2.encode(String(secret)), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  return new Uint8Array(await subtle2.sign("HMAC", key, te2.encode(text)));
}
async function signValue(payload, secret) {
  const body = Buffer.from(JSON.stringify(payload)).toString("base64url");
  return `${body}.${b64u(await hmac(secret, body))}`;
}
async function verifyValue(value, secret) {
  const parts = String(value || "").split(".");
  if (parts.length !== 2 || !parts[0] || !parts[1]) return null;
  const expect = await hmac(secret, parts[0]);
  const got = b64uToBytes(parts[1]);
  if (got.length !== expect.length) return null;
  let diff = 0;
  for (let i = 0; i < expect.length; i++) diff |= expect[i] ^ got[i];
  if (diff !== 0) return null;
  try {
    return JSON.parse(Buffer.from(parts[0], "base64url").toString("utf8"));
  } catch {
    return null;
  }
}
var TOKEN_TTL_SECONDS = 600;
var TOKEN_TYP = "lolly-ca/enroll";
async function mintEnrollToken({ email, provider, days }, secret, ttlSeconds = TOKEN_TTL_SECONDS) {
  const iat = Math.floor(Date.now() / 1e3);
  return signValue({ typ: TOKEN_TYP, email, provider, iat, exp: iat + ttlSeconds, ...Number.isFinite(days) ? { days } : {} }, secret);
}
async function verifyEnrollToken(token, secret) {
  const payload = await verifyValue(token, secret);
  if (!payload) return { ok: false, error: "invalid enrollment token" };
  if (payload.typ !== TOKEN_TYP) return { ok: false, error: "wrong token type" };
  if (typeof payload.exp !== "number" || payload.exp * 1e3 < Date.now()) return { ok: false, error: "enrollment token expired" };
  if (!payload.email || !payload.provider) return { ok: false, error: "enrollment token carries no identity" };
  return { ok: true, payload };
}

// services/ca/lib/pages.mjs
var js = (value) => JSON.stringify(value).replace(/</g, "\\u003c");
var escapeHtml = (s) => String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
var shell = (title, body, script = "") => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>${escapeHtml(title)}</title>
<style>
  body { font-family: system-ui, sans-serif; display: grid; place-items: center; min-height: 100vh; margin: 0; background: #0c322c; color: #efefef; text-align: center; }
  main { padding: 2rem; max-width: 26rem; }
  h1 { font-size: 1.3rem; margin: 0 0 0.5rem; }
  p { color: #b7c8c4; line-height: 1.5; }
</style>
</head>
<body>
<main>${body}</main>
${script}</body>
</html>
`;
function completionPage({ token, origin }) {
  const script = `<script>
(function () {
  try {
    if (window.opener) {
      window.opener.postMessage(${js({ source: "lolly-ca", type: "enroll-token", token })}, ${js(origin)});
      window.close();
    }
  } catch (e) { /* fall through to the visible message */ }
})();
</script>
`;
  return shell("Lolly \u2014 verified", `<h1>You&#39;re verified</h1>
<p>Return to Lolly to finish setting up Content Credentials. You can close this window.</p>`, script);
}
function errorPage(message) {
  return shell("Lolly \u2014 sign-in failed", `<h1>Sign-in didn&#39;t complete</h1>
<p>${escapeHtml(message)}</p>
<p>Close this window and try again from Lolly.</p>`);
}

// engine/src/x509.ts
var te3 = new TextEncoder();
var subtle3 = globalThis.crypto.subtle;
var asBufferSource = (b) => b;
function concatBytes(parts) {
  let n = 0;
  for (const p of parts) n += p.length;
  const out = new Uint8Array(n);
  let o = 0;
  for (const p of parts) {
    out.set(p, o);
    o += p.length;
  }
  return out;
}
function derLen(n) {
  if (n < 128) return Uint8Array.of(n);
  if (n < 256) return Uint8Array.of(129, n);
  if (n < 65536) return Uint8Array.of(130, n >>> 8, n & 255);
  return Uint8Array.of(131, n >>> 16, n >>> 8 & 255, n & 255);
}
function der(tag, ...content) {
  const body = concatBytes(content);
  return concatBytes([Uint8Array.of(tag), derLen(body.length), body]);
}
var derSeq = (...c) => der(48, ...c);
var derSet = (...c) => der(49, ...c);
var derOctet = (bytes) => der(4, bytes);
function derUint(bytes) {
  let i = 0;
  while (i < bytes.length - 1 && bytes[i] === 0) i++;
  const v = bytes.subarray(i);
  return v[0] & 128 ? der(2, Uint8Array.of(0), v) : der(2, v);
}
function derOid(oid) {
  const parts = oid.split(".").map(Number);
  const bytes = [parts[0] * 40 + parts[1]];
  for (const p of parts.slice(2)) {
    const grp = [p & 127];
    for (let n = Math.floor(p / 128); n > 0; n = Math.floor(n / 128)) grp.unshift(n & 127 | 128);
    bytes.push(...grp);
  }
  return der(6, Uint8Array.from(bytes));
}
function derTime(date) {
  const p = (v, w = 2) => String(v).padStart(w, "0");
  const y = date.getUTCFullYear();
  const rest = p(date.getUTCMonth() + 1) + p(date.getUTCDate()) + p(date.getUTCHours()) + p(date.getUTCMinutes()) + p(date.getUTCSeconds()) + "Z";
  if (y >= 1950 && y < 2050) return der(23, te3.encode(p(y % 100) + rest));
  return der(24, te3.encode(p(y, 4) + rest));
}
function ecdsaRawToDer(raw) {
  const half = raw.length / 2;
  return derSeq(derUint(raw.subarray(0, half)), derUint(raw.subarray(half)));
}
function asDate(v, fallback) {
  const d = v == null ? new Date(fallback) : v instanceof Date ? v : new Date(v);
  if (Number.isNaN(d.getTime())) throw new Error("c2pa: invalid date " + v);
  return d;
}
function readTlv(b, i) {
  if (i + 2 > b.length) throw new Error("x509: truncated DER");
  const tag = b[i];
  let len = b[i + 1];
  let j = i + 2;
  if (len & 128) {
    const k = len & 127;
    len = 0;
    for (let x = 0; x < k; x++) len = len * 256 + b[j++];
  }
  if (j + len > b.length) throw new Error("x509: DER length overruns buffer");
  return { tag, start: i, contentStart: j, end: j + len };
}
function readChildren(b, tlv) {
  const kids = [];
  let i = tlv.contentStart;
  while (i < tlv.end) {
    const c = readTlv(b, i);
    kids.push(c);
    i = c.end;
  }
  return kids;
}
async function keyIdOf(spkiDer) {
  const [, bits] = readChildren(spkiDer, readTlv(spkiDer, 0));
  if (!bits || bits.tag !== 3) throw new Error("x509: SPKI has no subjectPublicKey BIT STRING");
  return new Uint8Array(await subtle3.digest("SHA-1", asBufferSource(spkiDer.subarray(bits.contentStart + 1, bits.end))));
}
function certNameAndKey(certDer) {
  const [tbs] = readChildren(certDer, readTlv(certDer, 0));
  const kids = readChildren(certDer, tbs);
  const shift = kids[0].tag === 160 ? 1 : 0;
  return {
    subjectBytes: certDer.slice(kids[shift + 4].start, kids[shift + 4].end),
    spkiDer: certDer.slice(kids[shift + 5].start, kids[shift + 5].end)
  };
}
function pemToDer(pem) {
  const b64 = String(pem).replace(/-----[^-]+-----/g, "").replace(/\s+/g, "");
  if (!b64) throw new Error("x509: no PEM body found");
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function derToPem(der2, label) {
  let bin = "";
  for (let i = 0; i < der2.length; i += 32768) {
    bin += String.fromCharCode.apply(null, der2.subarray(i, i + 32768));
  }
  const body = btoa(bin).replace(/(.{64})/g, "$1\n").trimEnd();
  return `-----BEGIN ${label}-----
${body}
-----END ${label}-----
`;
}
var OID_ECDSA_WITH_SHA256 = "1.2.840.10045.4.3.2";
function randomSerial() {
  const serial = globalThis.crypto.getRandomValues(new Uint8Array(9));
  serial[0] = serial[0] & 63 | 64;
  return serial;
}
function x501Name(organization, commonName) {
  return derSeq(
    derSet(derSeq(derOid("2.5.4.10"), der(12, te3.encode(organization)))),
    // organizationName
    derSet(derSeq(derOid("2.5.4.3"), der(12, te3.encode(commonName))))
    // commonName
  );
}
async function signTbs(tbs, privateKey) {
  const raw = new Uint8Array(await subtle3.sign({ name: "ECDSA", hash: "SHA-256" }, privateKey, asBufferSource(tbs)));
  return derSeq(tbs, derSeq(derOid(OID_ECDSA_WITH_SHA256)), der(3, Uint8Array.of(0), ecdsaRawToDer(raw)));
}
async function issueLeafCert({
  caCertDer,
  caPrivateKey,
  spkiDer,
  email,
  commonName,
  organization = "Lolly",
  days = 7,
  notBefore,
  notAfter
} = {}) {
  if (!(caCertDer instanceof Uint8Array)) throw new Error("x509: caCertDer must be a Uint8Array");
  if (!(spkiDer instanceof Uint8Array)) throw new Error("x509: spkiDer must be a Uint8Array");
  if (!email) throw new Error("x509: email is required");
  const nb = asDate(notBefore, Date.now() - 6e4);
  const na = asDate(notAfter, nb.getTime() + days * 24 * 3600 * 1e3);
  const signKey = caPrivateKey instanceof Uint8Array ? await subtle3.importKey("pkcs8", asBufferSource(caPrivateKey), { name: "ECDSA", namedCurve: "P-256" }, false, ["sign"]) : caPrivateKey;
  const ca = certNameAndKey(caCertDer);
  const keyId = await keyIdOf(spkiDer);
  const issuerKeyId = await keyIdOf(ca.spkiDer);
  const extensions = derSeq(
    derSeq(derOid("2.5.29.19"), derOctet(derSeq())),
    // basicConstraints: CA absent = false
    derSeq(derOid("2.5.29.15"), der(1, Uint8Array.of(255)), derOctet(der(3, Uint8Array.of(7, 128)))),
    // keyUsage: digitalSignature, critical
    derSeq(derOid("2.5.29.37"), derOctet(derSeq(derOid("1.3.6.1.5.5.7.3.4")))),
    // extKeyUsage: emailProtection
    derSeq(derOid("2.5.29.14"), derOctet(derOctet(keyId))),
    // subjectKeyIdentifier
    derSeq(derOid("2.5.29.35"), derOctet(derSeq(der(128, issuerKeyId)))),
    // authorityKeyIdentifier: [0] keyid
    derSeq(derOid("2.5.29.17"), derOctet(derSeq(der(129, te3.encode(String(email))))))
    // subjectAltName: rfc822Name
  );
  const tbs = derSeq(
    der(160, derUint(Uint8Array.of(2))),
    // [0] version: v3
    derUint(randomSerial()),
    derSeq(derOid(OID_ECDSA_WITH_SHA256)),
    ca.subjectBytes,
    // issuer, byte-identical to the CA's subject
    derSeq(derTime(nb), derTime(na)),
    x501Name(organization, commonName || String(email)),
    spkiDer,
    // already a DER SubjectPublicKeyInfo
    der(163, extensions)
  );
  return signTbs(tbs, signKey);
}

// services/ca/lib/enroll.mjs
var te4 = new TextEncoder();
var subtle4 = globalThis.crypto.subtle;
var DAY_MS = 24 * 3600 * 1e3;
var ALLOWED_DAYS = [7, 30, 90, 365];
async function verifyPop({ token, spki, pop }) {
  const spkiDer = b64uToBytes(spki);
  const sig = b64uToBytes(pop);
  if (sig.length !== 64) return { ok: false, error: "pop must be a raw 64-byte ECDSA P-256 signature" };
  let key;
  try {
    key = await subtle4.importKey("spki", spkiDer, { name: "ECDSA", namedCurve: "P-256" }, false, ["verify"]);
  } catch {
    return { ok: false, error: "spki is not a P-256 public key" };
  }
  const ok = await subtle4.verify({ name: "ECDSA", hash: "SHA-256" }, key, sig, te4.encode(String(token)));
  return ok ? { ok: true, spkiDer } : { ok: false, error: "proof-of-possession signature does not verify" };
}
function leafDays(env, requested) {
  const fallback = Number(env.CA_CERT_DAYS) || 30;
  const max = Number(env.CA_CERT_MAX_DAYS) || 365;
  const days = ALLOWED_DAYS.includes(Number(requested)) ? Number(requested) : fallback;
  return Math.min(days, max);
}
async function logIssuance(env, { email, provider, certDer, notAfter }) {
  const digest = new Uint8Array(await subtle4.digest("SHA-256", certDer));
  const serialHint = Array.from(digest.subarray(0, 4), (b) => b.toString(16).padStart(2, "0")).join("");
  const entry = { at: (/* @__PURE__ */ new Date()).toISOString(), email, provider, serialHint, notAfter: notAfter.toISOString() };
  console.log(JSON.stringify(entry));
  if (env.CA_LOG_WEBHOOK) {
    fetch(env.CA_LOG_WEBHOOK, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(entry)
    }).catch(() => {
    });
  }
}
async function enroll({ token, spki, pop, days } = {}, env) {
  if (!token || !spki || !pop) return { status: 400, json: { error: "token, spki and pop are required" } };
  const t = await verifyEnrollToken(String(token), env.CA_SERVICE_SECRET);
  if (!t.ok) return { status: 401, json: { error: t.error } };
  const p = await verifyPop({ token: String(token), spki, pop });
  if (!p.ok) return { status: 401, json: { error: p.error } };
  if (!env.CA_ROOT_CERT_PEM || !env.CA_ROOT_KEY_PEM) return { status: 500, json: { error: "CA root is not configured" } };
  const caCertDer = pemToDer(env.CA_ROOT_CERT_PEM);
  const notBefore = new Date(Math.floor((Date.now() - 6e4) / 1e3) * 1e3);
  const notAfter = new Date(notBefore.getTime() + leafDays(env, t.payload.days ?? days) * DAY_MS);
  const certDer = await issueLeafCert({
    caCertDer,
    caPrivateKey: pemToDer(env.CA_ROOT_KEY_PEM),
    spkiDer: p.spkiDer,
    email: t.payload.email,
    notBefore,
    notAfter
  });
  await logIssuance(env, { email: t.payload.email, provider: t.payload.provider, certDer, notAfter });
  const certPem = derToPem(certDer, "CERTIFICATE");
  return {
    status: 200,
    json: {
      cert: certPem,
      chain: [certPem, derToPem(caCertDer, "CERTIFICATE")],
      // leaf-first, root normalised
      identity: { email: t.payload.email, provider: t.payload.provider },
      notBefore: notBefore.toISOString(),
      notAfter: notAfter.toISOString()
    }
  };
}

// services/ca/handler.mjs
var STATE_COOKIE = "lolly_ca_state";
var STATE_TTL_SECONDS = 600;
var BODY_CAP = 64 * 1024;
var STATE_TYP = "lolly-ca/state";
var EMAIL_COOLDOWN_MS = 60 * 1e3;
var lastEmailAt = /* @__PURE__ */ new Map();
function emailOnCooldown(email, now) {
  if (lastEmailAt.size > 5e3) {
    for (const [k, t] of lastEmailAt) if (now - t > EMAIL_COOLDOWN_MS) lastEmailAt.delete(k);
  }
  const prev = lastEmailAt.get(email);
  return prev !== void 0 && now - prev < EMAIL_COOLDOWN_MS;
}
var IP_WINDOW_MS = 60 * 1e3;
var IP_MAX_PER_WINDOW = 5;
var ipHits = /* @__PURE__ */ new Map();
function ipRateLimited(ip, now) {
  if (!ip) return false;
  if (ipHits.size > 5e3) {
    for (const [k, hits] of ipHits) if (!hits.some((t) => now - t < IP_WINDOW_MS)) ipHits.delete(k);
  }
  const recent = (ipHits.get(ip) || []).filter((t) => now - t < IP_WINDOW_MS);
  ipHits.set(ip, recent);
  if (recent.length >= IP_MAX_PER_WINDOW) return true;
  recent.push(now);
  return false;
}
function isAllowedOrigin(origin, env) {
  if (!origin || typeof origin !== "string") return false;
  const list = String(env.CA_ALLOWED_ORIGINS || "").split(",").map((s) => s.trim()).filter(Boolean);
  if (list.includes(origin)) return true;
  if (env.CA_DEV_FAKE_PROVIDER === "1" && /^http:\/\/localhost(:\d+)?$/.test(origin)) return true;
  return false;
}
function routeHealth(env) {
  return {
    status: 200,
    json: {
      ok: true,
      devProvider: env.CA_DEV_FAKE_PROVIDER === "1",
      configured: configuredProviders(env)
    }
  };
}
function routeRootPem(env) {
  if (!env.CA_ROOT_CERT_PEM) {
    return { status: 404, body: "CA root certificate is not configured on this deployment\n", type: "text/plain; charset=utf-8" };
  }
  return { status: 200, body: `${String(env.CA_ROOT_CERT_PEM).trim()}
`, type: "text/plain; charset=utf-8" };
}
var stateCookie = (value, redirectUri, maxAge = STATE_TTL_SECONDS) => `${STATE_COOKIE}=${value}; Max-Age=${maxAge}; Path=/api/ca; HttpOnly; SameSite=Lax${String(redirectUri).startsWith("https") ? "; Secure" : ""}`;
async function routeAuth(env, { provider, origin, redirectUri }) {
  if (!isAllowedOrigin(origin, env)) return { status: 403, json: { error: "origin is not allowlisted" } };
  if (provider === "dev") {
    if (env.CA_DEV_FAKE_PROVIDER !== "1") return { status: 404, json: { error: "unknown provider" } };
    const token = await mintEnrollToken({ email: "dev@example.com", provider: "dev" }, env.CA_SERVICE_SECRET);
    return { status: 200, body: completionPage({ token, origin }), type: "text/html; charset=utf-8" };
  }
  if (!OAUTH_PROVIDERS.includes(provider)) return { status: 404, json: { error: "unknown provider" } };
  if (!configuredProviders(env)[provider]) return { status: 501, json: { error: `${provider} sign-in is not configured on this deployment` } };
  const nonce = randomB64u(24);
  const pkceVerifier = randomB64u(48);
  const state = { typ: STATE_TYP, provider, origin, pkceVerifier, nonce, exp: Math.floor(Date.now() / 1e3) + STATE_TTL_SECONDS };
  const location = await buildAuthorizeUrl(provider, env, { redirectUri, state: nonce, nonce, pkceVerifier });
  return {
    status: 302,
    headers: {
      location,
      "set-cookie": stateCookie(await signValue(state, env.CA_SERVICE_SECRET), redirectUri)
    }
  };
}
async function routeCallback(env, { provider, query, cookieHeader, redirectUri }) {
  const clear = { "set-cookie": stateCookie("", redirectUri, 0) };
  const fail = (status, message) => ({ status, body: errorPage(message), type: "text/html; charset=utf-8", headers: clear });
  const state = await verifyValue(parseCookies(cookieHeader)[STATE_COOKIE], env.CA_SERVICE_SECRET);
  if (!state || state.typ !== STATE_TYP) return fail(401, "The sign-in state is missing or invalid. Start again from Lolly.");
  if (typeof state.exp !== "number" || state.exp * 1e3 < Date.now()) return fail(401, "The sign-in attempt expired \u2014 it only lives 10 minutes.");
  if (state.provider !== provider) return fail(400, "The sign-in state does not match this provider.");
  if (!query.state || query.state !== state.nonce) return fail(400, "The sign-in state does not match this browser.");
  if (!query.code) return fail(400, query.error_description || query.error || "The provider returned no authorization code.");
  let email;
  try {
    email = await fetchVerifiedEmail(provider, env, {
      code: query.code,
      redirectUri,
      pkceVerifier: state.pkceVerifier,
      nonce: state.nonce
    });
  } catch (err) {
    return fail(401, err?.message || "Could not verify your email with the provider.");
  }
  const token = await mintEnrollToken({ email, provider }, env.CA_SERVICE_SECRET);
  return { status: 200, body: completionPage({ token, origin: state.origin }), type: "text/html; charset=utf-8", headers: clear };
}
async function routeEmailStart(env, body, ip) {
  const email = typeof body?.email === "string" ? body.email.trim() : "";
  const origin = body?.origin;
  if (!isAllowedOrigin(origin, env)) return { status: 403, json: { error: "origin is not allowlisted" } };
  if (!looksLikeEmail(email)) return { status: 400, json: { error: "invalid email address" } };
  if (!env.RESEND_API_KEY || !env.EMAIL_FROM) {
    return { status: 501, json: { error: "email sign-in is not configured on this deployment (RESEND_API_KEY / EMAIL_FROM)" } };
  }
  const now = Date.now();
  if (emailOnCooldown(email, now)) return { status: 200, json: { sent: true } };
  if (ipRateLimited(ip, now)) return { status: 429, json: { error: "too many requests, please try again shortly" } };
  lastEmailAt.set(email, now);
  const days = Number(body?.days);
  const token = await mintEnrollToken(
    { email, provider: "email", ...Number.isFinite(days) ? { days } : {} },
    env.CA_SERVICE_SECRET
  );
  const link = `${origin}/#/profile?enrollToken=${encodeURIComponent(token)}`;
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { authorization: `Bearer ${env.RESEND_API_KEY}`, "content-type": "application/json" },
    body: JSON.stringify({
      from: env.EMAIL_FROM,
      to: [email],
      subject: "Verify your email for Lolly Content Credentials",
      text: `Open this link in the browser where Lolly is open (it expires in 10 minutes):

${link}

If you didn't request this, ignore this email.`
    })
  });
  if (!res.ok) {
    console.error("resend send failed:", res.status, (await res.text().catch(() => "")).slice(0, 300));
    return { status: 502, json: { error: "sending the verification email failed" } };
  }
  return { status: 200, json: { sent: true } };
}
function clientIp(req) {
  const xff = String(req.headers["x-forwarded-for"] || "").split(",")[0].trim();
  return xff || req.socket?.remoteAddress || "";
}
function parseCookies(header) {
  const out = {};
  for (const part of String(header || "").split(/;\s*/)) {
    const i = part.indexOf("=");
    if (i > 0) out[part.slice(0, i)] = part.slice(i + 1);
  }
  return out;
}
function redirectUriFor(req, provider) {
  const host = String(req.headers.host || "localhost");
  const forwarded = String(req.headers["x-forwarded-proto"] || "").split(",")[0].trim();
  const proto = forwarded || (/^(localhost|127\.)/.test(host) ? "http" : "https");
  return `${proto}://${host}/api/ca/callback/${provider}`;
}
async function readJsonBody(req) {
  if (req.body !== void 0 && req.body !== null) {
    if (Buffer.isBuffer(req.body) || typeof req.body === "string") {
      try {
        return JSON.parse(String(req.body));
      } catch {
        return null;
      }
    }
    return req.body;
  }
  const chunks = [];
  let size = 0;
  for await (const chunk of req) {
    size += chunk.length;
    if (size > BODY_CAP) throw Object.assign(new Error("request body too large"), { statusCode: 413 });
    chunks.push(chunk);
  }
  try {
    return JSON.parse(Buffer.concat(chunks).toString("utf8") || "null");
  } catch {
    return null;
  }
}
function writeResult(res, result, cors = {}) {
  const headers = { ...cors, ...result.headers || {} };
  let body;
  if (result.json !== void 0) {
    headers["content-type"] = "application/json; charset=utf-8";
    body = JSON.stringify(result.json);
  } else {
    headers["content-type"] = result.type || "text/html; charset=utf-8";
    body = result.body || "";
  }
  if (!headers["cache-control"]) headers["cache-control"] = "no-store";
  res.writeHead(result.status, headers);
  res.end(body);
}
async function route(env, req, url, path) {
  const m = req.method;
  if (m === "GET" && path === "/api/ca/health") return routeHealth(env);
  if (m === "GET" && path === "/api/ca/root.pem") return routeRootPem(env);
  const auth = m === "GET" && path.match(/^\/api\/ca\/auth\/([a-z0-9_-]+)$/);
  if (auth) {
    return routeAuth(env, {
      provider: auth[1],
      origin: url.searchParams.get("origin"),
      redirectUri: redirectUriFor(req, auth[1])
    });
  }
  const cb = m === "GET" && path.match(/^\/api\/ca\/callback\/([a-z0-9_-]+)$/);
  if (cb) {
    return routeCallback(env, {
      provider: cb[1],
      query: Object.fromEntries(url.searchParams),
      cookieHeader: req.headers.cookie,
      redirectUri: redirectUriFor(req, cb[1])
    });
  }
  if (m === "POST" && (path === "/api/ca/email/start" || path === "/api/ca/enroll")) {
    let body;
    try {
      body = await readJsonBody(req);
    } catch (err) {
      return { status: err.statusCode || 400, json: { error: err.message } };
    }
    return path === "/api/ca/enroll" ? enroll(body || {}, env) : routeEmailStart(env, body || {}, clientIp(req));
  }
  return { status: 404, json: { error: "not found" } };
}
function createCaHandler(env = process.env) {
  const caEnabled = !!(env.CA_SERVICE_SECRET || env.CA_ROOT_KEY_PEM);
  return async function caHandler(req, res) {
    try {
      const url = new URL(req.url, "http://internal");
      const path = url.pathname.replace(/\/+$/, "") || "/";
      if (!caEnabled) {
        res.writeHead(404, { "content-type": "application/json; charset=utf-8" });
        res.end(JSON.stringify({ error: "not_found" }));
        return;
      }
      const requestOrigin = req.headers.origin;
      const cors = isAllowedOrigin(requestOrigin, env) ? { "access-control-allow-origin": requestOrigin, vary: "Origin" } : {};
      if (req.method === "OPTIONS") {
        res.writeHead(204, { ...cors, "access-control-allow-methods": "GET,POST,OPTIONS", "access-control-allow-headers": "content-type" });
        res.end();
        return;
      }
      writeResult(res, await route(env, req, url, path), cors);
    } catch (err) {
      console.error("ca handler error:", err);
      try {
        res.writeHead(500, { "content-type": "application/json; charset=utf-8" });
        res.end(JSON.stringify({ error: "internal error" }));
      } catch {
      }
    }
  };
}

// services/ca/vercel-entry.mjs
var vercel_entry_default = createCaHandler();
export {
  vercel_entry_default as default
};
