// SPDX-License-Identifier: MPL-2.0
/**
 * Text AI-likelihood signals - a string in, a tiered report of the signals that
 * bear on "was this text generated by (or run through) an AI model" out.
 *
 * This is a SIGNAL, never a verdict. AI-text detection is unreliable and, misused,
 * harms real people (false accusations, a bias against non-native and formal
 * writing). So this module never returns a bare percentage and never asserts a
 * fact: it returns a coarse BAND (none/weak/notable/strong) plus the concrete
 * findings behind it, and the shell presents those as observations a person reads,
 * not a score a person quotes.
 *
 * Two confidence tiers ship in v1:
 *  - `artifact` (high): byte-level tells in DIGITAL text - invisible/zero-width
 *    characters, mixed-script homoglyphs, whitespace anomalies, bidi overrides.
 *    These are artifacts, not guesses. They are ABSENT from text read out of an
 *    image: OCR reads pixels, so the whole artifact layer is lost in rasterisation
 *    (`source: 'ocr'` sets `pixelSourced` and skips this tier entirely).
 *  - `heuristic` (low): a writing-style hint - an LLM-lexicon list, punctuation
 *    and list tells, sentence-length uniformity. Style is not proof, so heuristics
 *    alone never reach `strong`. They are English-centric, so they run ONLY on text
 *    that reads as English and is long enough to judge - short or non-English text
 *    returns `none` honestly rather than a biased false positive. This bias guard
 *    is required, not optional.
 *
 * A `watermark` tier (a named-scheme detector like SynthID-Text) is a later add-on;
 * a watermark match is the one thing that may name a model with confidence. Until
 * then a naming guess is stylistic only, hence `TextStyleGuess.confidence` is the
 * literal `'low'` - the type forbids a confident stylistic attribution - and it is
 * offered only at band >= 'notable', framed "consistent with", never as an accusation.
 *
 * DOM-free and model-free: plain string in, plain object out, so the verify view,
 * the CLI, and the OCR path all read identical numbers. Pure - no I/O, no state.
 */

export type TextSignalSource = 'digital' | 'ocr';
export type TextSignalBand = 'none' | 'weak' | 'notable' | 'strong';
export type TextSignalTier = 'artifact' | 'heuristic'; // 'watermark' added by a later minor.

/** A [index, length) slice of the source string, in UTF-16 code units, for highlighting. */
export interface TextSignalSpan {
  index: number;
  length: number;
}

/**
 * One observed signal. `weight` is this finding's contribution to the band (see
 * `analyzeTextSignals`); `spans` locate it in the source for the UI to highlight.
 * `label`/`detail` are plain English defaults - the shell may re-localise by `kind`.
 */
export interface TextSignalFinding {
  tier: TextSignalTier;
  /** Stable machine key, e.g. 'zero-width-char' | 'mixed-script' | 'llm-lexicon'. */
  kind: string;
  /** Human summary the UI may show as-is. */
  label: string;
  /** Specifics: which codepoints, which words, counts. */
  detail?: string;
  /** Contribution to the band. Artifact tells weigh more than style tells. */
  weight: number;
  spans?: TextSignalSpan[];
}

/**
 * A hedged, stylistic-only guess at a source. `confidence` is the LITERAL 'low':
 * a specific model cannot be credibly named from writing style, so this is offered
 * as a possibility ("consistent with"), never a determination, and never on its own.
 */
export interface TextStyleGuess {
  /** A family label, e.g. 'generic-LLM'. Naming a specific product awaits a watermark tier. */
  family: string;
  confidence: 'low';
  /** Which markers drove the guess; always framed as a possibility. */
  rationale: string;
}

export interface TextSignalReport {
  source: TextSignalSource;
  /** True when `source === 'ocr'`: the artifact tier could not run (pixels, not bytes). */
  pixelSourced: boolean;
  band: TextSignalBand;
  /** Findings, most significant first. */
  findings: TextSignalFinding[];
  /** Present only at band >= 'notable'. Always hedged (see `TextStyleGuess`). */
  styleGuess?: TextStyleGuess;
  /** A plain, non-accusatory one-liner the UI may show as-is. */
  summary: string;
}

export interface AnalyzeTextSignalsOpts {
  source: TextSignalSource;
}

// ─── Artifact-tier detectors (digital text only) ──────────────────────────────

/** Zero-width / invisible characters that are essentially never legitimate in prose. */
const INVISIBLE_CORE = /[​⁠﻿᠎­]/gu;
/** ZWNJ / ZWJ - legitimate in emoji sequences and in Arabic/Indic shaping, so context-checked. */
const ZW_JOINERS = /[‌‍]/gu;
/** Unicode tag characters - a known scheme for smuggling invisible ASCII. */
const TAG_CHARS = /[\u{E0000}-\u{E007F}]/gu;
/** Ideographic variation selectors (VS17-256) - almost never legitimate outside rare CJK IVD. */
const VS_SUPPLEMENTARY = /[\u{E0100}-\u{E01EF}]/gu;
/** Runs of two or more BMP variation selectors - a byte-smuggling pattern. */
const VS_BMP_RUN = /[︀-️]{2,}/gu;
/** Bidi OVERRIDES (LRO/RLO) - the trojan-source vector; embeddings/isolates are left alone (RTL uses them). */
const BIDI_OVERRIDE = /[‭‮]/gu;
/** Non-standard spaces. NBSP and narrow-NBSP are carved out where French typography wants them. */
const ANOMALOUS_SPACE = /[ -  　]/gu;

/** Extended-pictographic test, to skip ZWJ that is joining an emoji sequence. */
const PICTOGRAPHIC = /\p{Extended_Pictographic}/u;
/** Scripts that share confusable glyphs with Latin. */
const CONFUSABLE_WITH_LATIN = /[\p{Script=Cyrillic}\p{Script=Greek}]/u;

interface RawSpan {
  index: number;
  length: number;
}

function collect(re: RegExp, text: string): RawSpan[] {
  const out: RawSpan[] = [];
  re.lastIndex = 0;
  for (let m = re.exec(text); m !== null; m = re.exec(text)) {
    out.push({ index: m.index, length: m[0].length });
    if (m[0].length === 0) re.lastIndex++; // guard against zero-width matches looping
  }
  return out;
}

/** Codepoint at a UTF-16 index, tolerant of surrogate pairs and string ends. */
function charAt(text: string, i: number): string {
  if (i < 0 || i >= text.length) return '';
  return String.fromCodePoint(text.codePointAt(i) as number);
}

/**
 * ZWJ/ZWNJ occurrences that are NOT joining an emoji sequence and NOT between
 * two non-Latin letters (Arabic/Indic shaping). What remains is suspicious.
 */
function suspiciousJoiners(text: string): RawSpan[] {
  return collect(ZW_JOINERS, text).filter(({ index }) => {
    const before = charAt(text, index - 1);
    const after = charAt(text, index + 1);
    if (PICTOGRAPHIC.test(before) || PICTOGRAPHIC.test(after)) return false;
    // Between two letters of a shaping script, a joiner is plausibly legitimate.
    const shaping = /[\p{Script=Arabic}\p{Script=Devanagari}\p{Script=Bengali}\p{Script=Tamil}]/u;
    if (shaping.test(before) && shaping.test(after)) return false;
    return true;
  });
}

/** Tokens (letter runs) that mix Latin with a confusable script - a homoglyph tell. */
function mixedScriptTokens(text: string): RawSpan[] {
  const out: RawSpan[] = [];
  const tokenRe = /\p{L}[\p{L}\p{M}]*/gu;
  for (let m = tokenRe.exec(text); m !== null; m = tokenRe.exec(text)) {
    const tok = m[0];
    if (/\p{Script=Latin}/u.test(tok) && CONFUSABLE_WITH_LATIN.test(tok)) {
      out.push({ index: m.index, length: tok.length });
    }
  }
  return out;
}

/** NBSP / narrow-NBSP runs, minus the French carve-out (before ; : ! ? and as a group separator). */
function anomalousNbsp(text: string): RawSpan[] {
  const out: RawSpan[] = [];
  const re = /[  ]/gu;
  for (let m = re.exec(text); m !== null; m = re.exec(text)) {
    const after = charAt(text, m.index + 1);
    // French: NBSP before high punctuation, or narrow-NBSP between digit groups.
    if (';:!?»'.includes(after)) continue;
    const before = charAt(text, m.index - 1);
    if (/\d/.test(before) && /\d/.test(after)) continue;
    out.push({ index: m.index, length: 1 });
  }
  return out;
}

// ─── Heuristic-tier detectors (English, long-enough text only) ─────────────────

/**
 * A curated LLM-lexicon: single words and phrases over-represented in AI prose.
 * Several of these are exactly the tics Lolly bans in its OWN copy, which is why
 * this list can seed from that same style guidance.
 */
const LLM_WORDS = [
  'delve', 'delving', 'tapestry', 'testament', 'boasts', 'underscore', 'underscores',
  'underscoring', 'nuanced', 'nuance', 'realm', 'realms', 'showcase', 'showcasing',
  'leverage', 'leveraging', 'foster', 'fostering', 'seamless', 'seamlessly', 'robust',
  'holistic', 'intricate', 'intricacies', 'pivotal', 'paramount', 'myriad', 'plethora',
  'garner', 'elevate', 'elevating', 'embark', 'vibrant', 'bustling', 'meticulous',
  'meticulously', 'comprehensive', 'unlock', 'unlocking', 'harness', 'harnessing',
];
const LLM_PHRASES = [
  "it's important to note", 'it is important to note', "it's worth noting",
  'in conclusion', 'in the realm of', 'when it comes to', 'a testament to',
  'plays a crucial role', 'plays a vital role', 'rich tapestry', 'navigating the',
  'that being said', 'dive into', "let's dive", 'in summary', 'ever-evolving',
  'fast-paced', 'cutting-edge', 'game-changer', 'at the end of the day',
  'the world of', 'in today', 'when it comes down to',
];

function letterStats(text: string): { total: number; latin: number } {
  let total = 0;
  let latin = 0;
  for (const ch of text) {
    if (/\p{L}/u.test(ch)) {
      total++;
      if (/\p{Script=Latin}/u.test(ch)) latin++;
    }
  }
  return { total, latin };
}

function wordCount(text: string): number {
  const m = text.match(/\p{L}[\p{L}\p{M}'-]*/gu);
  return m ? m.length : 0;
}

/** Sentence lengths in words - for the burstiness measure. */
function sentenceWordLengths(text: string): number[] {
  return text
    .split(/[.!?]+[\s"')\]]+|\n+/u)
    .map((s) => wordCount(s))
    .filter((n) => n > 0);
}

// ─── Banding ──────────────────────────────────────────────────────────────────

const HEURISTIC_CAP = 3; // heuristics alone never reach 'strong'.

function bandFrom(artifactScore: number, heuristicScore: number): TextSignalBand {
  if (artifactScore >= 4) return 'strong';
  if (artifactScore === 0) {
    // Style-only: capped at 'notable' - style is not proof.
    if (heuristicScore >= 3) return 'notable';
    if (heuristicScore >= 1.5) return 'weak';
    return 'none';
  }
  const combined = artifactScore + Math.min(heuristicScore, HEURISTIC_CAP);
  if (combined >= 4) return 'strong';
  if (combined >= 2) return 'notable';
  if (combined >= 1) return 'weak';
  return 'none';
}

function summaryFor(band: TextSignalBand, pixelSourced: boolean): string {
  const base: Record<TextSignalBand, string> = {
    none: 'No AI-generation signals were found in this text.',
    weak: 'A few weak signals were found. Nothing here is conclusive.',
    notable: 'Several signals consistent with AI-generated text were found. This is not proof.',
    strong: 'Strong signals were found, including tells that are rare in ordinary writing. This is a signal, not proof.',
  };
  const note = pixelSourced
    ? ' The text was read from an image, so hidden-character and watermark checks could not run. Only writing-style signals were assessed.'
    : '';
  return base[band] + note;
}

/**
 * A stylistic-only family guess. It deliberately returns 'generic-LLM' for now:
 * naming a specific product from writing style is not credible, so v1 does not,
 * pending the sign-off on which families (if any) may be named. The rationale
 * carries the markers so the UI can show WHY, hedged.
 */
function styleGuessFrom(heuristicFindings: TextSignalFinding[]): TextStyleGuess | undefined {
  if (heuristicFindings.length === 0) return undefined;
  const markers = heuristicFindings.map((f) => f.label.toLowerCase()).join('; ');
  return {
    family: 'generic-LLM',
    confidence: 'low',
    rationale: `Writing-style markers only (${markers}). Consistent with AI-assisted text, but style cannot identify a specific model.`,
  };
}

// ─── The analyser ─────────────────────────────────────────────────────────────

/**
 * Analyse `text` for AI-generation signals. `opts.source` decides which tiers run:
 * 'digital' runs the artifact tier plus the heuristic tier; 'ocr' runs the
 * heuristic tier only (and sets `pixelSourced`), because a rasterised read has no
 * byte-level layer to inspect.
 *
 * Pure and synchronous. A best-effort SIGNAL, never a verdict.
 */
export function analyzeTextSignals(text: string, opts: AnalyzeTextSignalsOpts): TextSignalReport {
  const source = opts.source;
  const pixelSourced = source === 'ocr';
  const findings: TextSignalFinding[] = [];

  // ── Artifact tier (digital only) ──
  if (!pixelSourced && text.length > 0) {
    const invisible = [...collect(INVISIBLE_CORE, text), ...suspiciousJoiners(text)];
    if (invisible.length > 0) {
      findings.push({
        tier: 'artifact',
        kind: 'invisible-char',
        label: 'Invisible characters',
        detail: `${invisible.length} zero-width or invisible character${invisible.length === 1 ? '' : 's'} that ordinary text does not contain.`,
        weight: 2 + (invisible.length >= 4 ? 1 : 0),
        spans: invisible,
      });
    }

    const tags = collect(TAG_CHARS, text);
    if (tags.length > 0) {
      findings.push({
        tier: 'artifact',
        kind: 'tag-chars',
        label: 'Hidden tag characters',
        detail: `${tags.length} Unicode tag character${tags.length === 1 ? '' : 's'}, a known way to smuggle invisible data into text.`,
        weight: 4,
        spans: tags,
      });
    }

    const vs = [...collect(VS_SUPPLEMENTARY, text), ...collect(VS_BMP_RUN, text)];
    if (vs.length > 0) {
      findings.push({
        tier: 'artifact',
        kind: 'variation-selectors',
        label: 'Unusual variation selectors',
        detail: `${vs.length} variation-selector sequence${vs.length === 1 ? '' : 's'}, which can carry hidden data.`,
        weight: 3,
        spans: vs,
      });
    }

    const bidi = collect(BIDI_OVERRIDE, text);
    if (bidi.length > 0) {
      findings.push({
        tier: 'artifact',
        kind: 'bidi-override',
        label: 'Bidirectional override characters',
        detail: `${bidi.length} left-to-right or right-to-left override${bidi.length === 1 ? '' : 's'}, which can hide or reorder text.`,
        weight: 3,
        spans: bidi,
      });
    }

    const mixed = mixedScriptTokens(text);
    if (mixed.length > 0) {
      findings.push({
        tier: 'artifact',
        kind: 'mixed-script',
        label: 'Mixed-script words',
        detail: `${mixed.length} word${mixed.length === 1 ? '' : 's'} mixing Latin with a look-alike script, a homoglyph tell.`,
        weight: 3,
        spans: mixed,
      });
    }

    const spaces = [...anomalousNbsp(text), ...collect(ANOMALOUS_SPACE, text)];
    if (spaces.length >= 2) {
      findings.push({
        tier: 'artifact',
        kind: 'anomalous-space',
        label: 'Unusual spacing',
        detail: `${spaces.length} non-standard space character${spaces.length === 1 ? '' : 's'}.`,
        weight: 1,
        spans: spaces,
      });
    }
  }

  // ── Heuristic tier (English, long-enough text only - the bias guard) ──
  const words = wordCount(text);
  const { total: letters, latin } = letterStats(text);
  const looksEnglish = letters === 0 ? false : latin / letters >= 0.6;
  const longEnough = words >= 40;
  const heuristicFindings: TextSignalFinding[] = [];

  if (looksEnglish && longEnough) {
    const lower = text.toLowerCase();

    let lexHits = 0;
    const lexSpans: RawSpan[] = [];
    for (const w of LLM_WORDS) {
      const re = new RegExp(`\\b${w}\\b`, 'giu');
      for (let m = re.exec(text); m !== null; m = re.exec(text)) {
        lexHits++;
        lexSpans.push({ index: m.index, length: m[0].length });
      }
    }
    for (const p of LLM_PHRASES) {
      let from = lower.indexOf(p);
      while (from !== -1) {
        lexHits++;
        lexSpans.push({ index: from, length: p.length });
        from = lower.indexOf(p, from + p.length);
      }
    }
    if (lexHits > 0) {
      const density = (lexHits / words) * 1000; // hits per 1000 words
      const weight = Math.min(3, 0.5 + density * 0.5);
      heuristicFindings.push({
        tier: 'heuristic',
        kind: 'llm-lexicon',
        label: 'AI-favoured wording',
        detail: `${lexHits} phrase${lexHits === 1 ? '' : 's'} over-represented in AI-written text.`,
        weight,
        spans: lexSpans,
      });
    }

    const emDashes = collect(/—/gu, text);
    if (emDashes.length >= 3) {
      heuristicFindings.push({
        tier: 'heuristic',
        kind: 'em-dash-density',
        label: 'Heavy em-dash use',
        detail: `${emDashes.length} em-dashes, a common tell in AI prose.`,
        weight: 1,
        spans: emDashes,
      });
    }

    const lines = text.split('\n');
    const bulletLines = lines.filter((l) => /^\s*([-*•]|\d+[.)])\s+/u.test(l)).length;
    if (lines.length >= 6 && bulletLines / lines.length >= 0.5) {
      heuristicFindings.push({
        tier: 'heuristic',
        kind: 'list-heavy',
        label: 'List-heavy structure',
        detail: `${bulletLines} of ${lines.length} lines are list items.`,
        weight: 1,
      });
    }

    const lens = sentenceWordLengths(text);
    if (lens.length >= 5) {
      const mean = lens.reduce((a, b) => a + b, 0) / lens.length;
      const variance = lens.reduce((a, b) => a + (b - mean) ** 2, 0) / lens.length;
      const cv = mean > 0 ? Math.sqrt(variance) / mean : 0;
      // Human writing is bursty (high variation); very uniform medium-length
      // sentences read as machine-smoothed.
      if (cv < 0.35 && mean >= 8) {
        heuristicFindings.push({
          tier: 'heuristic',
          kind: 'uniform-burstiness',
          label: 'Unusually uniform sentences',
          detail: 'Sentence lengths vary little, which is uncommon in human writing.',
          weight: 1,
        });
      }
    }
  }

  findings.push(...heuristicFindings);

  const artifactScore = findings.filter((f) => f.tier === 'artifact').reduce((a, f) => a + f.weight, 0);
  const heuristicScore = heuristicFindings.reduce((a, f) => a + f.weight, 0);
  const band = bandFrom(artifactScore, heuristicScore);

  findings.sort((a, b) => b.weight - a.weight);

  const styleGuess = band === 'notable' || band === 'strong' ? styleGuessFrom(heuristicFindings) : undefined;

  return {
    source,
    pixelSourced,
    band,
    findings,
    styleGuess,
    summary: summaryFor(band, pixelSourced),
  };
}
